# Wildfire Knowledge Graph Evaluation

This notebook evaluates the performance of a wildfire knowledge graph agent by testing it on a variety of questions and comparing responses to expected outputs. The evaluation uses LangSmith to track performance metrics including response accuracy and tool usage.

> **Important:** This evaluation framework requires proper environment setup including LangSmith API keys and access to LLM endpoints. Make sure to configure the `.env` file before running. Also be sure to restart the kernel after each pipeline execution or the next evaluation run will not appear the LangSmith UI.

In [1]:
import json
import pandas as pd
from typing import Dict, List, Any, Optional
from langsmith import Client
from langsmith.schemas import Example, Run, ExampleCreate
import asyncio
from dotenv import load_dotenv
import nest_asyncio
from datetime import datetime
from langchain_core.runnables.config import RunnableConfig
from collections import Counter
import os
import logging
import pathlib

# Load environment variables
load_dotenv(dotenv_path="../../applications/wildfire-kg-api/.env")

# Import the agent after loading the environment variables
from wildfire_kg_api.orchestration.agent import create_wildfire_react_agent
from wildfire_kg_api.orchestration.state import State
from wildfire_kg_api.orchestration.models import (
    AVAILABLE_MODELS,
    LITELLM_MODELS,
    OPENAI_MODELS,
    AGENT_COMPATIBLE_MODELS,
    is_agent_compatible,
    get_default_temperature,
)

# Initialize LangSmith client
client = Client()

# Data paths
DATA_PATH = "../../data/evaluation"

## Experiment Configuration

The evaluation framework is designed to test different combinations of openai and litellm models and their parameters. Here's how the configurations work:

1. **Agent Models**: These are the models used for the main agent that handles user queries and tool selection. Currently set to test with `llama3-sdsc`.
   - Available agent models must support the ReAct pattern for tool usage
   - Full list of compatible models available in `AGENT_COMPATIBLE_MODELS`
   - Models must be capable of structured reasoning and tool invocation

2. **Knowledge Graph Models**: These models are used specifically for knowledge graph operations. Also set to use `llama3-sdsc`.
   - All available models in `AVAILABLE_MODELS` can be used for KG operations
   - Models must be capable of SPARQL query generation and understanding

3. **Temperature Settings**: Controls the randomness/creativity of model outputs. Currently testing with a temperature of 0.1.

The framework will automatically generate all valid combinations of these settings. For example, with the current configuration:
- Agent Model: llama3-sdsc
- KG Model: llama3-sdsc
- Temperature: 0.1

This results in one experiment configuration that tests this specific combination. The framework is designed to be easily extended to test more combinations by modifying the configuration lists above.

To test different model combinations, you can uncomment and modify the following configuration lines:
```python
AGENT_MODELS_TO_TEST = AGENT_COMPATIBLE_MODELS  # Test all compatible agent models
KG_MODELS_TO_TEST = AVAILABLE_MODELS  # Test all available KG models
TEMPERATURES_TO_TEST = [0.0, 0.1, 0.2]  # Test multiple temperature settings
```

In [2]:
# ============================================================================
# CONFIGURATION INPUTS
# ============================================================================
# Models that can be used as agents (must support ReAct pattern)
# AGENT_MODELS_TO_TEST = AGENT_COMPATIBLE_MODELS
AGENT_MODELS_TO_TEST = ["llama3-sdsc"]
# AGENT_MODELS_TO_TEST = ["gpt-4.1-mini"]

# Models that can be used for knowledge graph tools (don't need ReAct pattern)
# KG_MODELS_TO_TEST = AVAILABLE_MODELS  # All models can be used for KG tools
KG_MODELS_TO_TEST = ["llama3-sdsc"]
# KG_MODELS_TO_TEST = ["gpt-4.1-mini"]

# Temperatures to test
# TEMPERATURES_TO_TEST = [0.0, 0.1, 0.2]
TEMPERATURES_TO_TEST = [0.1]

# ============================================================================
# GENERATE ACTIVE EXPERIMENT CONFIGURATIONS
# ============================================================================
active_experiment_configs: List[Dict[str, Any]] = []

# Define a list of temperatures to iterate over for configurable models.
# If TEMPERATURES_TO_TEST is empty, use [None] to signify one run using model defaults or fixed behavior.
effective_temps_for_iteration = TEMPERATURES_TO_TEST if TEMPERATURES_TO_TEST else [None]

print("Generating experiment configurations...")
for agent_model in AGENT_MODELS_TO_TEST:
    is_agent_temp_configurable = get_default_temperature(agent_model) is not None
    # Temps to loop for the current agent model:
    # - If configurable, use all effective_temps_for_iteration.
    # - If not configurable, use only [None] to represent a single, non-varied setting.
    agent_model_temps_to_loop = (
        effective_temps_for_iteration if is_agent_temp_configurable else [None]
    )

    for agent_temp_setting in agent_model_temps_to_loop:
        for kg_model in KG_MODELS_TO_TEST:
            if not KG_MODELS_TO_TEST:
                print(
                    f"Warning: KG_MODELS_TO_TEST is empty. Skipping KG model loop for agent {agent_model}."
                )
                continue

            is_kg_temp_configurable = get_default_temperature(kg_model) is not None
            # Temps to loop for the current KG model:
            kg_model_temps_to_loop = (
                effective_temps_for_iteration if is_kg_temp_configurable else [None]
            )

            for kg_temp_setting in kg_model_temps_to_loop:
                config_entry = {
                    "agent_model": agent_model,
                    "agent_temperature_config": agent_temp_setting,
                    "kg_model": kg_model,
                    "kg_temperature_config": kg_temp_setting,
                }
                active_experiment_configs.append(config_entry)

print(
    f"Generated {len(active_experiment_configs)} experiment configurations to run (all combinations of agent/KG models with independent temperatures where applicable):"
)
for i, cfg in enumerate(active_experiment_configs):
    agent_temp_display = (
        cfg["agent_temperature_config"]
        if cfg["agent_temperature_config"] is not None
        else "N/A"
    )
    kg_temp_display = (
        cfg["kg_temperature_config"]
        if cfg["kg_temperature_config"] is not None
        else "N/A"
    )
    print(
        f"  {i+1}. Agent: {cfg['agent_model']} (Temp: {agent_temp_display}), KG: {cfg['kg_model']} (Temp: {kg_temp_display})"
    )

if not active_experiment_configs and any([AGENT_MODELS_TO_TEST, KG_MODELS_TO_TEST]):
    print(
        "Warning: No experiment configurations were generated. This might be due to empty TEMPERATURES_TO_TEST list when it was expected to have values, or other logic issues. Evaluation will not run."
    )
elif not active_experiment_configs:
    print(
        "Warning: No experiment configurations generated as AGENT_MODELS_TO_TEST or KG_MODELS_TO_TEST might be empty. Evaluation will not run."
    )

Generating experiment configurations...
Generated 1 experiment configurations to run (all combinations of agent/KG models with independent temperatures where applicable):
  1. Agent: llama3-sdsc (Temp: 0.1), KG: llama3-sdsc (Temp: 0.1)

## Dataset Configuration

Define the datasets to be used for evaluation. Each dataset should have:
- A unique name
- A description
- A path to the data file
- Expected tools and tags

The framework supports multiple types of evaluation datasets:
1. **Knowledge Graph Datasets**:
   - Tree/Shrub metrics evaluation
   - Fire behavior metrics evaluation
   - Vegetation metrics evaluation
2. **Tool-specific Datasets**:
   - Web search evaluation
   - Weather metrics evaluation
3. **Quick Test Dataset**:
   - Currently active for rapid testing

Each dataset should be in JSONL format with the following structure:
```json
{
  "user_query": "The question to evaluate",
  "expected_response_contains": ["Expected response elements"],
  "tags": ["relevant", "tags"],
  "expected_tools": ["tools", "to", "use"]
}
```

To enable additional datasets, uncomment the relevant entries in the `datasets` list below.

In [3]:

# Dataset configuration
datasets = [
    {
        "name": "tree-shrub-metrics",
        "description": "Knowledge graph tree shrub metrics evaluation dataset",
        "data_path": f"{DATA_PATH}/kg_tool/tree_shrub_metrics.jsonl",
    },
    {
        "name": "fire-behavior-metrics",
        "description": "Knowledge graph fire behavior metrics evaluation dataset",
        "data_path": f"{DATA_PATH}/kg_tool/fire_behavior_metrics.jsonl",
    },
    {
        "name": "vegetation-metrics",
        "description": "Knowledge graph vegetation metrics evaluation dataset",
        "data_path": f"{DATA_PATH}/kg_tool/vegetation_metrics.jsonl",
    },
    {
        "name": "web-search-basic",
        "description": "Web search basic evaluation dataset",
        "data_path": f"{DATA_PATH}/web_search_tool/web_search_basic.jsonl",
    },
    {
        "name": "weather-basic",
        "description": "Weather basic evaluation dataset",
        "data_path": f"{DATA_PATH}/weather_tool/weather_basic.jsonl",
    },
    {
        "name": "no-tools-basic",
        "description": "No-tools basic evaluation dataset",
        "data_path": f"{DATA_PATH}/no_tools/no_tools_basic.jsonl",
    },
    {
        "name": "mixed-basic",
        "description": "Mixed tools basic evaluation dataset",
        "data_path": f"{DATA_PATH}/mixed/mixed_basic.jsonl",
    },
    # {
    #     "name": "mini-eval",
    #     "description": "Mini eval dataset",
    #     "data_path": f"{DATA_PATH}/splits/mini_eval.jsonl",
    # },
    # {
    #     "name": "quick-test",
    #     "description": "Quick test dataset",
    #     "data_path": f"{DATA_PATH}/splits/quick_test.jsonl",
    # },
]

## Evaluation Setup

We'll use the following components for evaluation:

1. **Data Loading**:
   - Load test cases from JSONL files containing questions and expected responses
   - Each test case includes user queries, expected responses, and tool usage expectations
   - Data is converted into LangSmith examples for tracking and analysis

2. **LangSmith Integration**:
   - Track runs and evaluate responses with LangSmith
   - Create datasets with unique identifiers for each evaluation run
   - Store experiment results and metadata for analysis

3. **Evaluators**:
   - Response Content Evaluator: Uses GPT-3.5-turbo to assess if responses contain expected information
   - Tool Usage Evaluator: Checks if the agent used the correct tools during execution
   - Both evaluators provide scores (0.0-1.0) and detailed feedback

4. **Agent Execution**:
   - Run the wildfire knowledge graph agent on each test case
   - Support for async execution with configurable concurrency
   - Automatic retries and error handling

The evaluation process is designed to be:
- Reproducible: Each run is tracked with unique identifiers
- Configurable: Easy to modify test cases and evaluation parameters
- Scalable: Can handle multiple model configurations and datasets
- Detailed: Provides comprehensive feedback on both response quality and tool usage

In [4]:
# Load evaluation data
def load_evaluation_data(file_path: str) -> List[Dict[str, Any]]:
    with open(file_path, "r") as f:
        return [json.loads(line) for line in f]


# Convert evaluation data to LangSmith examples
def create_langsmith_examples(
    eval_data: List[Dict[str, Any]],
    dataset_config: Dict[str, Any],
    agent_model_name: str,
    temperature_to_test: float,
    kg_model_name: str = None,
) -> List[ExampleCreate]:
    """
    Create LangSmith examples for evaluation.

    Args:
        eval_data: List of evaluation data items
        dataset_config: Dataset configuration
        agent_model_name: Name of the agent model to test
        temperature_to_test: Temperature setting to test
        kg_model_name: Name of the KG model to test (defaults to agent_model_name if None)

    Returns:
        List of LangSmith examples
    """
    # If kg_model_name not specified, use agent_model_name
    if kg_model_name is None:
        kg_model_name = agent_model_name

    examples = []
    for item in eval_data:
        examples.append(
            ExampleCreate(
                inputs={
                    "question": item["user_query"],
                    "agent_model": agent_model_name,
                    "kg_model": kg_model_name,
                    "temperature": temperature_to_test,
                },
                outputs={"expected_response": item["expected_response_contains"]},
                metadata={
                    "tags": item["tags"],
                    "expected_tools": item["expected_tools"],
                },
            )
        )
    return examples

## Evaluation Functions

We use two main evaluators:

1. **Response Content Evaluator**: Uses an LLM to determine if responses contain all expected information
2. **Tool Usage Evaluator**: Checks if the agent used the correct tools during its execution

In [5]:
# Create evaluation functions
def evaluate_response_contains(run: Run, example: Example) -> Dict[str, Any]:
    """Evaluate if the response contains the expected information using an LLM as judge."""
    from langchain_openai import ChatOpenAI
    from langchain.prompts import ChatPromptTemplate
    from langchain_core.messages import (
        AIMessage,
        HumanMessage,
    )  # Added for type checking

    # Extract the response from messages
    messages = run.outputs.get("messages", [])
    if not messages:
        return {
            "key": "response_contains",
            "score": 0.0,
            "comment": "No messages found in output",
        }

    # Get the last message (usually the assistant's response)
    last_message_raw = messages[-1]
    actual_response = ""

    # Handle different message formats (direct content, AIMessage, dict)
    if isinstance(last_message_raw, str):
        actual_response = last_message_raw
    elif hasattr(last_message_raw, "content"):  # Covers AIMessage, HumanMessage etc.
        actual_response = last_message_raw.content
    elif isinstance(last_message_raw, dict) and "content" in last_message_raw:
        actual_response = last_message_raw["content"]
    else:  # Fallback if structure is unexpected
        actual_response = str(last_message_raw)

    # Get expected information
    expected_info = example.outputs.get("expected_response", [])
    # Format expected info for the prompt
    if isinstance(expected_info, list) and expected_info:
        # Create a bulleted list string for the prompt
        expected_str = "\n- " + "\n- ".join([str(item) for item in expected_info])
    elif isinstance(expected_info, str) and expected_info:  # If it's already a string
        expected_str = expected_info
    else:  # Fallback for other types or empty
        # Provide a clear string indicating no specific info was expected or it was malformed
        expected_str = (
            "\n- (No specific expected information provided or list was empty)"
        )

    # Create LLM for evaluation
    llm = ChatOpenAI(model="gpt-4.1-mini", temperature=0)

    # Create prompt for the LLM judgment
    template = """You are an evaluator assessing response accuracy.

You will be given an ACTUAL RESPONSE and a list of EXPECTED INFORMATION elements.
Your task is to determine if the ACTUAL RESPONSE contains ALL of the elements listed under EXPECTED INFORMATION.
The elements can appear anywhere in the response and do not need to be in the same order.
It is OK if the actual response contains more information than expected, as long as it includes ALL the required information elements.
The response should not contain any statements that contradict the expected information.

EXPECTED INFORMATION (all of these elements, or their clear semantic equivalents, should be present in the actual response):{expected_info}

Actual Response: {actual_response}

First, provide a brief analysis of whether each element from the EXPECTED INFORMATION list is present in the ACTUAL RESPONSE.
Then, provide a final score between 0.0 and 1.0, where:
- 1.0 means the ACTUAL RESPONSE completely and accurately contains all elements from EXPECTED INFORMATION.
- 0.0 means the ACTUAL RESPONSE contains none of the elements from EXPECTED INFORMATION, or contains significant inaccuracies related to them.
- Values in between represent partial matches (e.g., some elements are present, others are missing or inaccurate).

Your response must be in the following format:
Analysis: <your detailed analysis, addressing each expected element's presence and correctness>
Score: <a number between 0.0 and 1.0>
Explanation: <short explanation for the score based on the presence/absence/accuracy of expected elements>
"""

    prompt = ChatPromptTemplate.from_template(template)

    # Get evaluation from LLM
    result = llm.invoke(
        prompt.format(expected_info=expected_str, actual_response=actual_response)
    )
    response_text = result.content

    # Parse the LLM response to extract the score and explanation
    score = 0.0
    explanation = "Unable to parse LLM response"

    try:
        # Try to extract score using regex
        import re

        score_match = re.search(r"Score:\s*(0\.\d+|1\.0|1|0)", response_text)
        if score_match:
            score = float(score_match.group(1))

        # Extract explanation
        explanation_match = re.search(
            r"Explanation:\s*(.*?)($|\n\n)", response_text, re.DOTALL
        )
        if explanation_match:
            explanation = explanation_match.group(1).strip()
        else:
            # If no specific explanation section, use the whole response
            explanation = response_text
    except Exception as e:
        explanation = f"Error parsing LLM response: {str(e)}"

    return {
        "key": "response_contains",
        "score": score,
        "comment": explanation,
        "metadata": {"expected_info": expected_str, "llm_full_response": response_text},
    }


def evaluate_tool_usage(run: Run, example: Example) -> Dict[str, Any]:
    """Evaluate tool usage based on expected tools, penalizing missing, overuse, and unexpected calls."""
    expected_tools_list = example.metadata.get("expected_tools", [])
    expected_set = set(expected_tools_list)

    all_actual_invocations = []
    messages = run.outputs.get("messages", [])

    # Iterate through messages to find tool calls proposed by the AI
    for msg in messages:
        # LangChain AIMessage objects (and their dict representations)
        # often store tool calls in `tool_calls` or `additional_kwargs.tool_calls`

        current_msg_tool_calls = []

        # 1. Check `tool_calls` attribute directly on the message object
        # These are typically parsed from the model's output directly.
        if hasattr(msg, "tool_calls") and isinstance(msg.tool_calls, list):
            for tool_call in msg.tool_calls:
                if isinstance(tool_call, dict) and "name" in tool_call:
                    current_msg_tool_calls.append(str(tool_call["name"]))
                # Handle cases where tool_call might be an object with a 'name' attribute
                elif hasattr(tool_call, "name") and getattr(tool_call, "name", None):
                    current_msg_tool_calls.append(str(tool_call.name))

        # 2. Check `additional_kwargs` for tool_calls (common for OpenAI models)
        # This is often where the raw tool call requests from the LLM are stored.
        elif hasattr(msg, "additional_kwargs") and isinstance(
            msg.additional_kwargs, dict
        ):
            additional_kwargs = msg.additional_kwargs
            if "tool_calls" in additional_kwargs and isinstance(
                additional_kwargs["tool_calls"], list
            ):
                for tool_call_item in additional_kwargs["tool_calls"]:
                    # OpenAI format: tool_calls -> [ { "function": { "name": "..." } } ]
                    if (
                        isinstance(tool_call_item, dict)
                        and "function" in tool_call_item
                    ):
                        function_dict = tool_call_item["function"]
                        if isinstance(function_dict, dict) and "name" in function_dict:
                            current_msg_tool_calls.append(str(function_dict["name"]))
                    # Simpler format sometimes seen: tool_calls -> [ { "name": "..." } ]
                    elif isinstance(tool_call_item, dict) and "name" in tool_call_item:
                        current_msg_tool_calls.append(str(tool_call_item["name"]))

        # 3. Handle direct dictionary representation of messages (e.g. from serialization)
        elif isinstance(msg, dict):
            if "tool_calls" in msg and isinstance(msg["tool_calls"], list):
                for tool_call_dict in msg["tool_calls"]:
                    if isinstance(tool_call_dict, dict) and "name" in tool_call_dict:
                        current_msg_tool_calls.append(str(tool_call_dict["name"]))
            elif "additional_kwargs" in msg and isinstance(
                msg["additional_kwargs"], dict
            ):
                additional_kwargs_dict = msg["additional_kwargs"]
                if "tool_calls" in additional_kwargs_dict and isinstance(
                    additional_kwargs_dict["tool_calls"], list
                ):
                    for tool_call_item_dict in additional_kwargs_dict["tool_calls"]:
                        if (
                            isinstance(tool_call_item_dict, dict)
                            and "function" in tool_call_item_dict
                        ):
                            function_item_dict = tool_call_item_dict["function"]
                            if (
                                isinstance(function_item_dict, dict)
                                and "name" in function_item_dict
                            ):
                                current_msg_tool_calls.append(
                                    str(function_item_dict["name"])
                                )
                        elif (
                            isinstance(tool_call_item_dict, dict)
                            and "name" in tool_call_item_dict
                        ):
                            current_msg_tool_calls.append(
                                str(tool_call_item_dict["name"])
                            )

        # Add all tool calls found in this message to the main list.
        # This structure assumes one message contains all tool calls for a given step.
        all_actual_invocations.extend(current_msg_tool_calls)

    actual_counts = Counter(all_actual_invocations)

    score = 1.0
    # Define penalties
    penalty_for_missing_expected_tool = (
        0.5  # Penalty if an expected tool is not called at all
    )
    penalty_per_unique_unexpected_tool = (
        0.25  # Penalty for each type of unexpected tool used
    )
    penalty_per_extra_invocation_of_any_tool = (
        0.1  # Penalty for each call beyond the first, for ANY tool
    )
    min_score_if_any_expected_called = (
        0.3  # Floor if at least one expected tool was called
    )

    comments = []
    any_expected_tool_called_flag = False

    # 1. Evaluate expected tools (missing, and overuse of expected tools)
    for tool_name in expected_set:
        call_count = actual_counts.get(tool_name, 0)
        if call_count > 0:
            any_expected_tool_called_flag = True
            if call_count > 1:
                score -= (call_count - 1) * penalty_per_extra_invocation_of_any_tool
                comments.append(
                    f"Expected tool '{tool_name}' called {call_count} times (expected once)"
                )
        else:  # Expected tool was not called
            score -= penalty_for_missing_expected_tool
            comments.append(f"Missing expected tool: {tool_name}")

    # 2. Evaluate unexpected tools (penalty for each unique unexpected tool + overuse of unexpected tools)
    unique_unexpected_tools_called = []
    for tool_name, call_count in actual_counts.items():
        if tool_name not in expected_set:
            if (
                tool_name not in unique_unexpected_tools_called
            ):  # Apply unique penalty only once per tool type
                score -= penalty_per_unique_unexpected_tool
                unique_unexpected_tools_called.append(tool_name)

            # Now, penalize overuse for this unexpected tool if called more than once
            if call_count > 1:
                score -= (call_count - 1) * penalty_per_extra_invocation_of_any_tool

            # Consolidate comments for unexpected tools later or add more detail here if needed

    if unique_unexpected_tools_called:
        unexpected_details = []
        for tool_name in unique_unexpected_tools_called:
            count = actual_counts[tool_name]
            detail = f"'{tool_name}' (called {count} times)"
            unexpected_details.append(detail)
        comments.append(f"Used unexpected tools: {(', '.join(unexpected_details))}")

    # Apply minimum score rule and cap
    if any_expected_tool_called_flag and score < min_score_if_any_expected_called:
        score = min_score_if_any_expected_called

    final_score = max(0.0, min(1.0, score))

    if (
        not comments
        and final_score == 1.0
        and not expected_set
        and not all_actual_invocations
    ):
        comment_str = "No tools were expected, and no tools were used."
    elif not comments and final_score == 1.0:
        comment_str = f"Used exactly the expected tools: {', '.join(sorted(list(expected_set)))} (each once)."
    elif not comments:  # Should ideally not happen if score is not 1.0
        comment_str = "Tool usage evaluation resulted in a score change, but no specific comments generated."
    else:
        comment_str = "; ".join(comments)

    return {
        "key": "tool_usage",
        "score": final_score,
        "comment": comment_str,
        "metadata": {
            "expected_tools": expected_tools_list,
            "actual_tool_invocations": all_actual_invocations,
            "actual_tool_counts": dict(actual_counts),
        },
    }

## Run Evaluation

Now we'll load the test data, create LangSmith datasets, and run the evaluation on our agent.

In [6]:
# Run evaluation for all datasets
async def run_experiments():
    if not active_experiment_configs:
        print("No active experiment configurations. Skipping evaluation runs.")
        return []

    print(f"Testing with {len(active_experiment_configs)} generated configurations.")

    all_experiment_results_summary = (
        []
    )  # To store high-level results from each experiment run

    # Generate timestamp for this evaluation run
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Create a single dataset with examples that don't include model-specific parameters
    print("\n=== Creating shared evaluation dataset ===")
    dataset_examples = []

    # Load examples from all datasets
    for dataset_file_config in datasets:
        print(f"Loading dataset: {dataset_file_config['name']}")
        eval_data = load_evaluation_data(dataset_file_config["data_path"])

        # Create examples without model-specific parameters
        for item in eval_data:
            dataset_examples.append(
                ExampleCreate(
                    inputs={"question": item["user_query"]},
                    outputs={"expected_response": item["expected_response_contains"]},
                    metadata={
                        "tags": item.get("tags", []),
                        "expected_tools": item.get("expected_tools", []),
                    },
                )
            )

        print(f"  Added {len(eval_data)} examples from {dataset_file_config['name']}")

    # Create the shared dataset
    shared_dataset_name = f"wildfire-kg-eval-{timestamp}"
    print(f"\nCreating dataset: {shared_dataset_name}")
    shared_dataset = client.create_dataset(
        dataset_name=shared_dataset_name,
        description=f"Wildfire KG evaluation dataset for multiple model configurations",
    )

    # Add examples to the dataset
    client.create_examples(
        dataset_id=shared_dataset.id,
        examples=dataset_examples,
    )
    print(f"Created dataset with {len(dataset_examples)} examples")

    # Run experiments for different model configurations
    for exp_config in active_experiment_configs:
        agent_model = exp_config["agent_model"]
        kg_model = exp_config["kg_model"]
        agent_temp_config_val = exp_config["agent_temperature_config"]
        kg_temp_config_val = exp_config["kg_temperature_config"]

        # These checks are now primarily for clear logging; actual config handled by `None` values passed to get_llm_params
        is_agent_temp_configurable = get_default_temperature(agent_model) is not None
        is_kg_temp_configurable = get_default_temperature(kg_model) is not None

        agent_temp_display_log = (
            agent_temp_config_val if agent_temp_config_val is not None else "N/A"
        )
        kg_temp_display_log = (
            kg_temp_config_val if kg_temp_config_val is not None else "N/A"
        )

        print(
            f"\n{'='*80}\n"
            f"Evaluating with (from pre-generated config):\n"
            f"  Agent Model: {agent_model} (Configurable Temp: {is_agent_temp_configurable}, Setting: {agent_temp_display_log})\n"
            f"  KG Model: {kg_model} (Configurable Temp: {is_kg_temp_configurable}, Setting: {kg_temp_display_log})\n"
            f"{'='*80}"
        )

        run_config = RunnableConfig(
            configurable={
                "agent_model_name": agent_model,
                "agent_temperature": agent_temp_config_val,  # Pass agent temp; LLM setup will handle applicability
                "kg_model_name": kg_model,
                "kg_temperature": kg_temp_config_val,  # Pass KG temp; LLM setup will handle applicability
                "verbose": True,
            },
        )

        agent_temp_str_for_prefix = (
            str(agent_temp_config_val).replace(".", "_")
            if agent_temp_config_val is not None
            else "N/A"
        )
        kg_temp_str_for_prefix = (
            str(kg_temp_config_val).replace(".", "_")
            if kg_temp_config_val is not None
            else "N/A"
        )

        experiment_prefix = f"AGT:{agent_model.replace('/', '_')}-{agent_temp_str_for_prefix}_KG:{kg_model.replace('/', '_')}-{kg_temp_str_for_prefix}-{timestamp}"
        print(f"Running experiment: {experiment_prefix}")

        agent_graph = create_wildfire_react_agent(config=run_config)

        async def target_func(inputs):
            question = inputs.get("question", "")
            from langchain_core.messages import HumanMessage

            result = await agent_graph.ainvoke(
                {"messages": [HumanMessage(content=question)]},
                config=run_config,
            )
            return result

        experiment_run_details = await client.aevaluate(
            target_func,
            data=shared_dataset_name,
            evaluators=[evaluate_response_contains, evaluate_tool_usage],
            experiment_prefix=experiment_prefix,
            metadata={
                "agent_model": agent_model,
                "kg_model": kg_model,
                "agent_temperature_config": agent_temp_config_val,
                "kg_temperature_config": kg_temp_config_val,
            },
            num_repetitions=2,
            max_concurrency=4,
        )
        print(
            f"Evaluation complete for agent={agent_model} (temp_cfg={agent_temp_config_val}), kg={kg_model} (temp_cfg={kg_temp_config_val})"
        )

        results_df = experiment_run_details.to_pandas()

        response_accuracy = float("nan")
        if "feedback.response_contains" in results_df.columns:
            response_scores = results_df["feedback.response_contains"].dropna().tolist()
            if response_scores:
                response_accuracy = sum(response_scores) / len(response_scores)

        tool_accuracy = float("nan")
        if "feedback.tool_usage" in results_df.columns:
            tool_scores = results_df["feedback.tool_usage"].dropna().tolist()
            if tool_scores:
                tool_accuracy = sum(tool_scores) / len(tool_scores)

        print(f"\nResults Summary:")
        print(f"{'='*50}")
        print(
            f"Response Accuracy: {response_accuracy:.2%}"
            if not pd.isna(response_accuracy)
            else "Response Accuracy: N/A"
        )
        print(
            f"Tool Usage Accuracy: {tool_accuracy:.2%}"
            if not pd.isna(tool_accuracy)
            else "Tool Usage Accuracy: N/A"
        )
        print(f"{'='*50}")

        all_experiment_results_summary.append(
            {
                "model_name": agent_model,
                "kg_model_name": kg_model,
                "agent_temperature_config": agent_temp_config_val,
                "kg_temperature_config": kg_temp_config_val,
                "dataset_name": shared_dataset_name,
                "results_dataframe": results_df,
                "response_accuracy": response_accuracy,
                "tool_accuracy": tool_accuracy,
                "total_examples": len(dataset_examples),
            }
        )

    print("\n" + "=" * 80)
    print("ALL EVALUATIONS COMPLETE")
    print("=" * 80)

    # Create a summary table of all results
    summary_data = []
    for summary in all_experiment_results_summary:
        summary_data.append(
            {
                "Agent Model": summary["model_name"],
                "KG Model": summary["kg_model_name"],
                "Agent Temperature": summary["agent_temperature_config"],
                "KG Temperature": summary["kg_temperature_config"],
                "Response Accuracy": (
                    f"{summary['response_accuracy']:.2%}"
                    if not pd.isna(summary["response_accuracy"])
                    else "N/A"
                ),
                "Tool Usage Accuracy": (
                    f"{summary['tool_accuracy']:.2%}"
                    if not pd.isna(summary["tool_accuracy"])
                    else "N/A"
                ),
                "Examples": summary["total_examples"],
                "Dataset": summary["dataset_name"],
            }
        )

    summary_df = pd.DataFrame(summary_data)
    print("\nOverall Results Summary:")
    print("=" * 80)
    display(summary_df)
    print("=" * 80)

    print("Evaluation complete - view detailed results in the LangSmith UI")

    return all_experiment_results_summary


# For Jupyter notebook execution
try:
    nest_asyncio.apply()
    print("Running evaluations...")
    # 'results' will now be a list of summaries, one for each model/temp configuration
    all_results_summary = asyncio.get_event_loop().run_until_complete(run_experiments())
    print("All evaluations complete!")

    # Display results for each dataset
    print("\n\n--- Overall Summary of Evaluation Runs ---")
    for summary in all_results_summary:
        print(
            f"\nModel: {summary['model_name']}, KG Model: {summary['kg_model_name']}, Temperature: {summary['agent_temperature_config']}, {summary['kg_temperature_config']}"
        )
        print(
            f"  Response Accuracy: {summary['response_accuracy']:.2%}"
            if not pd.isna(summary["response_accuracy"])
            else "  Response Accuracy: N/A"
        )
        print(
            f"  Tool Usage Accuracy: {summary['tool_accuracy']:.2%}"
            if not pd.isna(summary["tool_accuracy"])
            else "  Tool Usage Accuracy: N/A"
        )
        print("  Detailed results table:")
        display(
            summary["results_dataframe"]
        )  # Display the pandas DataFrame for this run

except Exception as e:
    print(f"Error running evaluations: {e}")
    import traceback

    traceback.print_exc()

Running evaluations...
Testing with 1 generated configurations.

=== Creating shared evaluation dataset ===
Loading dataset: tree-shrub-metrics
  Added 7 examples from tree-shrub-metrics
Loading dataset: fire-behavior-metrics
  Added 5 examples from fire-behavior-metrics
Loading dataset: vegetation-metrics
  Added 9 examples from vegetation-metrics
Loading dataset: web-search-basic
  Added 3 examples from web-search-basic
Loading dataset: weather-basic
  Added 5 examples from weather-basic
Loading dataset: no-tools-basic
  Added 3 examples from no-tools-basic
Loading dataset: mixed-basic
  Added 2 examples from mixed-basic

Creating dataset: wildfire-kg-eval-20250605_171033

2025-06-05 17:10:35,116 - wildfire_kg.agent - INFO - Creating graph with provided config.
2025-06-05 17:10:35,116 - wildfire_kg.agent - INFO - Graph config: {'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True}}
2025-06-05 17:10:35,117 - wildfire_kg.agent - INFO - Attempting to create ReAct agent with model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:10:35,117 - wildfire_kg.agent - INFO - Final LLM params for agent: {'model': 'llama3-sdsc', 'callbacks': [], 'tags': [], 'metadata': {}, 'verbose': True, 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:10:35,187 - wildfire_kg.tools.web_search - DEBUG - Initializing DuckDuckGo Search with default string output and 3 results limit

Created dataset with 34 examples

================================================================================
Evaluating with (from pre-generated config):
  Agent Model: llama3-sdsc (Configurable Temp: True, Setting: 0.1)
  KG Model: llama3-sdsc (Configurable Temp: True, Setting: 0.1)
================================================================================
Running experiment: AGT:llama3-sdsc-0_1_KG:llama3-sdsc-0_1-20250605_171033

2025-06-05 17:10:35,410 - wildfire_kg.prompts - DEBUG - Loading prompt from file: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/prompts/tools/web_search/web_search_prompt.yaml
2025-06-05 17:10:35,411 - wildfire_kg.prompts - DEBUG - Successfully loaded prompt: tools.web_search.web_search_prompt from /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/prompts/tools/web_search/web_search_prompt.yaml
2025-06-05 17:10:35,411 - wildfire_kg.prompts - DEBUG - Loading prompt from file: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/prompts/tools/kg/sparql_generation_prompt.yaml
2025-06-05 17:10:35,413 - wildfire_kg.prompts - DEBUG - Successfully loaded prompt: tools.kg.sparql_generation_prompt from /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/prompts/tools/kg/sparql_generation_prompt.yaml
2025-06-05 17:10:35,413 - wildfire_kg.prompts - DEBUG - Loading prompt from file: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/prompts/tools/kg/qa_prompt.yaml
2025-06-05 17:10:35,414 - wildfire_kg.prompts - DEBUG - Successfully loaded prompt: tools.kg.qa_prompt from /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/prompts/tools/kg/qa_prompt.yaml
2025-06-05 17:10:35,415 - wildfire_kg.prompts - DEBUG - Loading prompt from file: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/prompts/tools/kg/sparql_fix_prompt.yaml
2025-06-05 17:10:35,416 - wildfire_kg.prompts - DEBUG - Successfully loaded prompt: tools.kg.sparql_fix_prompt from /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/prompts/tools/kg/sparql_fix_prompt.yaml
2025-06-05 17:10:35,416 - wildfire_kg.prompts - DEBUG - Loading prompt from file: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/prompts/agents/agent_prompt.yaml
2025-06-05 17:10:35,418 - wildfire_kg.prompts - DEBUG - Successfully loaded prompt: agents.agent_prompt from /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/prompts/agents/agent_prompt.yaml
2025-06-05 17:10:35,418 - wildfire_kg.prompts - INFO - Successfully loaded 5 prompts: ['tools.web_search.web_search_prompt', 'tools.kg.sparql_generation_prompt', 'tools.kg.qa_prompt', 'tools.kg.sparql_fix_prompt', 'agents.agent_prompt']
2025-06-05 17:10:35,419 - wildfire_kg.agent - DEBUG - Successfully loaded agent prompt template

View the evaluation results for experiment: 'AGT:llama3-sdsc-0_1_KG:llama3-sdsc-0_1-20250605_171033-82c3b029' at:
https://smith.langchain.com/o/13e553a1-7013-4b52-9cd0-2628eb4078c1/datasets/3b358a29-f77b-480b-9927-63c73d41186b/compare?selectedSessions=67aaa51a-3212-4811-8165-6b97c528c9b1

0it [00:00, ?it/s]

2025-06-05 17:10:45,408 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: current wind in Bakersfield
2025-06-05 17:10:45,408 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:10:45,409 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'today/current': 2025-06-06
2025-06-05 17:10:45,409 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-06 for query: current wind in Bakersfield
2025-06-05 17:10:45,410 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-06
2025-06-05 17:10:45,410 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 0
2025-06-05 17:10:45,410 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:10:45,411 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-06 00:00:00+00:00
2025-06-05 17:10:45,411 - wildfire_kg.tools.weather - INFO - - Location: Bakersfield
2025-06-05 17:10:45,411 - wildfire_kg.tools.weather - INFO - - Type: Current
2025-06-05 17:10:45,678 - wildfire_kg.tools.weather - INFO - Making current weather API call...
2025-06-05 17:10:45,678 - wildfire_kg.tools.weather - INFO - Calling current endpoint: https://pro.openweathermap.org/data/2.5/weather with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 35.3738712, 'lon': -119.0194639}
2025-06-05 17:10:45,702 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: importance of defensible space around homes in wildfire-prone areas and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:ed410ff2-7074-746b-1634-4c8a5f49de47', 'checkpoint_ns': 'tools:ed410ff2-7074-746b-1634-4c8a5f49de47'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x16b110a10>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'ed410ff2-7074-746b-1634-4c8a5f49de47', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169f208b0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x169eaba80>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x169eaadc0>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x169eaba40>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x169eab8c0>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x1699bfbd0>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x162aa1890>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426ab-14c3-638a-8001-68c620cafdbe'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:ed410ff2-7074-746b-1634-4c8a5f49de47', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b103c70>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b102980>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x169e76d40>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b102c50>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x1614ab9c0; to 'PregelExecutableTask' at 0x1614baf80>, stream=False, retry=None, futures=<weakref at 0x1614ab970; to 'FuturesDict' at 0x169e85550>, schedule_task=<weakref at 0x169e61930; to 'AsyncPregelLoop' at 0x169eaa490>, submit=<weakref at 0x169e617e0; to 'AsyncBackgroundExecutor' at 0x169eaa810>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:10:45,702 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:10:45,703 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/weather
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 35.3738712,
  "lon": -119.0194639
}
Status Code: 200
Response: {
  "coord": {
    "lon": -119.0195,
    "lat": 35.3739
  },
  "weather": [
    {
      "id": 800,
      "main": "Clear",
      "description": "clear sky",
      "icon": "01d"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 34.68,
    "feels_like": 33.34,
    "temp_min": 34.15,
    "temp_max": 36.2,
    "pressure": 1009,
    "humidity": 25,
    "sea_level": 1009,
    "grnd_level": 991
  },
  "visibility": 10000,
  "wind": {
    "speed": 2.68,
    "deg": 284,
    "gust": 4.47
  },
  "clouds": {
    "all": 0
  },
  "dt": 1749168645,
  "sys": {
    "type": 2,
    "id": 2019205,
    "country": "US",
    "sunrise": 1749127284,
    "sunset": 1749179292
  },
  "timezone": -25200,
  "id": 5325738,
  "name": "Bakersfield",
  "cod": 200
}
==================================================

2025-06-05 17:10:45,861 - wildfire_kg.tools.weather - INFO - API response for Bakersfield: {"coord": {"lon": -119.0195, "lat": 35.3739}, "weather": [{"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}], "base": "stations", "main": {"temp": 34.68, "feels_like": 33.34, "te...
2025-06-05 17:10:46,088 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:10:46,089 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:10:46,089 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:10:46,123 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:10:46,123 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:10:46,841 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: How many trees and shrubs are present in CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:26a4c5df-4b67-ad5d-0ffe-3db6634a3e1e', 'checkpoint_ns': 'tools:26a4c5df-4b67-ad5d-0ffe-3db6634a3e1e'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x169eaea10>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '26a4c5df-4b67-ad5d-0ffe-3db6634a3e1e', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x162ae2b60>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x162f46d40>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x162f1a1c0>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x162f45fc0>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x162f3c140>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x162f105d0>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x162a5cf10>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426ab-1f9f-6db2-8001-a936dab834b3'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:26a4c5df-4b67-ad5d-0ffe-3db6634a3e1e', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x169e7ff70>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x169ec8ac0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x169f4ade0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x169ec8400>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x1629f3420; to 'PregelExecutableTask' at 0x16b7b91b0>, stream=False, retry=None, futures=<weakref at 0x161693380; to 'FuturesDict' at 0x1629e3110>, schedule_task=<weakref at 0x169e612a0; to 'AsyncPregelLoop' at 0x1629d3f50>, submit=<weakref at 0x169e61230; to 'AsyncBackgroundExecutor' at 0x169944510>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:10:46,842 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:10:46,842 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:10:47,057 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:10:47,058 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:10:47,058 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:10:47,099 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:10:47,100 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:10:58,418 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: current wind in Bakersfield
2025-06-05 17:10:58,419 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:10:58,420 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'today/current': 2025-06-06
2025-06-05 17:10:58,420 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-06 for query: current wind in Bakersfield
2025-06-05 17:10:58,420 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-06
2025-06-05 17:10:58,421 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 0
2025-06-05 17:10:58,421 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:10:58,422 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-06 00:00:00+00:00
2025-06-05 17:10:58,423 - wildfire_kg.tools.weather - INFO - - Location: Bakersfield
2025-06-05 17:10:58,424 - wildfire_kg.tools.weather - INFO - - Type: Current
2025-06-05 17:10:58,509 - wildfire_kg.tools.weather - INFO - Making current weather API call...
2025-06-05 17:10:58,509 - wildfire_kg.tools.weather - INFO - Calling current endpoint: https://pro.openweathermap.org/data/2.5/weather with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 35.3738712, 'lon': -119.0194639}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/weather
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 35.3738712,
  "lon": -119.0194639
}
Status Code: 200
Response: {
  "coord": {
    "lon": -119.0195,
    "lat": 35.3739
  },
  "weather": [
    {
      "id": 800,
      "main": "Clear",
      "description": "clear sky",
      "icon": "01d"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 34.68,
    "feels_like": 33.34,
    "temp_min": 34.15,
    "temp_max": 36.2,
    "pressure": 1009,
    "humidity": 25,
    "sea_level": 1009,
    "grnd_level": 991
  },
  "visibility": 10000,
  "wind": {
    "speed": 2.68,
    "deg": 284,
    "gust": 4.47
  },
  "clouds": {
    "all": 0
  },
  "dt": 1749168645,
  "sys": {
    "type": 2,
    "id": 2019205,
    "country": "US",
    "sunrise": 1749127284,
    "sunset": 1749179292
  },
  "timezone": -25200,
  "id": 5325738,
  "name": "Bakersfield",
  "cod": 200
}
==================================================

2025-06-05 17:10:58,639 - wildfire_kg.tools.weather - INFO - API response for Bakersfield: {"coord": {"lon": -119.0195, "lat": 35.3739}, "weather": [{"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}], "base": "stations", "main": {"temp": 34.68, "feels_like": 33.34, "te...
2025-06-05 17:11:11,189 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the leaf area index (LAI) for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:26a938fd-e445-401b-6fe2-c528946c3960', 'checkpoint_ns': 'tools:26a938fd-e445-401b-6fe2-c528946c3960'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x16b8d5710>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '26a938fd-e445-401b-6fe2-c528946c3960', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169e8fa60>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x16b8c9f00>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16b8ca140>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16b8ca400>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16b8ca3c0>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x16b8b32d0>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x16b8b1190>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426ac-07d4-609c-8001-febb8e22fddd'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:26a938fd-e445-401b-6fe2-c528946c3960', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b8c6e60>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b8c6e00>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x169f44540>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b8c6bf0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x1618307c0; to 'PregelExecutableTask' at 0x16b7b9d80>, stream=False, retry=None, futures=<weakref at 0x161833650; to 'FuturesDict' at 0x16b872570>, schedule_task=<weakref at 0x16b7d3920; to 'AsyncPregelLoop' at 0x16b8c3710>, submit=<weakref at 0x169e63ed0; to 'AsyncBackgroundExecutor' at 0x16b8abe50>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:11:11,190 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:11:11,190 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:11:11,439 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:11:11,440 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:11:11,440 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:11:11,484 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:11:11,484 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:11:14,752 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the overstory shrub volume (OSvol) for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:70ea79cc-8ddb-db0f-b8da-6773c6033304', 'checkpoint_ns': 'tools:70ea79cc-8ddb-db0f-b8da-6773c6033304'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x16be36310>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '70ea79cc-8ddb-db0f-b8da-6773c6033304', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16be05120>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x16be014c0>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16be01740>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16be00680>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16be027c0>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x16b81b550>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x1699be7d0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426ac-29cc-61b8-8001-b18bfe5aee61'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:70ea79cc-8ddb-db0f-b8da-6773c6033304', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16be08310>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16be082b0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x16b8f8d60>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16be08460>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x161832570; to 'PregelExecutableTask' at 0x16b7b9b40>, stream=False, retry=None, futures=<weakref at 0x161832480; to 'FuturesDict' at 0x169e85310>, schedule_task=<weakref at 0x16b7d3990; to 'AsyncPregelLoop' at 0x16b8d4e50>, submit=<weakref at 0x16b7d38b0; to 'AsyncBackgroundExecutor' at 0x16b807010>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:11:14,753 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:11:14,753 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:11:14,976 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:11:14,977 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:11:14,978 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:11:15,021 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:11:15,021 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?plotName ?treesN ?shrubsN
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:TreesN ?treesN .
  ?treeShrubMetrics wifire:ShrubsN ?shrubsN .
  BIND("CASBC_0007_20241117_1" AS ?plotName) .
}
LIMIT 50

2025-06-05 17:11:35,888 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:11:35,889 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:11:35,890 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?lai
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegMetrics .
  ?vegMetrics wifire:LAI ?lai .
}
LIMIT 50

2025-06-05 17:11:40,184 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:11:40,184 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:11:40,184 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?osvol
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegMetrics .
  ?vegMetrics wifire:OSvol ?osvol .
}
LIMIT 50

2025-06-05 17:11:42,712 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:11:42,713 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:11:42,713 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:11:57,129 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the components of the fire triangle? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:63098dee-e2de-a4ad-f7ba-108cf159ee2b', 'checkpoint_ns': 'tools:63098dee-e2de-a4ad-f7ba-108cf159ee2b'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x16be604d0>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '63098dee-e2de-a4ad-f7ba-108cf159ee2b', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169e8c040>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x16b8f5980>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16b84fd00>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16b84ee80>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16b84c740>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x16b809f50>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x16b840910>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426ad-bdf3-664c-8001-b7cdb43f3964'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:63098dee-e2de-a4ad-f7ba-108cf159ee2b', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16bee58a0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16bee45b0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x169f4b9c0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16bee4c10>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x162ab4ae0; to 'PregelExecutableTask' at 0x16b7bb1c0>, stream=False, retry=None, futures=<weakref at 0x162ab7fb0; to 'FuturesDict' at 0x169e84950>, schedule_task=<weakref at 0x16be38cf0; to 'AsyncPregelLoop' at 0x16b814390>, submit=<weakref at 0x16be386d0; to 'AsyncBackgroundExecutor' at 0x16b65b910>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:11:57,130 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:11:57,130 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:11:57,335 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:11:57,335 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:11:57,335 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:11:57,372 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:11:57,373 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:12:13,469 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the mean diameter at breast height and mean leaf area index for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:6dcb980d-53ab-3503-ccaf-d137b94564a1', 'checkpoint_ns': 'tools:6dcb980d-53ab-3503-ccaf-d137b94564a1'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x16bef34d0>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '6dcb980d-53ab-3503-ccaf-d137b94564a1', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169e8d4e0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x16cd4ce80>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16cd4cf40>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16cd4d080>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16cd4d0c0>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x16b1287d0>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x16b8b2450>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426ae-59c5-6980-8001-dd503bfdcd00'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:6dcb980d-53ab-3503-ccaf-d137b94564a1', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b7de290>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16be812d0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x162cc6660>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16be83970>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x161ca1e40; to 'PregelExecutableTask' at 0x162b35630>, stream=False, retry=None, futures=<weakref at 0x161ca3830; to 'FuturesDict' at 0x16be55970>, schedule_task=<weakref at 0x16be39cb0; to 'AsyncPregelLoop' at 0x16cd4c650>, submit=<weakref at 0x16be3ab90; to 'AsyncBackgroundExecutor' at 0x16cd4c990>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:12:13,470 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:12:13,470 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:12:13,673 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:12:13,673 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:12:13,673 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:12:13,709 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:12:13,709 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?plot ?plotName ?plotCounty ?plotState ?shrubArea ?treeArea ?basalArea
WHERE {
  ?plot a wifire:PlotMetrics .
  ?plot wifire:hasLocationDataPlot ?locationData .
  ?locationData wifire:plotCounty ?plotCounty .
  ?locationData wifire:plotState ?plotState .
  ?plot wifire:plotName ?plotName .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:shrubArea ?shrubArea .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:basalArea ?basalArea .
  FILTER(CONTAINS(LCASE(?plotCounty), LCASE("santa barbara")) || CONTAINS(LCASE(?plotState), LCASE("california")))
}
LIMIT 50
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?component ?label
WHERE {
  {
    SELECT ?component ?label
    WHERE {
      ?component rdfs:label ?label .
      FILTER (?label = "Fuel" || ?label = "Oxygen" || ?label = "Heat") .
    }
  }
}
LIMIT 50

2025-06-05 17:12:35,460 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:12:35,461 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:12:35,461 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?mdbh ?mlai
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:MDBH ?mdbh .
  ?treeShrubMetrics wifire:MLAI ?mlai .
}
LIMIT 50

2025-06-05 17:12:51,329 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the slope percentage of CASBC_0011_20240913_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:41dc66ee-3466-d95c-6701-397ba72bd9eb', 'checkpoint_ns': 'tools:41dc66ee-3466-d95c-6701-397ba72bd9eb'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x16b888810>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '41dc66ee-3466-d95c-6701-397ba72bd9eb', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b8f2b60>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x16b4f7040>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16b86cb00>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16b86d1c0>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16b86d000>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x16b86c550>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x16be0d110>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426af-c2d4-6268-8001-9ed385969e66'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:41dc66ee-3466-d95c-6701-397ba72bd9eb', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b869ea0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b8684c0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x16b8fa3e0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b8691e0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x162ab6e30; to 'PregelExecutableTask' at 0x16b7b9900>, stream=False, retry=None, futures=<weakref at 0x162ab60c0; to 'FuturesDict' at 0x16b8703b0>, schedule_task=<weakref at 0x16be38e40; to 'AsyncPregelLoop' at 0x16b86d150>, submit=<weakref at 0x16be38270; to 'AsyncBackgroundExecutor' at 0x16bed2410>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:12:51,329 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:12:51,330 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:12:51,564 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:12:51,565 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:12:51,565 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:12:51,604 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:12:51,604 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...
2025-06-05 17:12:51,803 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the mean shrub area and scaled shrub area for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:b59f2fca-b880-837e-5987-fd65780da4b7', 'checkpoint_ns': 'tools:b59f2fca-b880-837e-5987-fd65780da4b7'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x16beee650>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'b59f2fca-b880-837e-5987-fd65780da4b7', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b10c5e0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x16b87d2c0>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16bea2a80>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16bea2680>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16bea1a80>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x16b87e090>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x1699fa7d0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426af-c75a-680a-8001-64e6ba0f7e1d'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:b59f2fca-b880-837e-5987-fd65780da4b7', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16beacdf0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16bead4b0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x16cd32de0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16bead7b0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x161679cb0; to 'PregelExecutableTask' at 0x16b7b9b40>, stream=False, retry=None, futures=<weakref at 0x16b7f9580; to 'FuturesDict' at 0x16b873ad0>, schedule_task=<weakref at 0x16be699a0; to 'AsyncPregelLoop' at 0x16b819790>, submit=<weakref at 0x16be69770; to 'AsyncBackgroundExecutor' at 0x16b81add0>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:12:51,803 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:12:51,803 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:12:52,055 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:12:52,055 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:12:52,056 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:12:52,097 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:12:52,098 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:12:56,766 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:12:56,767 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:12:56,768 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?slopePercentage
WHERE {
  ?plot wifire:plotName "CASBC_0011_20240913_1" .
  ?plot wifire:hasFireBehaviorMetrics ?fireBehaviorMetrics .
  ?fireBehaviorMetrics wifire:LF_SLPD ?slopePercentage .
}
LIMIT 50

2025-06-05 17:13:27,908 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:13:27,909 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:13:27,910 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?meanShrubArea ?scaledShrubArea
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:MeanSA ?meanShrubArea .
  ?treeShrubMetrics wifire:scaledShrubArea ?scaledShrubArea .
}
LIMIT 50

2025-06-05 17:13:37,844 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:13:37,845 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:13:37,846 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:13:39,634 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: current weather in Palm Springs
2025-06-05 17:13:39,635 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:13:39,635 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'today/current': 2025-06-06
2025-06-05 17:13:39,635 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-06 for query: current weather in Palm Springs
2025-06-05 17:13:39,636 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-06
2025-06-05 17:13:39,636 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 0
2025-06-05 17:13:39,636 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:13:39,636 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-06 00:00:00+00:00
2025-06-05 17:13:39,637 - wildfire_kg.tools.weather - INFO - - Location: Palm Springs
2025-06-05 17:13:39,637 - wildfire_kg.tools.weather - INFO - - Type: Current
2025-06-05 17:13:39,857 - wildfire_kg.tools.weather - INFO - Making current weather API call...
2025-06-05 17:13:39,858 - wildfire_kg.tools.weather - INFO - Calling current endpoint: https://pro.openweathermap.org/data/2.5/weather with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 33.8246269, 'lon': -116.540303}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/weather
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 33.8246269,
  "lon": -116.540303
}
Status Code: 200
Response: {
  "coord": {
    "lon": -116.5403,
    "lat": 33.8246
  },
  "weather": [
    {
      "id": 800,
      "main": "Clear",
      "description": "clear sky",
      "icon": "01d"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 36.65,
    "feels_like": 35.72,
    "temp_min": 31.2,
    "temp_max": 37,
    "pressure": 1009,
    "humidity": 24,
    "sea_level": 1009,
    "grnd_level": 921
  },
  "visibility": 10000,
  "wind": {
    "speed": 5.66,
    "deg": 310,
    "gust": 11.83
  },
  "clouds": {
    "all": 0
  },
  "dt": 1749168820,
  "sys": {
    "type": 1,
    "id": 5412,
    "country": "US",
    "sunrise": 1749126935,
    "sunset": 1749178451
  },
  "timezone": -25200,
  "id": 5380668,
  "name": "Palm Springs",
  "cod": 200
}
==================================================

2025-06-05 17:13:40,015 - wildfire_kg.tools.weather - INFO - API response for Palm Springs: {"coord": {"lon": -116.5403, "lat": 33.8246}, "weather": [{"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}], "base": "stations", "main": {"temp": 36.65, "feels_like": 35.72, "te...
2025-06-05 17:13:56,789 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: current weather in Palm Springs
2025-06-05 17:13:56,790 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:13:56,790 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'today/current': 2025-06-06
2025-06-05 17:13:56,791 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-06 for query: current weather in Palm Springs
2025-06-05 17:13:56,791 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-06
2025-06-05 17:13:56,791 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 0
2025-06-05 17:13:56,791 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:13:56,792 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-06 00:00:00+00:00
2025-06-05 17:13:56,792 - wildfire_kg.tools.weather - INFO - - Location: Palm Springs
2025-06-05 17:13:56,793 - wildfire_kg.tools.weather - INFO - - Type: Current
2025-06-05 17:13:56,876 - wildfire_kg.tools.weather - INFO - Making current weather API call...
2025-06-05 17:13:56,876 - wildfire_kg.tools.weather - INFO - Calling current endpoint: https://pro.openweathermap.org/data/2.5/weather with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 33.8246269, 'lon': -116.540303}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/weather
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 33.8246269,
  "lon": -116.540303
}
Status Code: 200
Response: {
  "coord": {
    "lon": -116.5403,
    "lat": 33.8246
  },
  "weather": [
    {
      "id": 800,
      "main": "Clear",
      "description": "clear sky",
      "icon": "01d"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 36.65,
    "feels_like": 35.72,
    "temp_min": 31.2,
    "temp_max": 37,
    "pressure": 1009,
    "humidity": 24,
    "sea_level": 1009,
    "grnd_level": 921
  },
  "visibility": 10000,
  "wind": {
    "speed": 5.66,
    "deg": 310,
    "gust": 11.83
  },
  "clouds": {
    "all": 0
  },
  "dt": 1749168820,
  "sys": {
    "type": 1,
    "id": 5412,
    "country": "US",
    "sunrise": 1749126935,
    "sunset": 1749178451
  },
  "timezone": -25200,
  "id": 5380668,
  "name": "Palm Springs",
  "cod": 200
}
==================================================

2025-06-05 17:13:56,995 - wildfire_kg.tools.weather - INFO - API response for Palm Springs: {"coord": {"lon": -116.5403, "lat": 33.8246}, "weather": [{"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}], "base": "stations", "main": {"temp": 36.65, "feels_like": 35.72, "te...
2025-06-05 17:14:01,712 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:14:01,713 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:14:01,713 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:14:12,052 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the green cover volume for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:efb36c08-5895-db22-5407-49ba47b0b05e', 'checkpoint_ns': 'tools:efb36c08-5895-db22-5407-49ba47b0b05e'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10842e050>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'efb36c08-5895-db22-5407-49ba47b0b05e', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b8f1a80>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x16b843a40>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16cdb3880>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16cdb38c0>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16cdb35c0>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x162ac4790>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x16cdb3c10>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426b2-c4a8-6e88-8001-6b8788b7e7c7'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:efb36c08-5895-db22-5407-49ba47b0b05e', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b8c5420>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b8c4cd0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10840b9c0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b8c4d30>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x162cd67a0; to 'PregelExecutableTask' at 0x16be9b490>, stream=False, retry=None, futures=<weakref at 0x162cd4c20; to 'FuturesDict' at 0x16b884710>, schedule_task=<weakref at 0x16be6b610; to 'AsyncPregelLoop' at 0x16cdb0890>, submit=<weakref at 0x16be39b60; to 'AsyncBackgroundExecutor' at 0x16cdcbb50>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:14:12,053 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:14:12,053 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:14:12,267 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:14:12,267 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:14:12,267 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:14:12,304 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:14:12,305 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:14:19,832 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the shrub height and its standard deviation for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:4b009d44-fe36-120e-78df-bc9609496dfa', 'checkpoint_ns': 'tools:4b009d44-fe36-120e-78df-bc9609496dfa'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x1084dab50>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '4b009d44-fe36-120e-78df-bc9609496dfa', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b8f0130>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x16cdcaec0>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1084d8d40>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1084d89c0>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1084d8d80>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x16cdc0050>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x169f0c810>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426b3-0edd-6b02-8001-2cbd28d28b50'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:4b009d44-fe36-120e-78df-bc9609496dfa', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1084bffd0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1084bfeb0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1084ae840>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1084bdc60>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x16172f650; to 'PregelExecutableTask' at 0x16be99b40>, stream=False, retry=None, futures=<weakref at 0x16172d4e0; to 'FuturesDict' at 0x16b885970>, schedule_task=<weakref at 0x16be6a650; to 'AsyncPregelLoop' at 0x1084d3c50>, submit=<weakref at 0x16be3a880; to 'AsyncBackgroundExecutor' at 0x1084b3910>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:14:19,833 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:14:19,833 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:14:20,040 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:14:20,040 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:14:20,041 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:14:20,059 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the disturbance status for CASBC_0011_20240913_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:da0b52e8-3be9-3e14-23b9-51185b80a792', 'checkpoint_ns': 'tools:da0b52e8-3be9-3e14-23b9-51185b80a792'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x16b6b2390>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'da0b52e8-3be9-3e14-23b9-51185b80a792', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b1ff880>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x16cd6fe80>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16be70780>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16be71100>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16be701c0>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x16b85ea90>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x16b804810>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426b3-1108-6e22-8001-efdbe0ae0c39'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:da0b52e8-3be9-3e14-23b9-51185b80a792', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10844e170>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10844cd90>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1084adee0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10844e8c0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x162ab7d30; to 'PregelExecutableTask' at 0x16be99bd0>, stream=False, retry=None, futures=<weakref at 0x162ab7830; to 'FuturesDict' at 0x16cdfe8d0>, schedule_task=<weakref at 0x16be6b220; to 'AsyncPregelLoop' at 0x16b841290>, submit=<weakref at 0x16be6aff0; to 'AsyncBackgroundExecutor' at 0x16b85d810>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:14:20,059 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:14:20,060 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:14:20,092 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:14:20,092 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...
2025-06-05 17:14:20,274 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:14:20,274 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:14:20,275 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:14:20,312 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:14:20,313 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?greenCoverVolume
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:GCvol ?greenCoverVolume .
}
LIMIT 50

2025-06-05 17:14:51,087 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:14:51,088 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:14:51,088 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?disturbanceStatus
WHERE {
  ?plot wifire:plotName "CASBC_0011_20240913_1" .
  ?plot wifire:hasFireBehaviorMetrics ?fireBehaviorMetrics .
  ?fireBehaviorMetrics wifire:LF_EVC ?disturbanceStatus .
}
LIMIT 50

2025-06-05 17:15:17,564 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:15:17,565 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:15:17,566 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:15:29,161 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the aspect value of CASBC_0011_20240913_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:7772f21c-7042-79c5-f9f2-441a595d6c0e', 'checkpoint_ns': 'tools:7772f21c-7042-79c5-f9f2-441a595d6c0e'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10869a250>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '7772f21c-7042-79c5-f9f2-441a595d6c0e', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169f20310>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x108443640>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1084434c0>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1084a2800>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1084a2340>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x16b808790>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x16cd52450>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426b5-a407-6a14-8001-7b1967255639'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:7772f21c-7042-79c5-f9f2-441a595d6c0e', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1084be230>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1084beda0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x16cddb560>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1084be320>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x162ab7830; to 'PregelExecutableTask' at 0x16b7b9b40>, stream=False, retry=None, futures=<weakref at 0x162ab7f10; to 'FuturesDict' at 0x16b845550>, schedule_task=<weakref at 0x16be6a180; to 'AsyncPregelLoop' at 0x162b00d90>, submit=<weakref at 0x16be6aa40; to 'AsyncBackgroundExecutor' at 0x16cd52410>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:15:29,161 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:15:29,162 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:15:29,376 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:15:29,376 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:15:29,377 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:15:29,413 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:15:29,414 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?shrubHeight ?stdDevShrubHeight
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:SDHT ?shrubHeight .
  ?treeShrubMetrics wifire:SDSHT ?stdDevShrubHeight .
}
LIMIT 50

2025-06-05 17:15:55,570 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:15:55,571 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:15:55,571 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:15:55,834 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: How many trees are in CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:079cf9dd-fe42-b848-adfb-7386df001e5d', 'checkpoint_ns': 'tools:079cf9dd-fe42-b848-adfb-7386df001e5d'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10863d0d0>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '079cf9dd-fe42-b848-adfb-7386df001e5d', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x162ae25c0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x16be1bfc0>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16be18500>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1084d0d00>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1084d1980>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x16b79d290>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x1084d9d10>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426b6-a268-663a-8001-151cc648aa84'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:079cf9dd-fe42-b848-adfb-7386df001e5d', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1086454b0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1086452a0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10862fba0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x108645510>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x162a72930; to 'PregelExecutableTask' at 0x16be9ab00>, stream=False, retry=None, futures=<weakref at 0x161834cc0; to 'FuturesDict' at 0x10860b770>, schedule_task=<weakref at 0x16be685f0; to 'AsyncPregelLoop' at 0x10861ae10>, submit=<weakref at 0x16be6b680; to 'AsyncBackgroundExecutor' at 0x108672410>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:15:55,834 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:15:55,834 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:15:56,035 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:15:56,036 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:15:56,036 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:15:56,070 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:15:56,070 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?aspect
WHERE {
  ?plot wifire:plotName "CASBC_0011_20240913_1" .
  ?plot wifire:hasFireBehaviorMetrics ?fireBehaviorMetrics .
  ?fireBehaviorMetrics wifire:LF_ASP ?aspect .
}
LIMIT 50

2025-06-05 17:16:07,415 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:16:07,415 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:16:07,416 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:16:11,962 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the shrub height and its standard deviation for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 4, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:7ff385a2-2e7e-f4c4-6fb1-b33faa771270', 'checkpoint_ns': 'tools:7ff385a2-2e7e-f4c4-6fb1-b33faa771270'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x1086c4b50>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '7ff385a2-2e7e-f4c4-6fb1-b33faa771270', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169f23e20>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x16cdcaec0>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1084d8d40>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1084d89c0>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1084d8d80>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x16cdc0050>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x169f0c810>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426b7-3c37-69a0-8003-31974585ab92'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:7ff385a2-2e7e-f4c4-6fb1-b33faa771270', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b101f00>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10868f4c0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1084ae840>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1086c2650>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x161ca39c0; to 'PregelExecutableTask' at 0x16be99510>, stream=False, retry=None, futures=<weakref at 0x161608400; to 'FuturesDict' at 0x16cdfec30>, schedule_task=<weakref at 0x16be6a650; to 'AsyncPregelLoop' at 0x1084d3c50>, submit=<weakref at 0x16be3a880; to 'AsyncBackgroundExecutor' at 0x1084b3910>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:16:11,963 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:16:11,963 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:16:12,190 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:16:12,191 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:16:12,191 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:16:12,234 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:16:12,235 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?shrubHeight ?stdDevShrubHeight
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:SDHT ?shrubHeight .
  ?treeShrubMetrics wifire:SDSHT ?stdDevShrubHeight .
}
LIMIT 50

2025-06-05 17:16:12,605 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:16:12,606 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:16:12,606 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?treeCount
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:TreesN ?treeCount .
}
LIMIT 50

2025-06-05 17:16:28,950 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:16:28,950 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:16:28,951 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:16:41,361 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: current weather in Escondido, CA
2025-06-05 17:16:41,361 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:16:41,362 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'today/current': 2025-06-06
2025-06-05 17:16:41,362 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-06 for query: current weather in Escondido, CA
2025-06-05 17:16:41,363 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-06
2025-06-05 17:16:41,363 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 0
2025-06-05 17:16:41,363 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:16:41,364 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-06 00:00:00+00:00
2025-06-05 17:16:41,365 - wildfire_kg.tools.weather - INFO - - Location: Escondido, CA
2025-06-05 17:16:41,366 - wildfire_kg.tools.weather - INFO - - Type: Current
2025-06-05 17:16:41,848 - wildfire_kg.tools.weather - INFO - Making current weather API call...
2025-06-05 17:16:41,849 - wildfire_kg.tools.weather - INFO - Calling current endpoint: https://pro.openweathermap.org/data/2.5/weather with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 33.1216751, 'lon': -117.0814849}
2025-06-05 17:16:41,969 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What type of tree shrub metrics are available for the plots? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:d0a97a1e-ac11-01b4-dbdd-508f83e0b414', 'checkpoint_ns': 'tools:d0a97a1e-ac11-01b4-dbdd-508f83e0b414'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x108fabd50>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'd0a97a1e-ac11-01b4-dbdd-508f83e0b414', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169e8d8a0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x108fa0b00>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108fa3f40>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108fa3580>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108fa3840>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10842a950>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x108f48b50>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426b8-5a63-6626-8001-e16911789a8f'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:d0a97a1e-ac11-01b4-dbdd-508f83e0b414', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x169ec8e20>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16bee7c40>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1086928e0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b103df0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x161497920; to 'PregelExecutableTask' at 0x1614badd0>, stream=False, retry=None, futures=<weakref at 0x16161ddf0; to 'FuturesDict' at 0x1084b6330>, schedule_task=<weakref at 0x108f30c80; to 'AsyncPregelLoop' at 0x108f72610>, submit=<weakref at 0x108f30ba0; to 'AsyncBackgroundExecutor' at 0x108f72190>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:16:41,969 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:16:41,970 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/weather
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 33.1216751,
  "lon": -117.0814849
}
Status Code: 200
Response: {
  "coord": {
    "lon": -117.0815,
    "lat": 33.1217
  },
  "weather": [
    {
      "id": 804,
      "main": "Clouds",
      "description": "overcast clouds",
      "icon": "04d"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 18.64,
    "feels_like": 18.6,
    "temp_min": 16.74,
    "temp_max": 20.1,
    "pressure": 1012,
    "humidity": 78,
    "sea_level": 1012,
    "grnd_level": 983
  },
  "visibility": 10000,
  "wind": {
    "speed": 2.68,
    "deg": 260
  },
  "clouds": {
    "all": 100
  },
  "dt": 1749169002,
  "sys": {
    "type": 2,
    "id": 2005618,
    "country": "US",
    "sunrise": 1749127172,
    "sunset": 1749178473
  },
  "timezone": -25200,
  "id": 5346827,
  "name": "Escondido",
  "cod": 200
}
==================================================

2025-06-05 17:16:42,004 - wildfire_kg.tools.weather - INFO - API response for Escondido: {"coord": {"lon": -117.0815, "lat": 33.1217}, "weather": [{"id": 804, "main": "Clouds", "description": "overcast clouds", "icon": "04d"}], "base": "stations", "main": {"temp": 18.64, "feels_like": 18....
2025-06-05 17:16:42,211 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:16:42,212 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:16:42,212 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:16:42,247 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:16:42,248 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:16:55,277 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: current weather in Escondido, CA
2025-06-05 17:16:55,277 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:16:55,278 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'today/current': 2025-06-06
2025-06-05 17:16:55,278 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-06 for query: current weather in Escondido, CA
2025-06-05 17:16:55,279 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-06
2025-06-05 17:16:55,279 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 0
2025-06-05 17:16:55,279 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:16:55,280 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-06 00:00:00+00:00
2025-06-05 17:16:55,281 - wildfire_kg.tools.weather - INFO - - Location: Escondido, CA
2025-06-05 17:16:55,282 - wildfire_kg.tools.weather - INFO - - Type: Current
2025-06-05 17:16:55,449 - wildfire_kg.tools.weather - INFO - Making current weather API call...
2025-06-05 17:16:55,450 - wildfire_kg.tools.weather - INFO - Calling current endpoint: https://pro.openweathermap.org/data/2.5/weather with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 33.1216751, 'lon': -117.0814849}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/weather
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 33.1216751,
  "lon": -117.0814849
}
Status Code: 200
Response: {
  "coord": {
    "lon": -117.0815,
    "lat": 33.1217
  },
  "weather": [
    {
      "id": 804,
      "main": "Clouds",
      "description": "overcast clouds",
      "icon": "04d"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 18.64,
    "feels_like": 18.6,
    "temp_min": 16.74,
    "temp_max": 20.1,
    "pressure": 1012,
    "humidity": 78,
    "sea_level": 1012,
    "grnd_level": 983
  },
  "visibility": 10000,
  "wind": {
    "speed": 2.68,
    "deg": 260
  },
  "clouds": {
    "all": 100
  },
  "dt": 1749169002,
  "sys": {
    "type": 2,
    "id": 2005618,
    "country": "US",
    "sunrise": 1749127172,
    "sunset": 1749178473
  },
  "timezone": -25200,
  "id": 5346827,
  "name": "Escondido",
  "cod": 200
}
==================================================

2025-06-05 17:16:55,583 - wildfire_kg.tools.weather - INFO - API response for Escondido: {"coord": {"lon": -117.0815, "lat": 33.1217}, "weather": [{"id": 804, "main": "Clouds", "description": "overcast clouds", "icon": "04d"}], "base": "stations", "main": {"temp": 18.64, "feels_like": 18....
2025-06-05 17:16:57,176 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the canopy base height and canopy bulk density for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:2d64aeb1-54ea-39e2-ea02-3e27de51c357', 'checkpoint_ns': 'tools:2d64aeb1-54ea-39e2-ea02-3e27de51c357'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x1086ad0d0>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '2d64aeb1-54ea-39e2-ea02-3e27de51c357', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169e8d6c0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x108441000>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108fa0680>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108fa0840>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108fa3880>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x1086e2a50>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x108fa0250>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426b8-eb69-630a-8001-f8227a123017'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:2d64aeb1-54ea-39e2-ea02-3e27de51c357', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10960b040>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109609090>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x169e76340>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10960af80>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x108f42520; to 'PregelExecutableTask' at 0x16be9b9a0>, stream=False, retry=None, futures=<weakref at 0x108f43f60; to 'FuturesDict' at 0x108f6e270>, schedule_task=<weakref at 0x108f31000; to 'AsyncPregelLoop' at 0x108fa2390>, submit=<weakref at 0x108f30f90; to 'AsyncBackgroundExecutor' at 0x16cdc2410>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:16:57,177 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:16:57,177 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:16:57,407 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:16:57,407 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:16:57,408 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:16:57,448 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:16:57,449 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:17:05,795 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the understory shrub volume (USvol) for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:771980fe-489c-eb6a-578e-fb572e47c76c', 'checkpoint_ns': 'tools:771980fe-489c-eb6a-578e-fb572e47c76c'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x109652190>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '771980fe-489c-eb6a-578e-fb572e47c76c', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169f22f20>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x108441a80>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108f48500>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108f48a40>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1086a8800>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10861f350>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10845ff50>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426b9-3d9c-67e4-8001-dc675531213c'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:771980fe-489c-eb6a-578e-fb572e47c76c', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109637d30>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109637a00>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10963d8a0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109637e80>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x108f414e0; to 'PregelExecutableTask' at 0x16be983a0>, stream=False, retry=None, futures=<weakref at 0x108f41670; to 'FuturesDict' at 0x16b847230>, schedule_task=<weakref at 0x16be694d0; to 'AsyncPregelLoop' at 0x108f5e7d0>, submit=<weakref at 0x16be686d0; to 'AsyncBackgroundExecutor' at 0x1084c7f10>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:17:05,796 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:17:05,796 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:17:06,005 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:17:06,005 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:17:06,005 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:17:06,040 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:17:06,041 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:17:17,961 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the recorded elevation for CASBC_0011_20240913_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:70239389-3d97-5444-2d3e-d2636c5146fa', 'checkpoint_ns': 'tools:70239389-3d97-5444-2d3e-d2636c5146fa'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x1096503d0>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '70239389-3d97-5444-2d3e-d2636c5146fa', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x162ae35b0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x162f45100>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108fd4f40>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108fd46c0>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108fd74c0>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x108443e10>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x161421e90>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426b9-b19f-6db2-8001-1983bbb75d82'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:70239389-3d97-5444-2d3e-d2636c5146fa', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109901090>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1084be440>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1096f8b80>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1084bf790>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x1618277e0; to 'PregelExecutableTask' at 0x108fb8c10>, stream=False, retry=None, futures=<weakref at 0x16b778ef0; to 'FuturesDict' at 0x16cdf6cf0>, schedule_task=<weakref at 0x108f32260; to 'AsyncPregelLoop' at 0x108ff1010>, submit=<weakref at 0x108f323b0; to 'AsyncBackgroundExecutor' at 0x10961b650>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:17:17,961 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:17:17,962 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:17:18,179 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:17:18,179 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:17:18,179 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:17:18,219 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:17:18,219 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?cbh ?cbd
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:CBH ?cbh .
  ?treeShrubMetrics wifire:LF_CBD ?cbd .
}
LIMIT 50
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?usvol
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegMetrics .
  ?vegMetrics wifire:USvol ?usvol .
}
LIMIT 50

2025-06-05 17:17:30,291 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:17:30,291 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:17:30,292 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:17:30,294 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:17:30,294 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:17:30,294 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?elevation
WHERE {
  ?plot wifire:plotName "CASBC_0011_20240913_1" .
  ?plot wifire:hasFireBehaviorMetrics ?fireBehaviorMetrics .
  ?fireBehaviorMetrics wifire:LF_EVEL ?elevation .
}
LIMIT 50

2025-06-05 17:17:51,096 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:17:51,097 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:17:51,098 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:17:53,130 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the canopy base height and canopy bulk density for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 4, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:d9db9ef4-def7-034e-fcf6-88f3e6422376', 'checkpoint_ns': 'tools:d9db9ef4-def7-034e-fcf6-88f3e6422376'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x108f49a50>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'd9db9ef4-def7-034e-fcf6-88f3e6422376', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x162ae25c0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x108441000>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108fa0680>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108fa0840>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108fa3880>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x1086e2a50>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x108fa0250>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426bb-0107-69ee-8003-5939f102e747'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:d9db9ef4-def7-034e-fcf6-88f3e6422376', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b8e8610>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10960af80>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x169e76340>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10960b1c0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x162ad6d40; to 'PregelExecutableTask' at 0x108fb9ab0>, stream=False, retry=None, futures=<weakref at 0x162ad4810; to 'FuturesDict' at 0x109626870>, schedule_task=<weakref at 0x108f31000; to 'AsyncPregelLoop' at 0x108fa2390>, submit=<weakref at 0x108f30f90; to 'AsyncBackgroundExecutor' at 0x16cdc2410>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:17:53,131 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:17:53,131 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:17:53,357 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:17:53,358 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:17:53,358 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:17:53,398 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:17:53,399 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?cbh ?cbd
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:CBH ?cbh .
  ?treeShrubMetrics wifire:LF_CBD ?cbd .
}
LIMIT 50

2025-06-05 17:17:53,764 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:17:53,765 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:17:53,765 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:18:05,172 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the mean shrub volume (MSvol) recorded for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:826ceeed-897e-40f1-b9b4-72b00deda821', 'checkpoint_ns': 'tools:826ceeed-897e-40f1-b9b4-72b00deda821'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x108ff3050>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '826ceeed-897e-40f1-b9b4-72b00deda821', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b8f33d0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x1096e3280>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108ff3080>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108ff1400>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108ff0480>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10869bb90>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x1096db550>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426bb-73de-6e22-8001-dc160e873138'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:826ceeed-897e-40f1-b9b4-72b00deda821', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1096379d0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x108f524a0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x109603740>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1084bf4f0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x1096ead40; to 'PregelExecutableTask' at 0x16be99510>, stream=False, retry=None, futures=<weakref at 0x1096eade0; to 'FuturesDict' at 0x108f6e630>, schedule_task=<weakref at 0x108f30120; to 'AsyncPregelLoop' at 0x109653890>, submit=<weakref at 0x16be6b920; to 'AsyncBackgroundExecutor' at 0x10847b3d0>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:18:05,172 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:18:05,173 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:18:05,389 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:18:05,389 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:18:05,390 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:18:05,435 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:18:05,435 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:18:16,238 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the overstory leaf area index (OLAI) for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:cb9053ea-ecd3-fa9b-6336-85d3e9eb2132', 'checkpoint_ns': 'tools:cb9053ea-ecd3-fa9b-6336-85d3e9eb2132'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x1099d9610>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'cb9053ea-ecd3-fa9b-6336-85d3e9eb2132', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b8f16c0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x1099d33c0>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1099d3380>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1099d3480>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1099d34c0>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x162f12950>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x109919a90>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426bb-dd6a-6f30-8001-3ac411a1f852'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:cb9053ea-ecd3-fa9b-6336-85d3e9eb2132', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1084dc430>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109903f70>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1099c9b20>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109900250>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10962f380; to 'PregelExecutableTask' at 0x108fb8670>, stream=False, retry=None, futures=<weakref at 0x10962f240; to 'FuturesDict' at 0x1096f6210>, schedule_task=<weakref at 0x1099709e0; to 'AsyncPregelLoop' at 0x1096b76d0>, submit=<weakref at 0x108f31c40; to 'AsyncBackgroundExecutor' at 0x1099cee50>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:18:16,239 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:18:16,239 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:18:16,442 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:18:16,443 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:18:16,443 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:18:16,477 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:18:16,478 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:18:19,550 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the understory leaf area index (ULAI) for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:8a37ce42-5073-463a-2899-31ce5c31c286', 'checkpoint_ns': 'tools:8a37ce42-5073-463a-2899-31ce5c31c286'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x1099b42d0>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '8a37ce42-5073-463a-2899-31ce5c31c286', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169e8f880>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109965dc0>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109965e80>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109965a40>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1099658c0>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10999a8d0>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x1099668d0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426bb-fcfd-65b4-8001-c82462c314f1'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:8a37ce42-5073-463a-2899-31ce5c31c286', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x108f52c20>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x108f52020>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1099ac720>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16cd91f00>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x1099558a0; to 'PregelExecutableTask' at 0x16be9b880>, stream=False, retry=None, futures=<weakref at 0x1099562a0; to 'FuturesDict' at 0x10868be30>, schedule_task=<weakref at 0x108f33f40; to 'AsyncPregelLoop' at 0x109967450>, submit=<weakref at 0x108f33c30; to 'AsyncBackgroundExecutor' at 0x1099cf310>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:18:19,551 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:18:19,551 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:18:19,770 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:18:19,771 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:18:19,771 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:18:19,815 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:18:19,816 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?msvol
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegMetrics .
  ?vegMetrics wifire:MSvol ?msvol .
}
LIMIT 50

2025-06-05 17:18:42,179 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:18:42,180 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:18:42,181 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?olai
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:OLAI ?olai .
}
LIMIT 50

2025-06-05 17:18:45,772 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:18:45,773 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:18:45,773 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?ulai
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegMetrics .
  ?vegMetrics wifire:ULAI ?ulai .
}
LIMIT 50

> Finished chain.

2025-06-05 17:18:54,029 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:18:54,029 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:18:54,030 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:19:01,959 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the mean shrub volume (MSvol) recorded for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 4, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:77c775c5-829a-e3bb-2147-bd916e5321c5', 'checkpoint_ns': 'tools:77c775c5-829a-e3bb-2147-bd916e5321c5'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10b275650>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '77c775c5-829a-e3bb-2147-bd916e5321c5', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16be07d30>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x1096e3280>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108ff3080>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108ff1400>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108ff0480>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10869bb90>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x1096db550>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426bd-916c-6b5e-8003-e96c8661c1c4'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:77c775c5-829a-e3bb-2147-bd916e5321c5', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109968d90>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10993f2b0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x108459d00>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109922260>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x16b798130; to 'PregelExecutableTask' at 0x16be99510>, stream=False, retry=None, futures=<weakref at 0x1614a9760; to 'FuturesDict' at 0x10868af30>, schedule_task=<weakref at 0x108f30120; to 'AsyncPregelLoop' at 0x109653890>, submit=<weakref at 0x16be6b920; to 'AsyncBackgroundExecutor' at 0x10847b3d0>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:19:01,959 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:19:01,959 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:19:02,174 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:19:02,175 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:19:02,175 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:19:02,209 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:19:02,209 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?msvol
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegMetrics .
  ?vegMetrics wifire:MSvol ?msvol .
}
LIMIT 50

2025-06-05 17:19:02,601 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:19:02,602 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:19:02,602 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:19:13,933 - wildfire_kg.tools.kg - ERROR - Error querying knowledge graph: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
Traceback (most recent call last):
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/kg_tool.py", line 124, in query_knowledge_graph
    result = qa_chain.invoke({qa_chain.input_key: query})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 167, in invoke
    raise e
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 157, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain_community/chains/graph_qa/ontotext_graphdb.py", line 127, in _call
    sparql_generation_chain_result = self.sparql_generation_chain.invoke(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 167, in invoke
    raise e
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 157, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain/chains/llm.py", line 127, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain/chains/llm.py", line 139, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 947, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 766, in generate
    self._generate_with_cache(
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 1012, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 800, in _generate
    response = self.client.create(**payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1296, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/openai/_base_client.py", line 973, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1062, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1111, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1062, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1111, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1077, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
2025-06-05 17:19:22,731 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the understory leaf area index (ULAI) for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 4, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:9d10ed16-386f-1511-d2d1-c2f8ee97a7b7', 'checkpoint_ns': 'tools:9d10ed16-386f-1511-d2d1-c2f8ee97a7b7'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x109974e50>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '9d10ed16-386f-1511-d2d1-c2f8ee97a7b7', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169e8f880>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109965dc0>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109965e80>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109965a40>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1099658c0>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10999a8d0>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x1099668d0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426be-5788-6766-8003-936048494c49'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:9d10ed16-386f-1511-d2d1-c2f8ee97a7b7', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16cd91f00>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x108f52bc0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1099ac720>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109927a30>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x1099c2e80; to 'PregelExecutableTask' at 0x16be9b880>, stream=False, retry=None, futures=<weakref at 0x1099c2930; to 'FuturesDict' at 0x108689df0>, schedule_task=<weakref at 0x108f33f40; to 'AsyncPregelLoop' at 0x109967450>, submit=<weakref at 0x108f33c30; to 'AsyncBackgroundExecutor' at 0x1099cf310>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:19:22,732 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:19:22,732 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:19:22,809 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What type of tree shrub metrics are available for the plots? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 4, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:73e028c9-2462-7f2d-0f2f-e4f65c83a6d4', 'checkpoint_ns': 'tools:73e028c9-2462-7f2d-0f2f-e4f65c83a6d4'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x108fabd50>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '73e028c9-2462-7f2d-0f2f-e4f65c83a6d4', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169e8d8a0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x108fa0b00>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108fa3f40>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108fa3580>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108fa3840>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10842a950>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x108f48b50>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426be-5847-6a80-8003-ca58a91b6ac4'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:73e028c9-2462-7f2d-0f2f-e4f65c83a6d4', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16bee7c40>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10b2ab010>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1086928e0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x108f5b070>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x161497920; to 'PregelExecutableTask' at 0x10b98beb0>, stream=False, retry=None, futures=<weakref at 0x161494130; to 'FuturesDict' at 0x169e87d10>, schedule_task=<weakref at 0x108f30c80; to 'AsyncPregelLoop' at 0x108f72610>, submit=<weakref at 0x108f30ba0; to 'AsyncBackgroundExecutor' at 0x108f72190>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:19:22,809 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:19:22,810 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:19:23,012 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:19:23,012 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:19:23,013 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:19:23,087 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:19:23,088 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:19:23,088 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:19:23,120 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:19:23,120 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...
2025-06-05 17:19:23,138 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:19:23,138 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...


> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?ulai
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegMetrics .
  ?vegMetrics wifire:ULAI ?ulai .
}
LIMIT 50
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?metric ?value
WHERE {
  ?plot a wifire:PlotMetrics .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  {
    ?treeShrubMetrics wifire:CBH ?value .
    BIND("Canopy Base Height" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MDBH ?value .
    BIND("Mean Diameter at Breast Height" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MLAI ?value .
    BIND("Mean Leaf Area Index" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MaxSD ?value .
    BIND("Maximum Shrub Diameter" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MaxSH ?value .
    BIND("Maximum Shrub Height" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MaxTH ?value .
    BIND("Maximum Tree Height" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MeanSA ?value .
    BIND("Mean Shrub Area" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MeanSD ?value .
    BIND("Mean Stem Density" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MeanSH ?value .
    BIND("Mean Shrub Height" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MeanTH ?value .
    BIND("Mean Tree Height" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MinSD ?value .
    BIND("Minimum Shrub Diameter" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:SDHT ?value .
    BIND("Shrub Height" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:SDSD ?value .
    BIND("Standard Deviation of Shrub Diameter" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:SDSHT ?value .
    BIND("Standard Deviation of Shrub Height" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:ShrubsN ?value .
    BIND("Number of Shrubs" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:TreesN ?value .
    BIND("Number of Trees" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:LF_CBD ?value .
    BIND("Canopy Bulk Density" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:scaledShrubArea ?value .
    BIND("Scaled Shrub Area" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:shrubArea ?value .
    BIND("Total Shrub Area" AS ?metric)
  }
}
LIMIT 50

2025-06-05 17:19:23,529 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:19:23,530 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:19:23,530 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:19:27,294 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the EVT classification for CASBC_0011_20240913_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:b5eebe47-04e5-8fcf-66b7-80480adc0a07', 'checkpoint_ns': 'tools:b5eebe47-04e5-8fcf-66b7-80480adc0a07'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x108f45350>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'b5eebe47-04e5-8fcf-66b7-80480adc0a07', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169e8c310>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x108fb0c40>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b23e180>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b23cd80>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b23ed40>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x109962590>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10b99e8d0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426be-830c-6630-8001-fb34e6b6d4a1'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:b5eebe47-04e5-8fcf-66b7-80480adc0a07', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10b2aae90>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1099261a0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1099f2ac0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b81cdf0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10b242610; to 'PregelExecutableTask' at 0x16b7b8e50>, stream=False, retry=None, futures=<weakref at 0x10b242250; to 'FuturesDict' at 0x16be3d4f0>, schedule_task=<weakref at 0x10b99a7a0; to 'AsyncPregelLoop' at 0x10b99fed0>, submit=<weakref at 0x108f31070; to 'AsyncBackgroundExecutor' at 0x109998490>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:19:27,294 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:19:27,294 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:19:27,501 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:19:27,502 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:19:27,502 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:19:27,541 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:19:27,541 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:19:36,342 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:19:36,343 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:19:36,343 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:19:37,886 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the Leaf Area Index (LAI) for the plot named CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:a3a926e3-f7a1-1283-c2a4-3d3a291abecf', 'checkpoint_ns': 'tools:a3a926e3-f7a1-1283-c2a4-3d3a291abecf'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x108f11310>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'a3a926e3-f7a1-1283-c2a4-3d3a291abecf', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x162ae3d30>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109660c80>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1096608c0>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109661c80>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109661e00>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x1096620d0>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x109650110>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426be-e80f-6f3c-8001-a0b4f9e61aff'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:a3a926e3-f7a1-1283-c2a4-3d3a291abecf', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10844c400>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10844e2c0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10b9bcae0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10844f130>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x161ca1d50; to 'PregelExecutableTask' at 0x16b7b9ab0>, stream=False, retry=None, futures=<weakref at 0x161ca3470; to 'FuturesDict' at 0x16b8852b0>, schedule_task=<weakref at 0x16be68f20; to 'AsyncPregelLoop' at 0x109662210>, submit=<weakref at 0x16be68200; to 'AsyncBackgroundExecutor' at 0x10b21b090>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:19:37,887 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:19:37,887 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:19:38,136 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:19:38,136 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:19:38,136 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:19:38,174 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:19:38,174 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:19:51,413 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the total basal area for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:471d6fbc-ca6a-b7c9-8b32-0c9eddfe739b', 'checkpoint_ns': 'tools:471d6fbc-ca6a-b7c9-8b32-0c9eddfe739b'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x108431250>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '471d6fbc-ca6a-b7c9-8b32-0c9eddfe739b', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169e8c7c0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109673500>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1084c4740>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1084c4880>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1084c4840>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10b219c10>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10841a150>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426bf-6910-6a46-8001-b13099ec1182'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:471d6fbc-ca6a-b7c9-8b32-0c9eddfe739b', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b860490>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b862d70>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10b282ac0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b8620e0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x162ad7fb0; to 'PregelExecutableTask' at 0x16be983a0>, stream=False, retry=None, futures=<weakref at 0x162ad6840; to 'FuturesDict' at 0x16b7ee330>, schedule_task=<weakref at 0x16be6ba00; to 'AsyncPregelLoop' at 0x1084c4d90>, submit=<weakref at 0x16be68900; to 'AsyncBackgroundExecutor' at 0x10b2b6650>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:19:51,415 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:19:51,415 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:19:51,642 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:19:51,642 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:19:51,642 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:19:51,679 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:19:51,680 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?evt
WHERE {
  ?plot wifire:plotName "CASBC_0011_20240913_1" .
  ?plot wifire:hasFireBehaviorMetrics ?fireBehaviorMetrics .
  ?fireBehaviorMetrics wifire:LF_EVT ?evt .
}
LIMIT 50

2025-06-05 17:20:04,207 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:20:04,207 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:20:04,207 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?lai
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:LAI ?lai .
}
LIMIT 50

2025-06-05 17:20:11,887 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: How many plots are there in Santa Barbara County? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:d812ccfd-97a3-6ab4-ad4a-732cdd284921', 'checkpoint_ns': 'tools:d812ccfd-97a3-6ab4-ad4a-732cdd284921'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x16beaa910>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'd812ccfd-97a3-6ab4-ad4a-732cdd284921', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169f236a0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109672300>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16bea9180>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16bea8740>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16bea9780>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x108f72950>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x108673850>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426c0-2c53-6ce2-8001-b1300799a96d'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:d812ccfd-97a3-6ab4-ad4a-732cdd284921', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16be08ac0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x108607280>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x108f9d1c0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16cd4bc70>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x161832430; to 'PregelExecutableTask' at 0x16be99990>, stream=False, retry=None, futures=<weakref at 0x161837c90; to 'FuturesDict' at 0x1084b78f0>, schedule_task=<weakref at 0x16b7d1bd0; to 'AsyncPregelLoop' at 0x1084b8c10>, submit=<weakref at 0x16be68430; to 'AsyncBackgroundExecutor' at 0x16bea8fd0>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:20:11,888 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:20:11,888 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:20:12,106 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:20:12,106 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:20:12,107 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:20:12,140 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:20:12,141 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:20:13,186 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:20:13,187 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:20:13,187 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?basalArea
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:basalArea ?basalArea .
}
LIMIT 50

2025-06-05 17:20:27,310 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:20:27,311 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:20:27,311 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:20:36,095 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: average temperature in San Diego, CA yesterday
2025-06-05 17:20:36,096 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:20:36,096 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'yesterday': 2025-06-05
2025-06-05 17:20:36,097 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-05 for query: average temperature in San Diego, CA yesterday
2025-06-05 17:20:36,097 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-05
2025-06-05 17:20:36,097 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: -1
2025-06-05 17:20:36,097 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:20:36,097 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-05 00:00:00+00:00
2025-06-05 17:20:36,098 - wildfire_kg.tools.weather - INFO - - Location: San Diego, CA
2025-06-05 17:20:36,098 - wildfire_kg.tools.weather - INFO - - Type: Historical
2025-06-05 17:20:36,558 - wildfire_kg.tools.weather - INFO - Making historical API call...
2025-06-05 17:20:36,558 - wildfire_kg.tools.weather - INFO - Calling historical endpoint: https://history.openweathermap.org/data/2.5/history/city with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 32.7174202, 'lon': -117.1627728, 'type': 'hour', 'start': 1749106800, 'end': 1749193199}

==================================================
API Call Details:
Endpoint: https://history.openweathermap.org/data/2.5/history/city
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 32.7174202,
  "lon": -117.1627728,
  "type": "hour",
  "start": 1749106800,
  "end": 1749193199
}
Status Code: 200
Response: {
  "message": "Count: 18",
  "cod": "200",
  "city_id": 1,
  "calctime": 0.004501755,
  "cnt": 18,
  "list": [
    {
      "dt": 1749106800,
      "main": {
        "temp": 16.39,
        "feels_like": 16.41,
        "pressure": 1012,
        "humidity": 89,
        "temp_min": 15.47,
        "temp_max": 17.24
      },
      "wind": {
        "speed": 3.09,
        "deg": 320
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749110400,
      "main": {
        "temp": 16.33,
        "feels_like": 16.37,
        "pressure": 1012,
        "humidity": 90,
        "temp_min": 15.47,
        "temp_max": 17.24
      },
      "wind": {
        "speed": 3.13,
        "deg": 309,
        "gust": 4.47
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749114000,
      "main": {
        "temp": 16.15,
        "feels_like": 16.2,
        "pressure": 1012,
        "humidity": 91,
        "temp_min": 15.46,
        "temp_max": 17.09
      },
      "wind": {
        "speed": 2.57,
        "deg": 320
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749117600,
      "main": {
        "temp": 16.13,
        "feels_like": 16.2,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.46,
        "temp_max": 17.09
      },
      "wind": {
        "speed": 1.79,
        "deg": 304,
        "gust": 3.58
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749121200,
      "main": {
        "temp": 16.11,
        "feels_like": 16.18,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.42,
        "temp_max": 16.89
      },
      "wind": {
        "speed": 1.79,
        "deg": 310,
        "gust": 3.13
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749124800,
      "main": {
        "temp": 16.14,
        "feels_like": 16.21,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.47,
        "temp_max": 16.89
      },
      "wind": {
        "speed": 2.06,
        "deg": 290
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749128400,
      "main": {
        "temp": 16.16,
        "feels_like": 16.23,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.47,
        "temp_max": 17.16
      },
      "wind": {
        "speed": 3.13,
        "deg": 310,
        "gust": 4.47
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749132000,
      "main": {
        "temp": 16.31,
        "feels_like": 16.4,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.42,
        "temp_max": 17.18
      },
      "wind": {
        "speed": 3.13,
        "deg": 343,
        "gust": 4.92
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749135600,
      "main": {
        "temp": 16.69,
        "feels_like": 16.79,
        "pressure": 1013,
        "humidity": 91,
        "temp_min": 15.59,
        "temp_max": 17.77
      },
      "wind": {
        "speed": 3.58,
        "deg": 313,
        "gust": 5.36
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 701,
          "main": "Mist",
          "description": "mist",
          "icon": "50d"
        }
      ]
    },
    {
      "dt": 1749139200,
      "main": {
        "temp": 17.23,
        "feels_like": 17.36,
        "pressure": 1013,
        "humidity": 90,
        "temp_min": 16.09,
        "temp_max": 18.6
      },
      "wind": {
        "speed": 2.68,
        "deg": 303,
        "gust": 4.02
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749142800,
      "main": {
        "temp": 17.58,
        "feels_like": 17.69,
        "pressure": 1013,
        "humidity": 88,
        "temp_min": 16.53,
        "temp_max": 19.12
      },
      "wind": {
        "speed": 3.6,
        "deg": 270
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749146400,
      "main": {
        "temp": 17.45,
        "feels_like": 17.57,
        "pressure": 1013,
        "humidity": 89,
        "temp_min": 16.53,
        "temp_max": 18.87
      },
      "wind": {
        "speed": 4.02,
        "deg": 282,
        "gust": 5.81
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749150000,
      "main": {
        "temp": 17.89,
        "feels_like": 17.95,
        "pressure": 1013,
        "humidity": 85,
        "temp_min": 17.08,
        "temp_max": 18.9
      },
      "wind": {
        "speed": 4.63,
        "deg": 270
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 701,
          "main": "Mist",
          "description": "mist",
          "icon": "50d"
        }
      ]
    },
    {
      "dt": 1749153600,
      "main": {
        "temp": 18.02,
        "feels_like": 18.1,
        "pressure": 1013,
        "humidity": 85,
        "temp_min": 17.1,
        "temp_max": 19.42
      },
      "wind": {
        "speed": 5.14,
        "deg": 310
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749157200,
      "main": {
        "temp": 18.42,
        "feels_like": 18.46,
        "pressure": 1012,
        "humidity": 82,
        "temp_min": 17.55,
        "temp_max": 19.93
      },
      "wind": {
        "speed": 5.66,
        "deg": 300
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 300,
          "main": "Drizzle",
          "description": "light intensity drizzle",
          "icon": "09d"
        }
      ]
    },
    {
      "dt": 1749160800,
      "main": {
        "temp": 18.31,
        "feels_like": 18.34,
        "pressure": 1012,
        "humidity": 82,
        "temp_min": 17.08,
        "temp_max": 19.46
      },
      "wind": {
        "speed": 4.63,
        "deg": 300
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 300,
          "main": "Drizzle",
          "description": "light intensity drizzle",
          "icon": "09d"
        }
      ]
    },
    {
      "dt": 1749164400,
      "main": {
        "temp": 18.66,
        "feels_like": 18.7,
        "pressure": 1012,
        "humidity": 81,
        "temp_min": 17.55,
        "temp_max": 20.07
      },
      "wind": {
        "speed": 4.92,
        "deg": 309,
        "gust": 6.71
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749168000,
      "main": {
        "temp": 18.24,
        "feels_like": 18.23,
        "pressure": 1012,
        "humidity": 81,
        "temp_min": 17.08,
        "temp_max": 20.6
      },
      "wind": {
        "speed": 4.92,
        "deg": 276,
        "gust": 5.81
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    }
  ]
}
==================================================

2025-06-05 17:20:37,110 - wildfire_kg.tools.weather - INFO - API response for San Diego: {"message": "Count: 18", "cod": "200", "city_id": 1, "calctime": 0.004501755, "cnt": 18, "list": [{"dt": 1749106800, "main": {"temp": 16.39, "feels_like": 16.41, "pressure": 1012, "humidity": 89, "tem...
2025-06-05 17:20:37,111 - wildfire_kg.tools.weather - INFO - Averaging 17 historical entries for San Diego on 2025-06-05

Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT (COUNT(DISTINCT ?plot) AS ?plotCount)
WHERE {
  ?plot a wifire:PlotMetrics .
  ?plot wifire:hasLocationDataPlot ?locationData .
  ?locationData wifire:plotCounty ?county .
  FILTER(CONTAINS(LCASE(?county), LCASE("santa barbara"))) .
}
LIMIT 50

2025-06-05 17:20:48,176 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: average temperature in San Diego, CA yesterday
2025-06-05 17:20:48,176 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:20:48,177 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'yesterday': 2025-06-05
2025-06-05 17:20:48,177 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-05 for query: average temperature in San Diego, CA yesterday
2025-06-05 17:20:48,177 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-05
2025-06-05 17:20:48,178 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: -1
2025-06-05 17:20:48,178 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:20:48,179 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-05 00:00:00+00:00
2025-06-05 17:20:48,180 - wildfire_kg.tools.weather - INFO - - Location: San Diego, CA
2025-06-05 17:20:48,180 - wildfire_kg.tools.weather - INFO - - Type: Historical
2025-06-05 17:20:48,349 - wildfire_kg.tools.weather - INFO - Making historical API call...
2025-06-05 17:20:48,350 - wildfire_kg.tools.weather - INFO - Calling historical endpoint: https://history.openweathermap.org/data/2.5/history/city with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 32.7174202, 'lon': -117.1627728, 'type': 'hour', 'start': 1749106800, 'end': 1749193199}
2025-06-05 17:20:48,687 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:20:48,688 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:20:48,688 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

==================================================
API Call Details:
Endpoint: https://history.openweathermap.org/data/2.5/history/city
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 32.7174202,
  "lon": -117.1627728,
  "type": "hour",
  "start": 1749106800,
  "end": 1749193199
}
Status Code: 200
Response: {
  "message": "Count: 18",
  "cod": "200",
  "city_id": 1,
  "calctime": 0.004206826,
  "cnt": 18,
  "list": [
    {
      "dt": 1749106800,
      "main": {
        "temp": 16.39,
        "feels_like": 16.41,
        "pressure": 1012,
        "humidity": 89,
        "temp_min": 15.47,
        "temp_max": 17.24
      },
      "wind": {
        "speed": 3.09,
        "deg": 320
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749110400,
      "main": {
        "temp": 16.33,
        "feels_like": 16.37,
        "pressure": 1012,
        "humidity": 90,
        "temp_min": 15.47,
        "temp_max": 17.24
      },
      "wind": {
        "speed": 3.13,
        "deg": 309,
        "gust": 4.47
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749114000,
      "main": {
        "temp": 16.15,
        "feels_like": 16.2,
        "pressure": 1012,
        "humidity": 91,
        "temp_min": 15.46,
        "temp_max": 17.09
      },
      "wind": {
        "speed": 2.57,
        "deg": 320
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749117600,
      "main": {
        "temp": 16.13,
        "feels_like": 16.2,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.46,
        "temp_max": 17.09
      },
      "wind": {
        "speed": 1.79,
        "deg": 304,
        "gust": 3.58
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749121200,
      "main": {
        "temp": 16.11,
        "feels_like": 16.18,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.42,
        "temp_max": 16.89
      },
      "wind": {
        "speed": 1.79,
        "deg": 310,
        "gust": 3.13
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749124800,
      "main": {
        "temp": 16.14,
        "feels_like": 16.21,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.47,
        "temp_max": 16.89
      },
      "wind": {
        "speed": 2.06,
        "deg": 290
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749128400,
      "main": {
        "temp": 16.16,
        "feels_like": 16.23,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.47,
        "temp_max": 17.16
      },
      "wind": {
        "speed": 3.13,
        "deg": 310,
        "gust": 4.47
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749132000,
      "main": {
        "temp": 16.31,
        "feels_like": 16.4,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.42,
        "temp_max": 17.18
      },
      "wind": {
        "speed": 3.13,
        "deg": 343,
        "gust": 4.92
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749135600,
      "main": {
        "temp": 16.69,
        "feels_like": 16.79,
        "pressure": 1013,
        "humidity": 91,
        "temp_min": 15.59,
        "temp_max": 17.77
      },
      "wind": {
        "speed": 3.58,
        "deg": 313,
        "gust": 5.36
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 701,
          "main": "Mist",
          "description": "mist",
          "icon": "50d"
        }
      ]
    },
    {
      "dt": 1749139200,
      "main": {
        "temp": 17.23,
        "feels_like": 17.36,
        "pressure": 1013,
        "humidity": 90,
        "temp_min": 16.09,
        "temp_max": 18.6
      },
      "wind": {
        "speed": 2.68,
        "deg": 303,
        "gust": 4.02
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749142800,
      "main": {
        "temp": 17.58,
        "feels_like": 17.69,
        "pressure": 1013,
        "humidity": 88,
        "temp_min": 16.53,
        "temp_max": 19.12
      },
      "wind": {
        "speed": 3.6,
        "deg": 270
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749146400,
      "main": {
        "temp": 17.45,
        "feels_like": 17.57,
        "pressure": 1013,
        "humidity": 89,
        "temp_min": 16.53,
        "temp_max": 18.87
      },
      "wind": {
        "speed": 4.02,
        "deg": 282,
        "gust": 5.81
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749150000,
      "main": {
        "temp": 17.89,
        "feels_like": 17.95,
        "pressure": 1013,
        "humidity": 85,
        "temp_min": 17.08,
        "temp_max": 18.9
      },
      "wind": {
        "speed": 4.63,
        "deg": 270
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 701,
          "main": "Mist",
          "description": "mist",
          "icon": "50d"
        }
      ]
    },
    {
      "dt": 1749153600,
      "main": {
        "temp": 18.02,
        "feels_like": 18.1,
        "pressure": 1013,
        "humidity": 85,
        "temp_min": 17.1,
        "temp_max": 19.42
      },
      "wind": {
        "speed": 5.14,
        "deg": 310
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749157200,
      "main": {
        "temp": 18.42,
        "feels_like": 18.46,
        "pressure": 1012,
        "humidity": 82,
        "temp_min": 17.55,
        "temp_max": 19.93
      },
      "wind": {
        "speed": 5.66,
        "deg": 300
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 300,
          "main": "Drizzle",
          "description": "light intensity drizzle",
          "icon": "09d"
        }
      ]
    },
    {
      "dt": 1749160800,
      "main": {
        "temp": 18.31,
        "feels_like": 18.34,
        "pressure": 1012,
        "humidity": 82,
        "temp_min": 17.08,
        "temp_max": 19.46
      },
      "wind": {
        "speed": 4.63,
        "deg": 300
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 300,
          "main": "Drizzle",
          "description": "light intensity drizzle",
          "icon": "09d"
        }
      ]
    },
    {
      "dt": 1749164400,
      "main": {
        "temp": 18.66,
        "feels_like": 18.7,
        "pressure": 1012,
        "humidity": 81,
        "temp_min": 17.55,
        "temp_max": 20.07
      },
      "wind": {
        "speed": 4.92,
        "deg": 309,
        "gust": 6.71
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749168000,
      "main": {
        "temp": 18.24,
        "feels_like": 18.23,
        "pressure": 1012,
        "humidity": 81,
        "temp_min": 17.08,
        "temp_max": 20.6
      },
      "wind": {
        "speed": 4.92,
        "deg": 276,
        "gust": 5.81
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    }
  ]
}
==================================================

2025-06-05 17:20:48,860 - wildfire_kg.tools.weather - INFO - API response for San Diego: {"message": "Count: 18", "cod": "200", "city_id": 1, "calctime": 0.004206826, "cnt": 18, "list": [{"dt": 1749106800, "main": {"temp": 16.39, "feels_like": 16.41, "pressure": 1012, "humidity": 89, "tem...
2025-06-05 17:20:48,861 - wildfire_kg.tools.weather - INFO - Averaging 17 historical entries for San Diego on 2025-06-05
2025-06-05 17:21:07,716 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the basal area value for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:79db6e81-2f66-a99e-a29b-98b64e71319d', 'checkpoint_ns': 'tools:79db6e81-2f66-a99e-a29b-98b64e71319d'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x16cd36050>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '79db6e81-2f66-a99e-a29b-98b64e71319d', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169e8c7c0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x16be4cc80>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16beeef80>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109673680>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16beedac0>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x1096789d0>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x16b7351d0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426c2-40be-6be4-8001-4f7348754168'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:79db6e81-2f66-a99e-a29b-98b64e71319d', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16bee75b0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16bee4ac0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x16cdd87c0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b7dee00>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x162cd7150; to 'PregelExecutableTask' at 0x16be9a9e0>, stream=False, retry=None, futures=<weakref at 0x162cd7100; to 'FuturesDict' at 0x1099b88f0>, schedule_task=<weakref at 0x16be3a0a0; to 'AsyncPregelLoop' at 0x16bec32d0>, submit=<weakref at 0x16be69fc0; to 'AsyncBackgroundExecutor' at 0x16bec0490>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:21:07,717 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:21:07,717 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:21:07,929 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:21:07,930 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:21:07,930 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:21:07,965 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:21:07,966 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:21:13,419 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: weather forecast for Los Angeles tomorrow
2025-06-05 17:21:13,420 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:21:13,420 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'tomorrow': 2025-06-07
2025-06-05 17:21:13,421 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-07 for query: weather forecast for Los Angeles tomorrow
2025-06-05 17:21:13,421 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-07
2025-06-05 17:21:13,421 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 1
2025-06-05 17:21:13,422 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:21:13,422 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-07 00:00:00+00:00
2025-06-05 17:21:13,423 - wildfire_kg.tools.weather - INFO - - Location: Los Angeles tomorrow
2025-06-05 17:21:13,424 - wildfire_kg.tools.weather - INFO - - Type: Forecast
2025-06-05 17:21:13,424 - wildfire_kg.tools.weather - INFO - DEBUG: Checking forecast range - Requested date: 2025-06-07, Max forecast date: 2025-06-11
2025-06-05 17:21:17,325 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: weather forecast for Los Angeles, CA tomorrow
2025-06-05 17:21:17,326 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:21:17,326 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'tomorrow': 2025-06-07
2025-06-05 17:21:17,326 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-07 for query: weather forecast for Los Angeles, CA tomorrow
2025-06-05 17:21:17,326 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-07
2025-06-05 17:21:17,327 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 1
2025-06-05 17:21:17,327 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:21:17,327 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-07 00:00:00+00:00
2025-06-05 17:21:17,327 - wildfire_kg.tools.weather - INFO - - Location: Los Angeles, CA
2025-06-05 17:21:17,327 - wildfire_kg.tools.weather - INFO - - Type: Forecast
2025-06-05 17:21:17,328 - wildfire_kg.tools.weather - INFO - DEBUG: Checking forecast range - Requested date: 2025-06-07, Max forecast date: 2025-06-11
2025-06-05 17:21:17,456 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: How many trees and shrubs are present in CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:bc6d600d-ab0a-de7c-e7d8-a96af2fcbe21', 'checkpoint_ns': 'tools:bc6d600d-ab0a-de7c-e7d8-a96af2fcbe21'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x16cd20910>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'bc6d600d-ab0a-de7c-e7d8-a96af2fcbe21', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16be05f30>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x16b85cec0>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108602c80>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16b658140>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16b65b540>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10861e450>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x16b85ec90>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426c2-9da4-61f6-8001-00ba854f7663'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:bc6d600d-ab0a-de7c-e7d8-a96af2fcbe21', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1099b3580>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1099b3eb0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x109621940>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16cd66a70>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10b9ee110; to 'PregelExecutableTask' at 0x10b9f5870>, stream=False, retry=None, futures=<weakref at 0x10b9ef740; to 'FuturesDict' at 0x109604530>, schedule_task=<weakref at 0x16be39af0; to 'AsyncPregelLoop' at 0x16b8880d0>, submit=<weakref at 0x16be6ba00; to 'AsyncBackgroundExecutor' at 0x1096e2b50>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:21:17,456 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:21:17,457 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:21:17,668 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:21:17,668 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:21:17,669 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:21:17,708 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:21:17,708 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...
2025-06-05 17:21:17,782 - wildfire_kg.tools.weather - INFO - Making forecast API call...
2025-06-05 17:21:17,782 - wildfire_kg.tools.weather - INFO - Calling forecast endpoint: https://pro.openweathermap.org/data/2.5/forecast with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 34.0536909, 'lon': -118.242766}

> Entering new OntotextGraphDBQAChain chain...

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/forecast
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 34.0536909,
  "lon": -118.242766
}
Status Code: 200
Response: {
  "cod": "200",
  "message": 0,
  "cnt": 40,
  "list": [
    {
      "dt": 1749178800,
      "main": {
        "temp": 20.39,
        "feels_like": 20.26,
        "temp_min": 19.54,
        "temp_max": 20.39,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 992,
        "humidity": 68,
        "temp_kf": 0.85
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "clouds": {
        "all": 50
      },
      "wind": {
        "speed": 3.53,
        "deg": 227,
        "gust": 3.36
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 03:00:00"
    },
    {
      "dt": 1749189600,
      "main": {
        "temp": 18.57,
        "feels_like": 18.31,
        "temp_min": 17.45,
        "temp_max": 18.57,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 993,
        "humidity": 70,
        "temp_kf": 1.12
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03n"
        }
      ],
      "clouds": {
        "all": 25
      },
      "wind": {
        "speed": 1.98,
        "deg": 209,
        "gust": 1.83
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 06:00:00"
    },
    {
      "dt": 1749200400,
      "main": {
        "temp": 17.25,
        "feels_like": 16.96,
        "temp_min": 17.25,
        "temp_max": 17.25,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 993,
        "humidity": 74,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 1
      },
      "wind": {
        "speed": 1.61,
        "deg": 202,
        "gust": 1.53
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 09:00:00"
    },
    {
      "dt": 1749211200,
      "main": {
        "temp": 16.6,
        "feels_like": 16.33,
        "temp_min": 16.6,
        "temp_max": 16.6,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 993,
        "humidity": 77,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 1
      },
      "wind": {
        "speed": 1.44,
        "deg": 206,
        "gust": 1.45
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 12:00:00"
    },
    {
      "dt": 1749222000,
      "main": {
        "temp": 18.17,
        "feels_like": 17.87,
        "temp_min": 18.17,
        "temp_max": 18.17,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 994,
        "humidity": 70,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 1
      },
      "wind": {
        "speed": 1.61,
        "deg": 222,
        "gust": 0.72
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 15:00:00"
    },
    {
      "dt": 1749232800,
      "main": {
        "temp": 22.88,
        "feels_like": 22.56,
        "temp_min": 22.88,
        "temp_max": 22.88,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 993,
        "humidity": 51,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 1
      },
      "wind": {
        "speed": 3.4,
        "deg": 233,
        "gust": 1.88
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 18:00:00"
    },
    {
      "dt": 1749243600,
      "main": {
        "temp": 23.69,
        "feels_like": 23.39,
        "temp_min": 23.69,
        "temp_max": 23.69,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 993,
        "humidity": 49,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 1
      },
      "wind": {
        "speed": 4.96,
        "deg": 238,
        "gust": 3.26
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 21:00:00"
    },
    {
      "dt": 1749254400,
      "main": {
        "temp": 22.93,
        "feels_like": 22.61,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 992,
        "humidity": 51,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 5.1,
        "deg": 229,
        "gust": 4.16
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 00:00:00"
    },
    {
      "dt": 1749265200,
      "main": {
        "temp": 19.62,
        "feels_like": 19.28,
        "temp_min": 19.62,
        "temp_max": 19.62,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 993,
        "humidity": 63,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 3.04,
        "deg": 220,
        "gust": 2.94
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 03:00:00"
    },
    {
      "dt": 1749276000,
      "main": {
        "temp": 18.6,
        "feels_like": 18.24,
        "temp_min": 18.6,
        "temp_max": 18.6,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 995,
        "humidity": 66,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 2.22,
        "deg": 224,
        "gust": 1.89
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 06:00:00"
    },
    {
      "dt": 1749286800,
      "main": {
        "temp": 17.71,
        "feels_like": 17.36,
        "temp_min": 17.71,
        "temp_max": 17.71,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 994,
        "humidity": 70,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 2.03,
        "deg": 228,
        "gust": 1.92
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 09:00:00"
    },
    {
      "dt": 1749297600,
      "main": {
        "temp": 17.12,
        "feels_like": 16.79,
        "temp_min": 17.12,
        "temp_max": 17.12,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 994,
        "humidity": 73,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 1.5,
        "deg": 226,
        "gust": 1.33
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 12:00:00"
    },
    {
      "dt": 1749308400,
      "main": {
        "temp": 19.15,
        "feels_like": 18.77,
        "temp_min": 19.15,
        "temp_max": 19.15,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 995,
        "humidity": 63,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 1.89,
        "deg": 222,
        "gust": 1.11
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 15:00:00"
    },
    {
      "dt": 1749319200,
      "main": {
        "temp": 23.82,
        "feels_like": 23.46,
        "temp_min": 23.82,
        "temp_max": 23.82,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 995,
        "humidity": 46,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 3.64,
        "deg": 231,
        "gust": 2.3
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 18:00:00"
    },
    {
      "dt": 1749330000,
      "main": {
        "temp": 25.21,
        "feels_like": 24.88,
        "temp_min": 25.21,
        "temp_max": 25.21,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 994,
        "humidity": 42,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 4.72,
        "deg": 235,
        "gust": 3.39
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 21:00:00"
    },
    {
      "dt": 1749340800,
      "main": {
        "temp": 24.97,
        "feels_like": 24.65,
        "temp_min": 24.97,
        "temp_max": 24.97,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 993,
        "humidity": 43,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 4.43,
        "deg": 229,
        "gust": 3.9
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 00:00:00"
    },
    {
      "dt": 1749351600,
      "main": {
        "temp": 21.7,
        "feels_like": 21.26,
        "temp_min": 21.7,
        "temp_max": 21.7,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 994,
        "humidity": 51,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 3.23,
        "deg": 204,
        "gust": 2.91
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 03:00:00"
    },
    {
      "dt": 1749362400,
      "main": {
        "temp": 20.22,
        "feels_like": 19.76,
        "temp_min": 20.22,
        "temp_max": 20.22,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 995,
        "humidity": 56,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 1.68,
        "deg": 166,
        "gust": 1.62
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 06:00:00"
    },
    {
      "dt": 1749373200,
      "main": {
        "temp": 19.78,
        "feels_like": 19.33,
        "temp_min": 19.78,
        "temp_max": 19.78,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 994,
        "humidity": 58,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 1.37,
        "deg": 159,
        "gust": 1.56
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 09:00:00"
    },
    {
      "dt": 1749384000,
      "main": {
        "temp": 19.17,
        "feels_like": 18.76,
        "temp_min": 19.17,
        "temp_max": 19.17,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 994,
        "humidity": 62,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 1.28,
        "deg": 151,
        "gust": 1.81
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 12:00:00"
    },
    {
      "dt": 1749394800,
      "main": {
        "temp": 21,
        "feels_like": 20.59,
        "temp_min": 21,
        "temp_max": 21,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 995,
        "humidity": 55,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 1.68,
        "deg": 160,
        "gust": 1.43
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 15:00:00"
    },
    {
      "dt": 1749405600,
      "main": {
        "temp": 26.5,
        "feels_like": 26.5,
        "temp_min": 26.5,
        "temp_max": 26.5,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 994,
        "humidity": 36,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 2.38,
        "deg": 208,
        "gust": 1.16
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 18:00:00"
    },
    {
      "dt": 1749416400,
      "main": {
        "temp": 28.48,
        "feels_like": 27.62,
        "temp_min": 28.48,
        "temp_max": 28.48,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 993,
        "humidity": 33,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 4.59,
        "deg": 233,
        "gust": 2.71
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 21:00:00"
    },
    {
      "dt": 1749427200,
      "main": {
        "temp": 26.87,
        "feels_like": 26.68,
        "temp_min": 26.87,
        "temp_max": 26.87,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 992,
        "humidity": 38,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 4.02,
        "deg": 230,
        "gust": 3.43
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-09 00:00:00"
    },
    {
      "dt": 1749438000,
      "main": {
        "temp": 23.16,
        "feels_like": 22.86,
        "temp_min": 23.16,
        "temp_max": 23.16,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 992,
        "humidity": 51,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 2.54,
        "deg": 209,
        "gust": 2.18
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-09 03:00:00"
    },
    {
      "dt": 1749448800,
      "main": {
        "temp": 22.42,
        "feels_like": 22.08,
        "temp_min": 22.42,
        "temp_max": 22.42,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 992,
        "humidity": 52,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 1.74,
        "deg": 165,
        "gust": 2.18
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 06:00:00"
    },
    {
      "dt": 1749459600,
      "main": {
        "temp": 21.35,
        "feels_like": 21,
        "temp_min": 21.35,
        "temp_max": 21.35,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 991,
        "humidity": 56,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 1.98,
        "deg": 160,
        "gust": 2.4
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 09:00:00"
    },
    {
      "dt": 1749470400,
      "main": {
        "temp": 20.58,
        "feels_like": 20.26,
        "temp_min": 20.58,
        "temp_max": 20.58,
        "pressure": 1010,
        "sea_level": 1010,
        "grnd_level": 991,
        "humidity": 60,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 8
      },

2025-06-05 17:21:17,961 - wildfire_kg.tools.weather - INFO - API response for Los Angeles: {"cod": "200", "message": 0, "cnt": 40, "list": [{"dt": 1749178800, "main": {"temp": 20.39, "feels_like": 20.26, "temp_min": 19.54, "temp_max": 20.39, "pressure": 1011, "sea_level": 1011, "grnd_level"...
2025-06-05 17:21:17,962 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: 8 forecast entries for Los Angeles on 2025-06-07
2025-06-05 17:21:28,766 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: weather forecast for Los Angeles, CA tomorrow
2025-06-05 17:21:28,766 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:21:28,766 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'tomorrow': 2025-06-07
2025-06-05 17:21:28,767 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-07 for query: weather forecast for Los Angeles, CA tomorrow
2025-06-05 17:21:28,767 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-07
2025-06-05 17:21:28,767 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 1
2025-06-05 17:21:28,767 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:21:28,768 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-07 00:00:00+00:00
2025-06-05 17:21:28,768 - wildfire_kg.tools.weather - INFO - - Location: Los Angeles, CA
2025-06-05 17:21:28,768 - wildfire_kg.tools.weather - INFO - - Type: Forecast
2025-06-05 17:21:28,769 - wildfire_kg.tools.weather - INFO - DEBUG: Checking forecast range - Requested date: 2025-06-07, Max forecast date: 2025-06-11
2025-06-05 17:21:28,942 - wildfire_kg.tools.weather - INFO - Making forecast API call...
2025-06-05 17:21:28,944 - wildfire_kg.tools.weather - INFO - Calling forecast endpoint: https://pro.openweathermap.org/data/2.5/forecast with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 34.0536909, 'lon': -118.242766}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/forecast
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 34.0536909,
  "lon": -118.242766
}
Status Code: 200
Response: {
  "cod": "200",
  "message": 0,
  "cnt": 40,
  "list": [
    {
      "dt": 1749178800,
      "main": {
        "temp": 20.39,
        "feels_like": 20.26,
        "temp_min": 19.54,
        "temp_max": 20.39,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 992,
        "humidity": 68,
        "temp_kf": 0.85
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "clouds": {
        "all": 50
      },
      "wind": {
        "speed": 3.53,
        "deg": 227,
        "gust": 3.36
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 03:00:00"
    },
    {
      "dt": 1749189600,
      "main": {
        "temp": 18.57,
        "feels_like": 18.31,
        "temp_min": 17.45,
        "temp_max": 18.57,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 993,
        "humidity": 70,
        "temp_kf": 1.12
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03n"
        }
      ],
      "clouds": {
        "all": 25
      },
      "wind": {
        "speed": 1.98,
        "deg": 209,
        "gust": 1.83
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 06:00:00"
    },
    {
      "dt": 1749200400,
      "main": {
        "temp": 17.25,
        "feels_like": 16.96,
        "temp_min": 17.25,
        "temp_max": 17.25,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 993,
        "humidity": 74,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 1
      },
      "wind": {
        "speed": 1.61,
        "deg": 202,
        "gust": 1.53
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 09:00:00"
    },
    {
      "dt": 1749211200,
      "main": {
        "temp": 16.6,
        "feels_like": 16.33,
        "temp_min": 16.6,
        "temp_max": 16.6,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 993,
        "humidity": 77,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 1
      },
      "wind": {
        "speed": 1.44,
        "deg": 206,
        "gust": 1.45
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 12:00:00"
    },
    {
      "dt": 1749222000,
      "main": {
        "temp": 18.17,
        "feels_like": 17.87,
        "temp_min": 18.17,
        "temp_max": 18.17,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 994,
        "humidity": 70,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 1
      },
      "wind": {
        "speed": 1.61,
        "deg": 222,
        "gust": 0.72
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 15:00:00"
    },
    {
      "dt": 1749232800,
      "main": {
        "temp": 22.88,
        "feels_like": 22.56,
        "temp_min": 22.88,
        "temp_max": 22.88,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 993,
        "humidity": 51,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 1
      },
      "wind": {
        "speed": 3.4,
        "deg": 233,
        "gust": 1.88
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 18:00:00"
    },
    {
      "dt": 1749243600,
      "main": {
        "temp": 23.69,
        "feels_like": 23.39,
        "temp_min": 23.69,
        "temp_max": 23.69,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 993,
        "humidity": 49,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 1
      },
      "wind": {
        "speed": 4.96,
        "deg": 238,
        "gust": 3.26
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 21:00:00"
    },
    {
      "dt": 1749254400,
      "main": {
        "temp": 22.93,
        "feels_like": 22.61,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 992,
        "humidity": 51,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 5.1,
        "deg": 229,
        "gust": 4.16
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 00:00:00"
    },
    {
      "dt": 1749265200,
      "main": {
        "temp": 19.62,
        "feels_like": 19.28,
        "temp_min": 19.62,
        "temp_max": 19.62,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 993,
        "humidity": 63,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 3.04,
        "deg": 220,
        "gust": 2.94
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 03:00:00"
    },
    {
      "dt": 1749276000,
      "main": {
        "temp": 18.6,
        "feels_like": 18.24,
        "temp_min": 18.6,
        "temp_max": 18.6,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 995,
        "humidity": 66,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 2.22,
        "deg": 224,
        "gust": 1.89
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 06:00:00"
    },
    {
      "dt": 1749286800,
      "main": {
        "temp": 17.71,
        "feels_like": 17.36,
        "temp_min": 17.71,
        "temp_max": 17.71,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 994,
        "humidity": 70,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 2.03,
        "deg": 228,
        "gust": 1.92
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 09:00:00"
    },
    {
      "dt": 1749297600,
      "main": {
        "temp": 17.12,
        "feels_like": 16.79,
        "temp_min": 17.12,
        "temp_max": 17.12,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 994,
        "humidity": 73,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 1.5,
        "deg": 226,
        "gust": 1.33
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 12:00:00"
    },
    {
      "dt": 1749308400,
      "main": {
        "temp": 19.15,
        "feels_like": 18.77,
        "temp_min": 19.15,
        "temp_max": 19.15,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 995,
        "humidity": 63,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 1.89,
        "deg": 222,
        "gust": 1.11
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 15:00:00"
    },
    {
      "dt": 1749319200,
      "main": {
        "temp": 23.82,
        "feels_like": 23.46,
        "temp_min": 23.82,
        "temp_max": 23.82,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 995,
        "humidity": 46,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 3.64,
        "deg": 231,
        "gust": 2.3
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 18:00:00"
    },
    {
      "dt": 1749330000,
      "main": {
        "temp": 25.21,
        "feels_like": 24.88,
        "temp_min": 25.21,
        "temp_max": 25.21,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 994,
        "humidity": 42,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 4.72,
        "deg": 235,
        "gust": 3.39
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 21:00:00"
    },
    {
      "dt": 1749340800,
      "main": {
        "temp": 24.97,
        "feels_like": 24.65,
        "temp_min": 24.97,
        "temp_max": 24.97,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 993,
        "humidity": 43,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 4.43,
        "deg": 229,
        "gust": 3.9
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 00:00:00"
    },
    {
      "dt": 1749351600,
      "main": {
        "temp": 21.7,
        "feels_like": 21.26,
        "temp_min": 21.7,
        "temp_max": 21.7,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 994,
        "humidity": 51,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 3.23,
        "deg": 204,
        "gust": 2.91
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 03:00:00"
    },
    {
      "dt": 1749362400,
      "main": {
        "temp": 20.22,
        "feels_like": 19.76,
        "temp_min": 20.22,
        "temp_max": 20.22,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 995,
        "humidity": 56,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 1.68,
        "deg": 166,
        "gust": 1.62
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 06:00:00"
    },
    {
      "dt": 1749373200,
      "main": {
        "temp": 19.78,
        "feels_like": 19.33,
        "temp_min": 19.78,
        "temp_max": 19.78,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 994,
        "humidity": 58,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 1.37,
        "deg": 159,
        "gust": 1.56
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 09:00:00"
    },
    {
      "dt": 1749384000,
      "main": {
        "temp": 19.17,
        "feels_like": 18.76,
        "temp_min": 19.17,
        "temp_max": 19.17,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 994,
        "humidity": 62,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 1.28,
        "deg": 151,
        "gust": 1.81
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 12:00:00"
    },
    {
      "dt": 1749394800,
      "main": {
        "temp": 21,
        "feels_like": 20.59,
        "temp_min": 21,
        "temp_max": 21,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 995,
        "humidity": 55,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 1.68,
        "deg": 160,
        "gust": 1.43
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 15:00:00"
    },
    {
      "dt": 1749405600,
      "main": {
        "temp": 26.5,
        "feels_like": 26.5,
        "temp_min": 26.5,
        "temp_max": 26.5,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 994,
        "humidity": 36,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 2.38,
        "deg": 208,
        "gust": 1.16
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 18:00:00"
    },
    {
      "dt": 1749416400,
      "main": {
        "temp": 28.48,
        "feels_like": 27.62,
        "temp_min": 28.48,
        "temp_max": 28.48,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 993,
        "humidity": 33,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 4.59,
        "deg": 233,
        "gust": 2.71
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 21:00:00"
    },
    {
      "dt": 1749427200,
      "main": {
        "temp": 26.87,
        "feels_like": 26.68,
        "temp_min": 26.87,
        "temp_max": 26.87,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 992,
        "humidity": 38,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 4.02,
        "deg": 230,
        "gust": 3.43
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-09 00:00:00"
    },
    {
      "dt": 1749438000,
      "main": {
        "temp": 23.16,
        "feels_like": 22.86,
        "temp_min": 23.16,
        "temp_max": 23.16,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 992,
        "humidity": 51,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 2.54,
        "deg": 209,
        "gust": 2.18
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-09 03:00:00"
    },
    {
      "dt": 1749448800,
      "main": {
        "temp": 22.42,
        "feels_like": 22.08,
        "temp_min": 22.42,
        "temp_max": 22.42,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 992,
        "humidity": 52,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 1.74,
        "deg": 165,
        "gust": 2.18
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 06:00:00"
    },
    {
      "dt": 1749459600,
      "main": {
        "temp": 21.35,
        "feels_like": 21,
        "temp_min": 21.35,
        "temp_max": 21.35,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 991,
        "humidity": 56,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 1.98,
        "deg": 160,
        "gust": 2.4
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 09:00:00"
    },
    {
      "dt": 1749470400,
      "main": {
        "temp": 20.58,
        "feels_like": 20.26,
        "temp_min": 20.58,
        "temp_max": 20.58,
        "pressure": 1010,
        "sea_level": 1010,
        "grnd_level": 991,
        "humidity": 60,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 8
      },
      "wind": {
        "speed": 0.79,
        "deg": 157,

2025-06-05 17:21:29,130 - wildfire_kg.tools.weather - INFO - API response for Los Angeles: {"cod": "200", "message": 0, "cnt": 40, "list": [{"dt": 1749178800, "main": {"temp": 20.39, "feels_like": 20.26, "temp_min": 19.54, "temp_max": 20.39, "pressure": 1011, "sea_level": 1011, "grnd_level"...
2025-06-05 17:21:29,131 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: 8 forecast entries for Los Angeles on 2025-06-07

Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?basalArea
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:basalArea ?basalArea .
}
LIMIT 50

2025-06-05 17:21:41,851 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:21:41,852 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:21:41,852 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:21:42,258 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: current wind in Bakersfield
2025-06-05 17:21:42,259 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:21:42,259 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'today/current': 2025-06-06
2025-06-05 17:21:42,259 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-06 for query: current wind in Bakersfield
2025-06-05 17:21:42,260 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-06
2025-06-05 17:21:42,260 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 0
2025-06-05 17:21:42,261 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:21:42,261 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-06 00:00:00+00:00
2025-06-05 17:21:42,262 - wildfire_kg.tools.weather - INFO - - Location: Bakersfield
2025-06-05 17:21:42,263 - wildfire_kg.tools.weather - INFO - - Type: Current
2025-06-05 17:21:42,486 - wildfire_kg.tools.weather - INFO - Making current weather API call...
2025-06-05 17:21:42,486 - wildfire_kg.tools.weather - INFO - Calling current endpoint: https://pro.openweathermap.org/data/2.5/weather with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 35.3738712, 'lon': -119.0194639}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/weather
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 35.3738712,
  "lon": -119.0194639
}
Status Code: 200
Response: {
  "coord": {
    "lon": -119.0195,
    "lat": 35.3739
  },
  "weather": [
    {
      "id": 800,
      "main": "Clear",
      "description": "clear sky",
      "icon": "01d"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 34.68,
    "feels_like": 33.2,
    "temp_min": 34.15,
    "temp_max": 36.2,
    "pressure": 1009,
    "humidity": 24,
    "sea_level": 1009,
    "grnd_level": 991
  },
  "visibility": 10000,
  "wind": {
    "speed": 3.13,
    "deg": 344,
    "gust": 5.81
  },
  "clouds": {
    "all": 0
  },
  "dt": 1749169302,
  "sys": {
    "type": 2,
    "id": 2019205,
    "country": "US",
    "sunrise": 1749127284,
    "sunset": 1749179292
  },
  "timezone": -25200,
  "id": 5325738,
  "name": "Bakersfield",
  "cod": 200
}
==================================================

2025-06-05 17:21:42,617 - wildfire_kg.tools.weather - INFO - API response for Bakersfield: {"coord": {"lon": -119.0195, "lat": 35.3739}, "weather": [{"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}], "base": "stations", "main": {"temp": 34.68, "feels_like": 33.2, "tem...
2025-06-05 17:21:47,492 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: importance of defensible space around homes in wildfire-prone areas and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:2d9382dc-13ec-fc15-3ac5-2da246959b29', 'checkpoint_ns': 'tools:2d9382dc-13ec-fc15-3ac5-2da246959b29'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10bb8cfd0>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '2d9382dc-13ec-fc15-3ac5-2da246959b29', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x162ae3d30>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x10b2b9bc0>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10991aa80>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109919080>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109919040>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10b9dded0>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x1099da190>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426c3-bc12-6178-8001-796922baf887'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:2d9382dc-13ec-fc15-3ac5-2da246959b29', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b868c10>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b8e8850>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10bb574c0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10993f1f0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10bb5acf0; to 'PregelExecutableTask' at 0x10b9f6560>, stream=False, retry=None, futures=<weakref at 0x10bb5bb50; to 'FuturesDict' at 0x10bb36150>, schedule_task=<weakref at 0x10bb38580; to 'AsyncPregelLoop' at 0x109611210>, submit=<weakref at 0x10bb386d0; to 'AsyncBackgroundExecutor' at 0x1096d9f10>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:21:47,492 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:21:47,493 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:21:47,725 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:21:47,725 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:21:47,725 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:21:47,764 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:21:47,765 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:21:51,793 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: current wind in Bakersfield
2025-06-05 17:21:51,793 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:21:51,794 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'today/current': 2025-06-06
2025-06-05 17:21:51,794 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-06 for query: current wind in Bakersfield
2025-06-05 17:21:51,794 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-06
2025-06-05 17:21:51,794 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 0
2025-06-05 17:21:51,795 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:21:51,795 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-06 00:00:00+00:00
2025-06-05 17:21:51,795 - wildfire_kg.tools.weather - INFO - - Location: Bakersfield
2025-06-05 17:21:51,795 - wildfire_kg.tools.weather - INFO - - Type: Current
2025-06-05 17:21:51,877 - wildfire_kg.tools.weather - INFO - Making current weather API call...
2025-06-05 17:21:51,879 - wildfire_kg.tools.weather - INFO - Calling current endpoint: https://pro.openweathermap.org/data/2.5/weather with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 35.3738712, 'lon': -119.0194639}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/weather
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 35.3738712,
  "lon": -119.0194639
}
Status Code: 200
Response: {
  "coord": {
    "lon": -119.0195,
    "lat": 35.3739
  },
  "weather": [
    {
      "id": 800,
      "main": "Clear",
      "description": "clear sky",
      "icon": "01d"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 34.68,
    "feels_like": 33.2,
    "temp_min": 34.15,
    "temp_max": 36.2,
    "pressure": 1009,
    "humidity": 24,
    "sea_level": 1009,
    "grnd_level": 991
  },
  "visibility": 10000,
  "wind": {
    "speed": 3.13,
    "deg": 344,
    "gust": 5.81
  },
  "clouds": {
    "all": 0
  },
  "dt": 1749169302,
  "sys": {
    "type": 2,
    "id": 2019205,
    "country": "US",
    "sunrise": 1749127284,
    "sunset": 1749179292
  },
  "timezone": -25200,
  "id": 5325738,
  "name": "Bakersfield",
  "cod": 200
}
==================================================

2025-06-05 17:21:52,008 - wildfire_kg.tools.weather - INFO - API response for Bakersfield: {"coord": {"lon": -119.0195, "lat": 35.3739}, "weather": [{"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}], "base": "stations", "main": {"temp": 34.68, "feels_like": 33.2, "tem...

Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?plotName ?treesN ?shrubsN
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:TreesN ?treesN .
  ?treeShrubMetrics wifire:ShrubsN ?shrubsN .
  BIND("CASBC_0007_20241117_1" AS ?plotName) .
}
LIMIT 50

2025-06-05 17:21:58,512 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the basal area value for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 4, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:a83152ed-bb26-b058-9672-996cbd1b36e3', 'checkpoint_ns': 'tools:a83152ed-bb26-b058-9672-996cbd1b36e3'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x16be02250>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'a83152ed-bb26-b058-9672-996cbd1b36e3', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169e8c7c0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x16be4cc80>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16beeef80>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109673680>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16beedac0>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x1096789d0>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x16b7351d0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426c4-252b-675e-8003-c28931df4df4'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:a83152ed-bb26-b058-9672-996cbd1b36e3', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16bee4ac0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b7dee00>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x16cdd87c0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10993d360>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x16172f150; to 'PregelExecutableTask' at 0x10b9f68c0>, stream=False, retry=None, futures=<weakref at 0x161830e00; to 'FuturesDict' at 0x1099b99d0>, schedule_task=<weakref at 0x16be3a0a0; to 'AsyncPregelLoop' at 0x16bec32d0>, submit=<weakref at 0x16be69fc0; to 'AsyncBackgroundExecutor' at 0x16bec0490>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:21:58,512 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:21:58,513 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:21:58,666 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:21:58,666 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:21:58,666 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:21:58,726 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:21:58,726 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:21:58,726 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:21:58,759 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:21:58,760 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Finished chain.


> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?basalArea
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:basalArea ?basalArea .
}
LIMIT 50

2025-06-05 17:21:59,137 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:21:59,137 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:21:59,138 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:21:59,285 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the leaf area index (LAI) for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:2f99fbe7-ceef-817a-cbdd-0c2de868b187', 'checkpoint_ns': 'tools:2f99fbe7-ceef-817a-cbdd-0c2de868b187'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10905b210>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '2f99fbe7-ceef-817a-cbdd-0c2de868b187', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b7b5d50>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x10b21dc40>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109048880>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109048c40>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109049900>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x109678ed0>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10904a5d0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426c4-2c8d-6c5e-8001-57cec5db5ca0'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:2f99fbe7-ceef-817a-cbdd-0c2de868b187', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10b9c96f0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10b9cac20>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10903a8e0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10b9c93c0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x108675ee0; to 'PregelExecutableTask' at 0x10b9f6cb0>, stream=False, retry=None, futures=<weakref at 0x108676840; to 'FuturesDict' at 0x10bbb6c30>, schedule_task=<weakref at 0x10bb39a10; to 'AsyncPregelLoop' at 0x10904bd90>, submit=<weakref at 0x10bb39c40; to 'AsyncBackgroundExecutor' at 0x109683910>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:21:59,285 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:21:59,286 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl

> Finished chain.

2025-06-05 17:21:59,519 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:21:59,520 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:21:59,520 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:21:59,559 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:21:59,559 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:22:21,522 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the overstory shrub volume (OSvol) for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:2f567c45-1a04-843c-2a0b-d0f02526276f', 'checkpoint_ns': 'tools:2f567c45-1a04-843c-2a0b-d0f02526276f'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x1090eaf50>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '2f567c45-1a04-843c-2a0b-d0f02526276f', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169f20310>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x10bb8cb80>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109042b40>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109043c40>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109043600>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10905a4d0>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x109059910>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426c5-009f-631c-8001-b6e7f944d705'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:2f567c45-1a04-843c-2a0b-d0f02526276f', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109901420>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109902950>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1090a72e0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109901570>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x1090edda0; to 'PregelExecutableTask' at 0x10b9f7400>, stream=False, retry=None, futures=<weakref at 0x1090ee5c0; to 'FuturesDict' at 0x1099b9c10>, schedule_task=<weakref at 0x10bb39310; to 'AsyncPregelLoop' at 0x108f6b910>, submit=<weakref at 0x16be3b990; to 'AsyncBackgroundExecutor' at 0x162ddbbd0>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:22:21,523 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:22:21,524 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:22:21,749 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:22:21,750 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:22:21,750 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:22:21,792 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:22:21,792 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?lai
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:LAI ?lai .
}
LIMIT 50
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?plot ?plotName ?plotCounty ?plotState ?shrubArea ?treeArea ?basalArea
WHERE {
  ?plot a wifire:PlotMetrics .
  ?plot wifire:hasLocationDataPlot ?locationData .
  ?locationData wifire:plotCounty ?plotCounty .
  ?locationData wifire:plotState ?plotState .
  ?plot wifire:plotName ?plotName .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:shrubArea ?shrubArea .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:basalArea ?basalArea .
  FILTER(CONTAINS(LCASE(?plotCounty), LCASE("santa barbara")) || CONTAINS(LCASE(?plotState), LCASE("california")))
}
LIMIT 50

2025-06-05 17:22:37,540 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the components of the fire triangle? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:5f51d0f7-38dc-d7a1-e6de-6f7a861c621e', 'checkpoint_ns': 'tools:5f51d0f7-38dc-d7a1-e6de-6f7a861c621e'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x1097fe850>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '5f51d0f7-38dc-d7a1-e6de-6f7a861c621e', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b8f23e0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109086680>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109087100>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109084a80>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109087700>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x109080b10>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x162d93c10>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426c5-9960-66f0-8001-64a7e491bacf'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:5f51d0f7-38dc-d7a1-e6de-6f7a861c621e', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x108f82110>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x108f801c0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1097dbec0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x108f81030>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x161ca3470; to 'PregelExecutableTask' at 0x10b9f75b0>, stream=False, retry=None, futures=<weakref at 0x1618369d0; to 'FuturesDict' at 0x10905d0d0>, schedule_task=<weakref at 0x10bb3b8b0; to 'AsyncPregelLoop' at 0x1097ebf50>, submit=<weakref at 0x16be3a730; to 'AsyncBackgroundExecutor' at 0x1097f0490>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:22:37,540 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:22:37,540 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:22:37,746 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:22:37,747 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:22:37,747 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:22:37,784 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:22:37,785 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...
2025-06-05 17:22:37,891 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:22:37,892 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:22:37,892 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Entering new OntotextGraphDBQAChain chain...

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?osvol
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegMetrics .
  ?vegMetrics wifire:OSvol ?osvol .
}
LIMIT 50

2025-06-05 17:22:54,004 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:22:54,005 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:22:54,005 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?component ?label
WHERE {
  {
    ?component rdfs:label "Fuel" .
    BIND("Fuel" AS ?label) .
  } UNION {
    ?component rdfs:label "Ignition" .
    BIND("Ignition" AS ?label) .
  } UNION {
    ?component rdfs:label "Oxygen" .
    BIND("Oxygen" AS ?label) .
  }
}
LIMIT 50

2025-06-05 17:22:58,134 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:22:58,135 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:22:58,135 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:23:09,873 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:23:09,873 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:23:09,874 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:23:22,294 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the mean diameter at breast height and mean leaf area index for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:7deba54f-b944-1b85-7b2b-89fe520be7aa', 'checkpoint_ns': 'tools:7deba54f-b944-1b85-7b2b-89fe520be7aa'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x1097dc110>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '7deba54f-b944-1b85-7b2b-89fe520be7aa', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b10c040>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109bec2c0>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1086c5680>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10909ed00>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109bec200>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x109be0690>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x109086190>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426c7-442f-61d4-8001-31298a33859c'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:7deba54f-b944-1b85-7b2b-89fe520be7aa', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b8c5390>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b8c7820>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x109b99bc0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b8c4e20>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10bb59c60; to 'PregelExecutableTask' at 0x10b9f5750>, stream=False, retry=None, futures=<weakref at 0x10bb5af20; to 'FuturesDict' at 0x1097b4350>, schedule_task=<weakref at 0x109b06650; to 'AsyncPregelLoop' at 0x109bc3bd0>, submit=<weakref at 0x109b065e0; to 'AsyncBackgroundExecutor' at 0x109be31d0>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:23:22,294 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:23:22,294 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:23:22,507 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:23:22,508 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:23:22,508 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:23:22,544 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:23:22,545 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:23:33,325 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the slope percentage of CASBC_0011_20240913_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:dd691a9f-e6a5-e47e-bc46-706ddc57acd9', 'checkpoint_ns': 'tools:dd691a9f-e6a5-e47e-bc46-706ddc57acd9'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x109086690>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'dd691a9f-e6a5-e47e-bc46-706ddc57acd9', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16be25f30>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109080300>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109080c80>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109083100>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109082800>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x109058890>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10a016890>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426c7-ad63-6100-8001-ed091a6a3e24'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:dd691a9f-e6a5-e47e-bc46-706ddc57acd9', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10993d390>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10993d510>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10840aac0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10993df90>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x161825260; to 'PregelExecutableTask' at 0x10b9f5000>, stream=False, retry=None, futures=<weakref at 0x161826570; to 'FuturesDict' at 0x16b845730>, schedule_task=<weakref at 0x10bb38c10; to 'AsyncPregelLoop' at 0x109080390>, submit=<weakref at 0x10bb393f0; to 'AsyncBackgroundExecutor' at 0x10bb82d10>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:23:33,326 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:23:33,326 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:23:33,526 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:23:33,527 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:23:33,527 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:23:33,569 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:23:33,569 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?mdbh ?mlai
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:MDBH ?mdbh .
  ?treeShrubMetrics wifire:MLAI ?mlai .
}
LIMIT 50

2025-06-05 17:23:56,659 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the mean shrub area and scaled shrub area for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:38b849a1-feac-d95c-5afe-03308aa22c82', 'checkpoint_ns': 'tools:38b849a1-feac-d95c-5afe-03308aa22c82'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10a015cd0>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '38b849a1-feac-d95c-5afe-03308aa22c82', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169f20310>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x1097bc340>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1097bf980>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x16beb28c0>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x169ea2080>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x162b1a7d0>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x1097184d0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426c8-8beb-6404-8001-bd0902d18960'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:38b849a1-feac-d95c-5afe-03308aa22c82', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10b2a9420>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10b2a9fc0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x16cdda3e0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10b2abca0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10b269ee0; to 'PregelExecutableTask' at 0x10b9f60e0>, stream=False, retry=None, futures=<weakref at 0x10b268ef0; to 'FuturesDict' at 0x1097b7170>, schedule_task=<weakref at 0x10bb398c0; to 'AsyncPregelLoop' at 0x16b8957d0>, submit=<weakref at 0x10bb39230; to 'AsyncBackgroundExecutor' at 0x109719e10>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:23:56,660 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:23:56,660 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:23:56,866 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:23:56,867 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:23:56,867 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:23:56,904 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:23:56,904 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?slopePercentage
WHERE {
  ?plot wifire:plotName "CASBC_0011_20240913_1" .
  ?plot wifire:hasFireBehaviorMetrics ?fireBehaviorMetrics .
  ?fireBehaviorMetrics wifire:LF_SLPD ?slopePercentage .
}
LIMIT 50

2025-06-05 17:23:59,977 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:23:59,978 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:23:59,978 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:24:01,006 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:24:01,006 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:24:01,006 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?meanShrubArea ?scaledShrubArea
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:MeanSA ?meanShrubArea .
  ?treeShrubMetrics wifire:scaledShrubArea ?scaledShrubArea .
}
LIMIT 50

2025-06-05 17:24:33,587 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:24:33,587 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:24:33,587 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:24:36,526 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: current weather in Palm Springs
2025-06-05 17:24:36,527 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:24:36,527 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'today/current': 2025-06-06
2025-06-05 17:24:36,527 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-06 for query: current weather in Palm Springs
2025-06-05 17:24:36,528 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-06
2025-06-05 17:24:36,528 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 0
2025-06-05 17:24:36,528 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:24:36,528 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-06 00:00:00+00:00
2025-06-05 17:24:36,529 - wildfire_kg.tools.weather - INFO - - Location: Palm Springs
2025-06-05 17:24:36,529 - wildfire_kg.tools.weather - INFO - - Type: Current
2025-06-05 17:24:36,754 - wildfire_kg.tools.weather - INFO - Making current weather API call...
2025-06-05 17:24:36,755 - wildfire_kg.tools.weather - INFO - Calling current endpoint: https://pro.openweathermap.org/data/2.5/weather with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 33.8246269, 'lon': -116.540303}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/weather
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 33.8246269,
  "lon": -116.540303
}
Status Code: 200
Response: {
  "coord": {
    "lon": -116.5403,
    "lat": 33.8246
  },
  "weather": [
    {
      "id": 800,
      "main": "Clear",
      "description": "clear sky",
      "icon": "01d"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 36.52,
    "feels_like": 35.76,
    "temp_min": 31.2,
    "temp_max": 37.1,
    "pressure": 1009,
    "humidity": 25,
    "sea_level": 1009,
    "grnd_level": 921
  },
  "visibility": 10000,
  "wind": {
    "speed": 5.66,
    "deg": 310,
    "gust": 11.83
  },
  "clouds": {
    "all": 0
  },
  "dt": 1749169476,
  "sys": {
    "type": 1,
    "id": 5412,
    "country": "US",
    "sunrise": 1749126935,
    "sunset": 1749178451
  },
  "timezone": -25200,
  "id": 5380668,
  "name": "Palm Springs",
  "cod": 200
}
==================================================

2025-06-05 17:24:36,911 - wildfire_kg.tools.weather - INFO - API response for Palm Springs: {"coord": {"lon": -116.5403, "lat": 33.8246}, "weather": [{"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}], "base": "stations", "main": {"temp": 36.52, "feels_like": 35.76, "te...
2025-06-05 17:24:46,589 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the green cover volume for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:296ada8a-5045-2dc2-2dd8-bc8ee7977e9e', 'checkpoint_ns': 'tools:296ada8a-5045-2dc2-2dd8-bc8ee7977e9e'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x108649610>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '296ada8a-5045-2dc2-2dd8-bc8ee7977e9e', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16be247c0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x108f4b740>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108f4bb00>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108f48b80>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108f49b00>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x1097be210>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x109bef0d0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426ca-6815-6cee-8001-a93d56f7f9ab'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:296ada8a-5045-2dc2-2dd8-bc8ee7977e9e', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109b90eb0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109b92740>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x16be5afc0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109b90490>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x1097f54e0; to 'PregelExecutableTask' at 0x10b9f7eb0>, stream=False, retry=None, futures=<weakref at 0x1097f4d10; to 'FuturesDict' at 0x1097b5bb0>, schedule_task=<weakref at 0x10b9fb4c0; to 'AsyncPregelLoop' at 0x108f49450>, submit=<weakref at 0x10b9fbd80; to 'AsyncBackgroundExecutor' at 0x109080850>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:24:46,590 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:24:46,590 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:24:46,594 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: current weather in Palm Springs
2025-06-05 17:24:46,594 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:24:46,594 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'today/current': 2025-06-06
2025-06-05 17:24:46,594 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-06 for query: current weather in Palm Springs
2025-06-05 17:24:46,595 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-06
2025-06-05 17:24:46,595 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 0
2025-06-05 17:24:46,595 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:24:46,596 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-06 00:00:00+00:00
2025-06-05 17:24:46,596 - wildfire_kg.tools.weather - INFO - - Location: Palm Springs
2025-06-05 17:24:46,596 - wildfire_kg.tools.weather - INFO - - Type: Current
2025-06-05 17:24:46,678 - wildfire_kg.tools.weather - INFO - Making current weather API call...
2025-06-05 17:24:46,679 - wildfire_kg.tools.weather - INFO - Calling current endpoint: https://pro.openweathermap.org/data/2.5/weather with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 33.8246269, 'lon': -116.540303}
2025-06-05 17:24:46,793 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:24:46,793 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:24:46,794 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/weather
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 33.8246269,
  "lon": -116.540303
}
Status Code: 200
Response: {
  "coord": {
    "lon": -116.5403,
    "lat": 33.8246
  },
  "weather": [
    {
      "id": 800,
      "main": "Clear",
      "description": "clear sky",
      "icon": "01d"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 36.52,
    "feels_like": 35.76,
    "temp_min": 31.2,
    "temp_max": 37.1,
    "pressure": 1009,
    "humidity": 25,
    "sea_level": 1009,
    "grnd_level": 921
  },
  "visibility": 10000,
  "wind": {
    "speed": 5.66,
    "deg": 310,
    "gust": 11.83
  },
  "clouds": {
    "all": 0
  },
  "dt": 1749169476,
  "sys": {
    "type": 1,
    "id": 5412,
    "country": "US",
    "sunrise": 1749126935,
    "sunset": 1749178451
  },
  "timezone": -25200,
  "id": 5380668,
  "name": "Palm Springs",
  "cod": 200
}
==================================================

2025-06-05 17:24:46,803 - wildfire_kg.tools.weather - INFO - API response for Palm Springs: {"coord": {"lon": -116.5403, "lat": 33.8246}, "weather": [{"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}], "base": "stations", "main": {"temp": 36.52, "feels_like": 35.76, "te...
2025-06-05 17:24:46,834 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:24:46,834 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?greenCoverVolume
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:GCvol ?greenCoverVolume .
}
LIMIT 50

2025-06-05 17:25:12,545 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the shrub height and its standard deviation for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:c35193d1-06ff-5038-05d9-bb19a972e097', 'checkpoint_ns': 'tools:c35193d1-06ff-5038-05d9-bb19a972e097'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x16cdc9690>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'c35193d1-06ff-5038-05d9-bb19a972e097', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b8f17b0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109681200>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b7340>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b4e80>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b6d00>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10a017650>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10bb6f110>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426cb-5f9c-6968-8001-9a874da5d687'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:c35193d1-06ff-5038-05d9-bb19a972e097', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1096841f0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109687610>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1084c1a80>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109685000>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x109044f40; to 'PregelExecutableTask' at 0x16be99fc0>, stream=False, retry=None, futures=<weakref at 0x109046ac0; to 'FuturesDict' at 0x1097b6330>, schedule_task=<weakref at 0x16be38eb0; to 'AsyncPregelLoop' at 0x10962ba50>, submit=<weakref at 0x10bb39700; to 'AsyncBackgroundExecutor' at 0x109992410>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:25:12,546 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:25:12,546 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:25:12,770 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:25:12,770 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:25:12,770 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:25:12,810 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:25:12,811 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:25:13,342 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:25:13,343 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:25:13,344 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:25:19,374 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the disturbance status for CASBC_0011_20240913_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:cd05498d-6880-65a9-d506-e89ea8d93703', 'checkpoint_ns': 'tools:cd05498d-6880-65a9-d506-e89ea8d93703'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10992e550>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'cd05498d-6880-65a9-d506-e89ea8d93703', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16be046d0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x16b114c00>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b2b9a40>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b2b8800>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b2baa40>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10964dc90>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10b296ed0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426cb-a0be-66ee-8001-159498905562'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:cd05498d-6880-65a9-d506-e89ea8d93703', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109903fd0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109902920>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x109623240>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109900d00>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x1097f65c0; to 'PregelExecutableTask' at 0x16be9a170>, stream=False, retry=None, futures=<weakref at 0x1097f59e0; to 'FuturesDict' at 0x1086568d0>, schedule_task=<weakref at 0x16be3a650; to 'AsyncPregelLoop' at 0x10b2966d0>, submit=<weakref at 0x16be38f20; to 'AsyncBackgroundExecutor' at 0x1097df450>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:25:19,375 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:25:19,375 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:25:19,597 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:25:19,598 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:25:19,598 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:25:19,641 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:25:19,641 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:25:27,527 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the aspect value of CASBC_0011_20240913_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:32dcee48-636e-db62-6710-4accd4167f85', 'checkpoint_ns': 'tools:32dcee48-636e-db62-6710-4accd4167f85'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x109b97710>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '32dcee48-636e-db62-6710-4accd4167f85', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169f226b0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x108fb2980>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108fb2900>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108fb1600>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x108fb2580>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x1096d9050>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x108f85090>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426cb-ee7f-6fc2-8001-4196710fc7b6'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:32dcee48-636e-db62-6710-4accd4167f85', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1096552d0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109684e20>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x109b9a2a0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109686a10>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10b9eede0; to 'PregelExecutableTask' at 0x10b9f5360>, stream=False, retry=None, futures=<weakref at 0x10b9ef150; to 'FuturesDict' at 0x16b847470>, schedule_task=<weakref at 0x16be69000; to 'AsyncPregelLoop' at 0x109941bd0>, submit=<weakref at 0x16be6ae30; to 'AsyncBackgroundExecutor' at 0x109082410>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:25:27,527 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:25:27,528 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:25:27,753 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:25:27,753 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:25:27,754 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:25:27,796 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:25:27,796 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?disturbanceStatus
WHERE {
  ?plot wifire:plotName "CASBC_0011_20240913_1" .
  ?plot wifire:hasFireBehaviorMetrics ?fireBehaviorMetrics .
  ?fireBehaviorMetrics wifire:LF_EVC ?disturbanceStatus .
}
LIMIT 50
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?shrubHeight ?stdDevShrubHeight
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:SDHT ?shrubHeight .
  ?treeShrubMetrics wifire:SDSHT ?stdDevShrubHeight .
}
LIMIT 50

2025-06-05 17:25:57,802 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: How many trees are in CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:16feb8de-bd8f-6a45-3511-0a938907fcd4', 'checkpoint_ns': 'tools:16feb8de-bd8f-6a45-3511-0a938907fcd4'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10bb801d0>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '16feb8de-bd8f-6a45-3511-0a938907fcd4', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16be05f30>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109728d00>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1099cff40>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1099ce080>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1099cfdc0>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10b2b65d0>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x109744ed0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426cd-0f38-6d26-8001-434567ec7dba'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:16feb8de-bd8f-6a45-3511-0a938907fcd4', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10b211bd0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10b212410>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x16bee28e0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10b213be0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x161ca1210; to 'PregelExecutableTask' at 0x10b9f6320>, stream=False, retry=None, futures=<weakref at 0x162a193f0; to 'FuturesDict' at 0x109605c10>, schedule_task=<weakref at 0x16be682e0; to 'AsyncPregelLoop' at 0x1099f9910>, submit=<weakref at 0x10b9fb5a0; to 'AsyncBackgroundExecutor' at 0x1096104d0>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:25:57,803 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:25:57,804 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:25:58,031 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:25:58,031 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:25:58,032 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:25:58,085 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:25:58,086 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?aspect
WHERE {
  ?plot wifire:plotName "CASBC_0011_20240913_1" .
  ?plot wifire:hasFireBehaviorMetrics ?fireBehaviorMetrics .
  ?fireBehaviorMetrics wifire:LF_ASP ?aspect .
}
LIMIT 50


> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:25:58,466 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:25:58,467 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:25:58,467 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:26:02,227 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:26:02,227 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:26:02,228 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:26:02,953 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:26:02,954 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:26:02,955 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:26:13,938 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the average Shrub Cover for similar plots in the surrounding region? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 4, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:d8015b23-365d-a6ad-b461-3ff90c975e25', 'checkpoint_ns': 'tools:d8015b23-365d-a6ad-b461-3ff90c975e25'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x16b51aa90>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'd8015b23-365d-a6ad-b461-3ff90c975e25', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16be046d0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x16b114c00>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b2b9a40>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b2b8800>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b2baa40>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10964dc90>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10b296ed0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426cd-a91e-6170-8003-f99ded869ba8'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:d8015b23-365d-a6ad-b461-3ff90c975e25', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10b9c8a00>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b8532e0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x109b15580>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b851ae0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x1097f5df0; to 'PregelExecutableTask' at 0x16be99fc0>, stream=False, retry=None, futures=<weakref at 0x1097f65c0; to 'FuturesDict' at 0x10970f530>, schedule_task=<weakref at 0x16be3a650; to 'AsyncPregelLoop' at 0x10b2966d0>, submit=<weakref at 0x16be38f20; to 'AsyncBackgroundExecutor' at 0x1097df450>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:26:13,939 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:26:13,939 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:26:14,158 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:26:14,158 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:26:14,159 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:26:14,199 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:26:14,199 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:26:25,847 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the shrub height and its standard deviation for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 4, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:50736ea1-8933-4b13-9919-e2b02da82ad2', 'checkpoint_ns': 'tools:50736ea1-8933-4b13-9919-e2b02da82ad2'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10909c650>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '50736ea1-8933-4b13-9919-e2b02da82ad2', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b8f32e0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109681200>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b7340>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b4e80>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b6d00>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10a017650>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10bb6f110>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426ce-1aad-6ff2-8003-0ef15742cbe0'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:50736ea1-8933-4b13-9919-e2b02da82ad2', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109634670>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109634c10>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x16cddbd80>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109634790>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x1090ecdb0; to 'PregelExecutableTask' at 0x10b98b010>, stream=False, retry=None, futures=<weakref at 0x1090ef010; to 'FuturesDict' at 0x1090e16d0>, schedule_task=<weakref at 0x16be38eb0; to 'AsyncPregelLoop' at 0x10962ba50>, submit=<weakref at 0x10bb39700; to 'AsyncBackgroundExecutor' at 0x109992410>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:26:25,847 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:26:25,847 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:26:26,050 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:26:26,050 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:26:26,050 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:26:26,083 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:26:26,084 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?shrubHeight ?stdDevShrubHeight
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:SDHT ?shrubHeight .
  ?treeShrubMetrics wifire:SDSHT ?stdDevShrubHeight .
}
LIMIT 50

2025-06-05 17:26:26,448 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:26:26,448 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:26:26,449 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?treeCount
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:TreesN ?treeCount .
}
LIMIT 50

2025-06-05 17:26:37,597 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:26:37,598 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:26:37,598 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:26:37,931 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the shrub height and its standard deviation for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 6, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:ece62ec9-ecf0-8b03-a662-56f333eeaa29', 'checkpoint_ns': 'tools:ece62ec9-ecf0-8b03-a662-56f333eeaa29'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x108ff8250>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'ece62ec9-ecf0-8b03-a662-56f333eeaa29', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16be275b0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109681200>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b7340>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b4e80>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b6d00>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10a017650>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10bb6f110>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426ce-8deb-6690-8005-4d7f85862058'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:ece62ec9-ecf0-8b03-a662-56f333eeaa29', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16be31a20>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16be32620>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1097daa20>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16be31510>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x1097362f0; to 'PregelExecutableTask' at 0x1614ba440>, stream=False, retry=None, futures=<weakref at 0x1097c2430; to 'FuturesDict' at 0x10bbe93d0>, schedule_task=<weakref at 0x16be38eb0; to 'AsyncPregelLoop' at 0x10962ba50>, submit=<weakref at 0x10bb39700; to 'AsyncBackgroundExecutor' at 0x109992410>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:26:37,932 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:26:37,932 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:26:38,154 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:26:38,155 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:26:38,155 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:26:38,195 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:26:38,196 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?shrubHeight ?stdDevShrubHeight
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:SDHT ?shrubHeight .
  ?treeShrubMetrics wifire:SDSHT ?stdDevShrubHeight .
}
LIMIT 50

2025-06-05 17:26:38,567 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:26:38,568 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:26:38,568 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:26:47,506 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: current weather in Escondido, CA
2025-06-05 17:26:47,507 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:26:47,507 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'today/current': 2025-06-06
2025-06-05 17:26:47,507 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-06 for query: current weather in Escondido, CA
2025-06-05 17:26:47,508 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-06
2025-06-05 17:26:47,508 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 0
2025-06-05 17:26:47,508 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:26:47,509 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-06 00:00:00+00:00
2025-06-05 17:26:47,509 - wildfire_kg.tools.weather - INFO - - Location: Escondido, CA
2025-06-05 17:26:47,510 - wildfire_kg.tools.weather - INFO - - Type: Current
2025-06-05 17:26:47,996 - wildfire_kg.tools.weather - INFO - Making current weather API call...
2025-06-05 17:26:47,998 - wildfire_kg.tools.weather - INFO - Calling current endpoint: https://pro.openweathermap.org/data/2.5/weather with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 33.1216751, 'lon': -117.0814849}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/weather
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 33.1216751,
  "lon": -117.0814849
}
Status Code: 200
Response: {
  "coord": {
    "lon": -117.0815,
    "lat": 33.1217
  },
  "weather": [
    {
      "id": 804,
      "main": "Clouds",
      "description": "overcast clouds",
      "icon": "04d"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 18.48,
    "feels_like": 18.45,
    "temp_min": 16.74,
    "temp_max": 19.99,
    "pressure": 1012,
    "humidity": 79,
    "sea_level": 1012,
    "grnd_level": 983
  },
  "visibility": 10000,
  "wind": {
    "speed": 2.68,
    "deg": 260
  },
  "clouds": {
    "all": 100
  },
  "dt": 1749169608,
  "sys": {
    "type": 2,
    "id": 2005618,
    "country": "US",
    "sunrise": 1749127172,
    "sunset": 1749178473
  },
  "timezone": -25200,
  "id": 5346827,
  "name": "Escondido",
  "cod": 200
}
==================================================

2025-06-05 17:26:48,142 - wildfire_kg.tools.weather - INFO - API response for Escondido: {"coord": {"lon": -117.0815, "lat": 33.1217}, "weather": [{"id": 804, "main": "Clouds", "description": "overcast clouds", "icon": "04d"}], "base": "stations", "main": {"temp": 18.48, "feels_like": 18....
2025-06-05 17:26:49,760 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the shrub height and its standard deviation for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 8, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:90bf7716-6db4-76a8-30cc-7758ebe32f9a', 'checkpoint_ns': 'tools:90bf7716-6db4-76a8-30cc-7758ebe32f9a'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x109b60d90>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '90bf7716-6db4-76a8-30cc-7758ebe32f9a', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b12dc60>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109681200>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b7340>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b4e80>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b6d00>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10a017650>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10bb6f110>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426ce-febc-6d9c-8007-940cead10ff8'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:90bf7716-6db4-76a8-30cc-7758ebe32f9a', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16cd1b0a0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16cd1a380>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1084c1800>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16cd18bb0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10bbc0f40; to 'PregelExecutableTask' at 0x16b7b9360>, stream=False, retry=None, futures=<weakref at 0x10bbc0400; to 'FuturesDict' at 0x1099b8170>, schedule_task=<weakref at 0x16be38eb0; to 'AsyncPregelLoop' at 0x10962ba50>, submit=<weakref at 0x10bb39700; to 'AsyncBackgroundExecutor' at 0x109992410>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:26:49,760 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:26:49,761 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:26:49,981 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:26:49,982 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:26:49,982 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:26:50,027 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:26:50,027 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?shrubHeight ?stdDevShrubHeight
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:SDHT ?shrubHeight .
  ?treeShrubMetrics wifire:SDSHT ?stdDevShrubHeight .
}
LIMIT 50

2025-06-05 17:26:50,454 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:26:50,455 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:26:50,455 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:26:52,977 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: current weather in Escondido, CA
2025-06-05 17:26:52,978 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:26:52,978 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'today/current': 2025-06-06
2025-06-05 17:26:52,979 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-06 for query: current weather in Escondido, CA
2025-06-05 17:26:52,979 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-06
2025-06-05 17:26:52,979 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 0
2025-06-05 17:26:52,980 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:26:52,980 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-06 00:00:00+00:00
2025-06-05 17:26:52,981 - wildfire_kg.tools.weather - INFO - - Location: Escondido, CA
2025-06-05 17:26:52,981 - wildfire_kg.tools.weather - INFO - - Type: Current
2025-06-05 17:26:53,149 - wildfire_kg.tools.weather - INFO - Making current weather API call...
2025-06-05 17:26:53,150 - wildfire_kg.tools.weather - INFO - Calling current endpoint: https://pro.openweathermap.org/data/2.5/weather with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 33.1216751, 'lon': -117.0814849}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/weather
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 33.1216751,
  "lon": -117.0814849
}
Status Code: 200
Response: {
  "coord": {
    "lon": -117.0815,
    "lat": 33.1217
  },
  "weather": [
    {
      "id": 804,
      "main": "Clouds",
      "description": "overcast clouds",
      "icon": "04d"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 18.48,
    "feels_like": 18.45,
    "temp_min": 16.74,
    "temp_max": 19.99,
    "pressure": 1012,
    "humidity": 79,
    "sea_level": 1012,
    "grnd_level": 983
  },
  "visibility": 10000,
  "wind": {
    "speed": 2.68,
    "deg": 260
  },
  "clouds": {
    "all": 100
  },
  "dt": 1749169608,
  "sys": {
    "type": 2,
    "id": 2005618,
    "country": "US",
    "sunrise": 1749127172,
    "sunset": 1749178473
  },
  "timezone": -25200,
  "id": 5346827,
  "name": "Escondido",
  "cod": 200
}
==================================================

2025-06-05 17:26:53,277 - wildfire_kg.tools.weather - INFO - API response for Escondido: {"coord": {"lon": -117.0815, "lat": 33.1217}, "weather": [{"id": 804, "main": "Clouds", "description": "overcast clouds", "icon": "04d"}], "base": "stations", "main": {"temp": 18.48, "feels_like": 18....

Invalid SPARQL query:
```sparql
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?plotName (AVG(?shrubArea) AS ?avgShrubArea)
WHERE {
    ?plot wifire:hasVegetationMetrics ?vegMetrics .
    ?vegMetrics wifire:GCvol ?shrubArea .
    ?plot wifire:hasLocationDataPlot ?locationData .
    ?locationData wifire:plotCounty ?county .
    ?plot wifire:plotName ?plotName .
    FILTER(CONTAINS(LCASE(?county), LCASE("santa barbara")))
}
GROUP BY ?plotName
LIMIT 50
```
SPARQL Query Parse Error:
Expected {SelectQuery | ConstructQuery | DescribeQuery | AskQuery}, found '`'  (at char 0), (line:1, col:1)

2025-06-05 17:27:02,763 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the shrub height and its standard deviation for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 10, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:a26f02e6-4c34-2424-d92a-5da64705e224', 'checkpoint_ns': 'tools:a26f02e6-4c34-2424-d92a-5da64705e224'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10bb02150>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'a26f02e6-4c34-2424-d92a-5da64705e224', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b12f880>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109681200>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b7340>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b4e80>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b6d00>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10a017650>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10bb6f110>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426cf-7abe-6800-8009-25529eddb22d'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:a26f02e6-4c34-2424-d92a-5da64705e224', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16bee7fa0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16bee6dd0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1090a4d60>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16bee74f0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10bbc2110; to 'PregelExecutableTask' at 0x10b9f7d90>, stream=False, retry=None, futures=<weakref at 0x10bbc3650; to 'FuturesDict' at 0x10a005550>, schedule_task=<weakref at 0x16be38eb0; to 'AsyncPregelLoop' at 0x10962ba50>, submit=<weakref at 0x10bb39700; to 'AsyncBackgroundExecutor' at 0x109992410>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:27:02,764 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:27:02,764 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:27:02,969 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:27:02,969 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:27:02,969 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:27:03,001 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:27:03,002 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:27:10,326 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What type of tree shrub metrics are available for the plots? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:598f96c5-f892-cb49-1686-306ab955324d', 'checkpoint_ns': 'tools:598f96c5-f892-cb49-1686-306ab955324d'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x1097e8810>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '598f96c5-f892-cb49-1686-306ab955324d', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169e8c220>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x10a044600>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10a044640>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10a044700>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10a044740>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10904f350>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x109747910>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426cf-c2dd-632a-8001-0aada94d7ea1'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:598f96c5-f892-cb49-1686-306ab955324d', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109920700>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109920760>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1090bf880>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109923070>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10bb58a40; to 'PregelExecutableTask' at 0x16b7ba5f0>, stream=False, retry=None, futures=<weakref at 0x10bbbff10; to 'FuturesDict' at 0x10a007cb0>, schedule_task=<weakref at 0x109b04e40; to 'AsyncPregelLoop' at 0x108f63250>, submit=<weakref at 0x10bb399a0; to 'AsyncBackgroundExecutor' at 0x10a061a90>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:27:10,327 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:27:10,328 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:27:10,555 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:27:10,556 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:27:10,556 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:27:10,593 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:27:10,593 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:27:28,466 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the canopy base height and canopy bulk density for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:c5df1b3d-6812-28b4-3388-eb1160cc6c27', 'checkpoint_ns': 'tools:c5df1b3d-6812-28b4-3388-eb1160cc6c27'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10a0c7210>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'c5df1b3d-6812-28b4-3388-eb1160cc6c27', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b7b7c40>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x16be34580>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109b2ef40>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109b2f340>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x109b2f380>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x1097ff090>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x109b2ee10>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426d0-6fdb-6c20-8001-04a52127619e'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:c5df1b3d-6812-28b4-3388-eb1160cc6c27', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16cd1aec0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1099b0eb0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10b9bccc0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10b213be0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x1097f54e0; to 'PregelExecutableTask' at 0x109b81360>, stream=False, retry=None, futures=<weakref at 0x1097f4ef0; to 'FuturesDict' at 0x109033bf0>, schedule_task=<weakref at 0x109b07220; to 'AsyncPregelLoop' at 0x109b2ea10>, submit=<weakref at 0x109b049e0; to 'AsyncBackgroundExecutor' at 0x109b2eb90>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:27:28,467 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:27:28,467 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:27:28,691 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:27:28,691 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:27:28,692 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:27:28,730 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:27:28,731 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?shrubHeight ?stdDevShrubHeight
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:SDHT ?shrubHeight .
  ?treeShrubMetrics wifire:SDSHT ?stdDevShrubHeight .
}
LIMIT 50
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?plotName (AVG(?shrubArea) AS ?avgShrubArea)
WHERE {
    ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
    ?treeShrubMetrics wifire:shrubArea ?shrubArea .
    ?plot wifire:hasLocationDataPlot ?locationData .
    ?locationData wifire:plotCounty ?county .
    ?plot wifire:plotName ?plotName .
    FILTER(CONTAINS(LCASE(?county), LCASE("santa barbara")))
}
GROUP BY ?plotName
LIMIT 50

2025-06-05 17:27:44,571 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:27:44,571 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:27:44,572 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?cbh ?cbd
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:CBH ?cbh .
  ?treeShrubMetrics wifire:LF_CBD ?cbd .
}
LIMIT 50

2025-06-05 17:27:57,694 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:27:57,695 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:27:57,695 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:28:11,074 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the shrub height and its standard deviation for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 12, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:e538759c-0d8a-3a2f-19e4-09c8ec74859d', 'checkpoint_ns': 'tools:e538759c-0d8a-3a2f-19e4-09c8ec74859d'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10a0d1990>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'e538759c-0d8a-3a2f-19e4-09c8ec74859d', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169f226b0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109681200>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b7340>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b4e80>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b6d00>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10a017650>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10bb6f110>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426d2-0633-6064-800b-567784e8191c'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:e538759c-0d8a-3a2f-19e4-09c8ec74859d', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16bee7fa0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16bee6dd0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1090a4d60>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b868bb0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x1097c3b50; to 'PregelExecutableTask' at 0x109b80820>, stream=False, retry=None, futures=<weakref at 0x1097c3d80; to 'FuturesDict' at 0x10a004a10>, schedule_task=<weakref at 0x16be38eb0; to 'AsyncPregelLoop' at 0x10962ba50>, submit=<weakref at 0x10bb39700; to 'AsyncBackgroundExecutor' at 0x109992410>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:28:11,075 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:28:11,076 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:28:11,296 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:28:11,297 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:28:11,297 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:28:11,340 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:28:11,340 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?shrubHeight ?stdDevShrubHeight
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:SDHT ?shrubHeight .
  ?treeShrubMetrics wifire:SDSHT ?stdDevShrubHeight .
}
LIMIT 50

2025-06-05 17:28:11,741 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:28:11,742 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:28:11,743 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:28:18,222 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the shrub height and its standard deviation for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 14, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:0a401abe-9e4c-5920-3d9c-948f33503984', 'checkpoint_ns': 'tools:0a401abe-9e4c-5920-3d9c-948f33503984'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x1097ebf50>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '0a401abe-9e4c-5920-3d9c-948f33503984', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169f226b0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109681200>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b7340>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b4e80>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b6d00>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10a017650>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10bb6f110>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426d2-4a5e-6f22-800d-a3df105ba404'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:0a401abe-9e4c-5920-3d9c-948f33503984', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16bee7fa0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16bee4df0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10bc44220>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16bee6dd0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10a71c630; to 'PregelExecutableTask' at 0x109b80820>, stream=False, retry=None, futures=<weakref at 0x10a71d530; to 'FuturesDict' at 0x10a0071d0>, schedule_task=<weakref at 0x16be38eb0; to 'AsyncPregelLoop' at 0x10962ba50>, submit=<weakref at 0x10bb39700; to 'AsyncBackgroundExecutor' at 0x109992410>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:28:18,223 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:28:18,224 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:28:18,436 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:28:18,437 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:28:18,437 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:28:18,473 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:28:18,473 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?shrubHeight ?stdDevShrubHeight
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:SDHT ?shrubHeight .
  ?treeShrubMetrics wifire:SDSHT ?stdDevShrubHeight .
}
LIMIT 50

2025-06-05 17:28:18,845 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:28:18,845 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:28:18,846 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:28:21,170 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:28:21,170 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:28:21,171 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:28:28,742 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the shrub height and its standard deviation for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 16, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:40c8537e-b33c-0b8b-a18e-9c0b76c121ee', 'checkpoint_ns': 'tools:40c8537e-b33c-0b8b-a18e-9c0b76c121ee'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10a727c90>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '40c8537e-b33c-0b8b-a18e-9c0b76c121ee', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b12d990>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109681200>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b7340>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b4e80>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b6d00>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10a017650>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10bb6f110>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426d2-aeb1-68da-800f-d63929c57591'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:40c8537e-b33c-0b8b-a18e-9c0b76c121ee', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1097fbf40>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10a792b00>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10bc440e0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10bcbb3a0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x108f42a70; to 'PregelExecutableTask' at 0x109b80820>, stream=False, retry=None, futures=<weakref at 0x10a71fe70; to 'FuturesDict' at 0x10a007e30>, schedule_task=<weakref at 0x16be38eb0; to 'AsyncPregelLoop' at 0x10962ba50>, submit=<weakref at 0x10bb39700; to 'AsyncBackgroundExecutor' at 0x109992410>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:28:28,743 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:28:28,743 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:28:28,964 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:28:28,964 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:28:28,965 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:28:29,003 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:28:29,003 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?shrubHeight ?stdDevShrubHeight
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:SDHT ?shrubHeight .
  ?treeShrubMetrics wifire:SDSHT ?stdDevShrubHeight .
}
LIMIT 50

2025-06-05 17:28:29,398 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:28:29,399 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:28:29,400 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:28:34,271 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the shrub height and its standard deviation for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 18, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:d89f4b14-b6e6-fab0-0d15-6a1bfe440773', 'checkpoint_ns': 'tools:d89f4b14-b6e6-fab0-0d15-6a1bfe440773'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10bd28a90>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'd89f4b14-b6e6-fab0-0d15-6a1bfe440773', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x10a0214e0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109681200>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b7340>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b4e80>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b6d00>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10a017650>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10bb6f110>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426d2-e36d-66a0-8011-0e4681d991fe'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:d89f4b14-b6e6-fab0-0d15-6a1bfe440773', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10bce47c0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10bce7520>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10bd062a0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10bce6f20>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10bc9c130; to 'PregelExecutableTask' at 0x109b82ef0>, stream=False, retry=None, futures=<weakref at 0x10bc9d8a0; to 'FuturesDict' at 0x10a007d70>, schedule_task=<weakref at 0x16be38eb0; to 'AsyncPregelLoop' at 0x10962ba50>, submit=<weakref at 0x10bb39700; to 'AsyncBackgroundExecutor' at 0x109992410>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:28:34,272 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:28:34,273 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:28:34,648 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:28:34,648 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:28:34,649 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:28:34,681 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:28:34,681 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?shrubHeight ?stdDevShrubHeight
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:SDHT ?shrubHeight .
  ?treeShrubMetrics wifire:SDSHT ?stdDevShrubHeight .
}
LIMIT 50

2025-06-05 17:28:35,052 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:28:35,052 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:28:35,053 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:28:41,481 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: How does the average Shrub Cover in the surrounding region vary by season or over the course of a year? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 6, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:550a775e-c6f5-b6cb-55f6-8205a471cd1c', 'checkpoint_ns': 'tools:550a775e-c6f5-b6cb-55f6-8205a471cd1c'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10a0ac050>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '550a775e-c6f5-b6cb-55f6-8205a471cd1c', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b8f23e0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x16b114c00>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b2b9a40>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b2b8800>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b2baa40>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10964dc90>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10b296ed0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426d3-282f-6a0e-8005-1056a6d4002b'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:550a775e-c6f5-b6cb-55f6-8205a471cd1c', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1084ddd50>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1084dfac0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10bd65f80>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1084dc4c0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x1096bb100; to 'PregelExecutableTask' at 0x16b7bb640>, stream=False, retry=None, futures=<weakref at 0x1096b99e0; to 'FuturesDict' at 0x1097c50d0>, schedule_task=<weakref at 0x16be3a650; to 'AsyncPregelLoop' at 0x10b2966d0>, submit=<weakref at 0x16be38f20; to 'AsyncBackgroundExecutor' at 0x1097df450>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:28:41,482 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:28:41,482 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:28:41,705 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:28:41,705 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:28:41,705 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:28:41,744 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:28:41,744 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:28:48,391 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the understory shrub volume (USvol) for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:5ba000d6-f950-043a-29ce-da76e1972106', 'checkpoint_ns': 'tools:5ba000d6-f950-043a-29ce-da76e1972106'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10975c310>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '5ba000d6-f950-043a-29ce-da76e1972106', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b8f04f0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x10bd4d000>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10bd4cfc0>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10bd4d0c0>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10bd4d100>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x108f01150>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x1084b3b90>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426d3-6a15-650e-8001-183a14a6b586'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:5ba000d6-f950-043a-29ce-da76e1972106', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10bd19780>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10bd19ba0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x16cd71300>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16cd18850>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x161ca0220; to 'PregelExecutableTask' at 0x16b7b9120>, stream=False, retry=None, futures=<weakref at 0x161ca3b50; to 'FuturesDict' at 0x10bc37230>, schedule_task=<weakref at 0x10a785ee0; to 'AsyncPregelLoop' at 0x10a725050>, submit=<weakref at 0x10a785e70; to 'AsyncBackgroundExecutor' at 0x10bcc3090>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:28:48,392 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:28:48,392 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the shrub height and its standard deviation for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 20, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:da29f5f2-faf2-d8a2-1a94-18e657d029a1', 'checkpoint_ns': 'tools:da29f5f2-faf2-d8a2-1a94-18e657d029a1'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10bd47f50>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'da29f5f2-faf2-d8a2-1a94-18e657d029a1', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b8f06d0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109681200>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b7340>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b4e80>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b6d00>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10a017650>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10bb6f110>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426d3-6a16-6882-8013-159a6c4ece17'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:da29f5f2-faf2-d8a2-1a94-18e657d029a1', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16cd196f0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1084bf4f0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10bc06d40>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10bd191b0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x162ab4d10; to 'PregelExecutableTask' at 0x16b7bbb50>, stream=False, retry=None, futures=<weakref at 0x162ab5580; to 'FuturesDict' at 0x10bbf5310>, schedule_task=<weakref at 0x16be38eb0; to 'AsyncPregelLoop' at 0x10962ba50>, submit=<weakref at 0x10bb39700; to 'AsyncBackgroundExecutor' at 0x109992410>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:28:48,393 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:28:48,393 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:28:48,393 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:28:48,648 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:28:48,649 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:28:48,649 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:28:48,649 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:28:48,650 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:28:48,650 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:28:48,705 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:28:48,706 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...
2025-06-05 17:28:48,706 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:28:48,710 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...


> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?usvol
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegMetrics .
  ?vegMetrics wifire:USvol ?usvol .
}
LIMIT 50

2025-06-05 17:29:25,237 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:29:25,238 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:29:25,239 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?shrubHeight ?stdDevShrubHeight
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:SDHT ?shrubHeight .
  ?treeShrubMetrics wifire:SDSHT ?stdDevShrubHeight .
}
LIMIT 50

> Finished chain.

2025-06-05 17:29:32,329 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:29:32,330 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:29:32,331 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:29:42,111 - wildfire_kg.tools.kg - ERROR - Error querying knowledge graph: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
Traceback (most recent call last):
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/kg_tool.py", line 124, in query_knowledge_graph
    result = qa_chain.invoke({qa_chain.input_key: query})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 167, in invoke
    raise e
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 157, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain_community/chains/graph_qa/ontotext_graphdb.py", line 127, in _call
    sparql_generation_chain_result = self.sparql_generation_chain.invoke(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 167, in invoke
    raise e
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 157, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain/chains/llm.py", line 127, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain/chains/llm.py", line 139, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 947, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 766, in generate
    self._generate_with_cache(
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 1012, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 800, in _generate
    response = self.client.create(**payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1296, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/openai/_base_client.py", line 973, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1062, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1111, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1062, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1111, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1077, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
2025-06-05 17:29:56,509 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What type of tree shrub metrics are available for the plots? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 4, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:56054389-469e-4462-f3d5-75df932712c6', 'checkpoint_ns': 'tools:56054389-469e-4462-f3d5-75df932712c6'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10a74d590>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '56054389-469e-4462-f3d5-75df932712c6', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169e8c220>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x10a044600>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10a044640>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10a044700>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10a044740>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10904f350>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x109747910>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426d5-f3b4-61b4-8003-5c8492623b8c'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:56054389-469e-4462-f3d5-75df932712c6', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10a7906a0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10a7906d0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1090bf880>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10a7924d0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x1096e8b80; to 'PregelExecutableTask' at 0x16be9bac0>, stream=False, retry=None, futures=<weakref at 0x1096eac00; to 'FuturesDict' at 0x10bc48350>, schedule_task=<weakref at 0x109b04e40; to 'AsyncPregelLoop' at 0x108f63250>, submit=<weakref at 0x10bb399a0; to 'AsyncBackgroundExecutor' at 0x10a061a90>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:29:56,511 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:29:56,511 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:29:56,732 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:29:56,732 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:29:56,733 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:29:56,774 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:29:56,774 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?metric ?value
WHERE {
  ?plot a wifire:PlotMetrics .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  {
    ?treeShrubMetrics wifire:CBH ?value .
    BIND("Canopy Base Height" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MDBH ?value .
    BIND("Mean Diameter at Breast Height" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MLAI ?value .
    BIND("Mean Leaf Area Index" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MaxSD ?value .
    BIND("Maximum Shrub Diameter" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MaxSH ?value .
    BIND("Maximum Shrub Height" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MaxTH ?value .
    BIND("Maximum Tree Height" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MeanSA ?value .
    BIND("Mean Shrub Area" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MeanSD ?value .
    BIND("Mean Stem Density" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MeanSH ?value .
    BIND("Mean Shrub Height" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MeanTH ?value .
    BIND("Mean Tree Height" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:MinSD ?value .
    BIND("Minimum Shrub Diameter" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:SDHT ?value .
    BIND("Shrub Height" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:SDSD ?value .
    BIND("Standard Deviation of Shrub Diameter" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:SDSHT ?value .
    BIND("Standard Deviation of Shrub Height" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:ShrubsN ?value .
    BIND("Number of Shrubs" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:scaledShrubArea ?value .
    BIND("Scaled Shrub Area" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:shrubArea ?value .
    BIND("Total Shrub Area" AS ?metric)
  } UNION {
    ?treeShrubMetrics wifire:TreesN ?value .
    BIND("Number of Trees" AS ?metric)
  }
}
LIMIT 50

2025-06-05 17:30:07,141 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the shrub height and its standard deviation for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 22, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:b22444ec-5669-8a0c-e96a-1fe8f89d3237', 'checkpoint_ns': 'tools:b22444ec-5669-8a0c-e96a-1fe8f89d3237'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x16b808410>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'b22444ec-5669-8a0c-e96a-1fe8f89d3237', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x162ae3b50>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109681200>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b7340>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b4e80>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b6d00>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10a017650>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10bb6f110>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426d6-5918-6708-8015-9422ae07c789'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:b22444ec-5669-8a0c-e96a-1fe8f89d3237', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10bd191b0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10a75d900>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1090a4ae0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10a7920b0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x162ab4d10; to 'PregelExecutableTask' at 0x16be9a680>, stream=False, retry=None, futures=<weakref at 0x162ab5580; to 'FuturesDict' at 0x10bbf4470>, schedule_task=<weakref at 0x16be38eb0; to 'AsyncPregelLoop' at 0x10962ba50>, submit=<weakref at 0x10bb39700; to 'AsyncBackgroundExecutor' at 0x109992410>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:30:07,141 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:30:07,142 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:30:07,371 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:30:07,371 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:30:07,372 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:30:07,420 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:30:07,420 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?shrubHeight ?stdDevShrubHeight
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:SDHT ?shrubHeight .
  ?treeShrubMetrics wifire:SDSHT ?stdDevShrubHeight .
}
LIMIT 50

2025-06-05 17:30:07,690 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:30:07,691 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:30:07,691 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:30:07,812 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:30:07,813 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:30:07,813 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

> Finished chain.

2025-06-05 17:30:10,683 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the recorded elevation for CASBC_0011_20240913_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:19412b57-4c1f-dd8d-a155-b3cfbd14f3d4', 'checkpoint_ns': 'tools:19412b57-4c1f-dd8d-a155-b3cfbd14f3d4'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x16cd2ff90>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '19412b57-4c1f-dd8d-a155-b3cfbd14f3d4', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169f22d40>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x10962bc80>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1086d76c0>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1086c7e40>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x1086c4480>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x16be8a5d0>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10a0c7b10>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426d6-7ae2-60dc-8001-6e8db7d3b8cf'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:19412b57-4c1f-dd8d-a155-b3cfbd14f3d4', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10868de40>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10868f220>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x109b45440>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10868fd30>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10b9efe70; to 'PregelExecutableTask' at 0x10b9f7400>, stream=False, retry=None, futures=<weakref at 0x109bc7ab0; to 'FuturesDict' at 0x10a7b8890>, schedule_task=<weakref at 0x10b9fb060; to 'AsyncPregelLoop' at 0x1086c4310>, submit=<weakref at 0x10b9fbb50; to 'AsyncBackgroundExecutor' at 0x10bb2aad0>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:30:10,684 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:30:10,685 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:30:10,905 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:30:10,905 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:30:10,906 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:30:10,948 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:30:10,948 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:30:19,918 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What are the shrub height and its standard deviation for CASBC_0007_20241117_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 24, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:b5edcd82-e036-d038-ccce-699153d0b9c5', 'checkpoint_ns': 'tools:b5edcd82-e036-d038-ccce-699153d0b9c5'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x109babb90>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'b5edcd82-e036-d038-ccce-699153d0b9c5', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x162ae3b50>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109681200>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b7340>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b4e80>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10b9b6d00>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10a017650>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10bb6f110>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426d6-d2f6-6368-8017-01f8d151de07'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:b5edcd82-e036-d038-ccce-699153d0b9c5', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b81faf0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10a7920b0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1090a4ae0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1084bf4f0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x161ca3650; to 'PregelExecutableTask' at 0x10b9f4d30>, stream=False, retry=None, futures=<weakref at 0x109780310; to 'FuturesDict' at 0x10bbf4590>, schedule_task=<weakref at 0x16be38eb0; to 'AsyncPregelLoop' at 0x10962ba50>, submit=<weakref at 0x10bb39700; to 'AsyncBackgroundExecutor' at 0x109992410>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:30:19,919 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:30:19,919 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:30:20,166 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:30:20,166 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:30:20,167 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:30:20,201 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:30:20,201 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?shrubHeight ?stdDevShrubHeight
WHERE {
  ?plot wifire:plotName "CASBC_0007_20241117_1" .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:SDHT ?shrubHeight .
  ?treeShrubMetrics wifire:SDSHT ?stdDevShrubHeight .
}
LIMIT 50

2025-06-05 17:30:20,578 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:30:20,579 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:30:20,579 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Invalid SPARQL query:
```sparql
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?plotName ?season (AVG(?shrubArea) AS ?avgShrubArea)
WHERE {
  ?plot a wifire:PlotMetrics .
  ?plot wifire:plotName ?plotName .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:shrubArea ?shrubArea .
  ?plot wifire:hasLocationDataPlot ?locationData .
  ?locationData wifire:plotCounty ?county .
  FILTER(CONTAINS(LCASE(?county), LCASE("santa barbara")) || ?county = "Santa Barbara County") .
  BIND(YEAR(?time) AS ?year) .
  BIND(MONTH(?time) AS ?month) .
  BIND(
    CASE
      WHEN (?month >= 3 && ?month <= 5) THEN "Spring"
      WHEN (?month >= 6 && ?month <= 8) THEN "Summer"
      WHEN (?month >= 9 && ?month <= 11) THEN "Autumn"
      ELSE "Winter"
    END
    AS ?season
  ) .
  ?sensor wifire:hasSensorMetadata ?sensorMetadata .
  ?sensorMetadata wifire:time ?time .
  ?plot wifire:hasFireIgnitionSensor ?sensor .
}
GROUP BY ?plotName ?season
ORDER BY ?plotName ?season
LIMIT 50
```
SPARQL Query Parse Error:
Expected {SelectQuery | ConstructQuery | DescribeQuery | AskQuery}, found '`'  (at char 0), (line:1, col:1)

Error running target function: Recursion limit of 25 reached without hitting a stop condition. You can increase the limit by setting the `recursion_limit` config key.
For troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/GRAPH_RECURSION_LIMIT
Traceback (most recent call last):
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langsmith/evaluation/_arunner.py", line 1236, in _aforward
    await fn(
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langsmith/run_helpers.py", line 538, in async_wrapper
    raise e
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langsmith/run_helpers.py", line 524, in async_wrapper
    function_result = await asyncio.create_task(  # type: ignore[call-arg]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/anaconda3/lib/python3.11/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "/Users/blake/anaconda3/lib/python3.11/asyncio/tasks.py", line 339, in __wakeup
    future.result()
  File "/Users/blake/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/Users/blake/anaconda3/lib/python3.11/asyncio/tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/var/folders/xg/71m7ljjd5dvbxqsym0xn0qv80000gn/T/ipykernel_32199/774810132.py", line 111, in target_func
    result = await agent_graph.ainvoke(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 2769, in ainvoke
    async for chunk in self.astream(
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 2673, in astream
    raise GraphRecursionError(msg)
langgraph.errors.GraphRecursionError: Recursion limit of 25 reached without hitting a stop condition. You can increase the limit by setting the `recursion_limit` config key.
For troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/GRAPH_RECURSION_LIMIT
2025-06-05 17:30:45,959 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the mean shrub volume (MSvol) recorded for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:53cf7657-1c1f-4aa0-1a80-1e7e5eb433fb', 'checkpoint_ns': 'tools:53cf7657-1c1f-4aa0-1a80-1e7e5eb433fb'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x109750150>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '53cf7657-1c1f-4aa0-1a80-1e7e5eb433fb', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169e8c7c0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109b2f940>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10bcc1d00>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10bcc3c40>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10bcc0b40>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x109b2d810>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x109b2cfd0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426d7-cb4a-6e74-8001-cb7d1979bf5d'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:53cf7657-1c1f-4aa0-1a80-1e7e5eb433fb', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16be301f0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16be32530>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x1090be5c0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16be33640>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10a7898f0; to 'PregelExecutableTask' at 0x16b7b9360>, stream=False, retry=None, futures=<weakref at 0x10b268ae0; to 'FuturesDict' at 0x10970cb30>, schedule_task=<weakref at 0x10bd9d1c0; to 'AsyncPregelLoop' at 0x109b2e590>, submit=<weakref at 0x10bd9d460; to 'AsyncBackgroundExecutor' at 0x10907aad0>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:30:45,960 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:30:45,962 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:30:46,195 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:30:46,196 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:30:46,196 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:30:46,233 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:30:46,234 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?elevation
WHERE {
  ?plot wifire:plotName "CASBC_0011_20240913_1" .
  ?plot wifire:hasFireBehaviorMetrics ?fireBehaviorMetrics .
  ?fireBehaviorMetrics wifire:LF_EVEL ?elevation .
}
LIMIT 50

2025-06-05 17:30:57,311 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the overstory leaf area index (OLAI) for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:94644de4-5eed-a9c0-2311-3026fd70ddcb', 'checkpoint_ns': 'tools:94644de4-5eed-a9c0-2311-3026fd70ddcb'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10bcc1b10>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '94644de4-5eed-a9c0-2311-3026fd70ddcb', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16be058a0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x10bd0dd80>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10a7f5140>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10a7f6a80>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10a7f6bc0>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10bd0df90>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10995add0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426d8-3791-6e84-8001-e22de3b8d42c'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:94644de4-5eed-a9c0-2311-3026fd70ddcb', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b81cc10>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b853010>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10a7220c0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b851300>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10bda68e0; to 'PregelExecutableTask' at 0x16be98f70>, stream=False, retry=None, futures=<weakref at 0x10bda6250; to 'FuturesDict' at 0x10bda23f0>, schedule_task=<weakref at 0x10bd9d7e0; to 'AsyncPregelLoop' at 0x10bd0ca50>, submit=<weakref at 0x10bd9d700; to 'AsyncBackgroundExecutor' at 0x10a7ad210>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:30:57,312 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:30:57,312 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:30:57,460 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:30:57,460 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:30:57,460 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:30:57,507 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:30:57,510 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:30:57,510 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:30:57,545 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:30:57,545 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Finished chain.


> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?msvol
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:MSvol ?msvol .
}
LIMIT 50

2025-06-05 17:31:22,081 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:31:22,083 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:31:22,084 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?olai
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:OLAI ?olai .
}
LIMIT 50

2025-06-05 17:31:40,318 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the understory leaf area index (ULAI) for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:b7971c17-9c57-65ef-3c1c-97bd56012041', 'checkpoint_ns': 'tools:b7971c17-9c57-65ef-3c1c-97bd56012041'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10c09bc90>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'b7971c17-9c57-65ef-3c1c-97bd56012041', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b12c130>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x10c08dac0>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c08d840>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c08f7c0>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c08f680>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10c0a8a50>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10c08ff50>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426d9-d1b7-6288-8001-e4c0c3404264'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:b7971c17-9c57-65ef-3c1c-97bd56012041', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x108f81f30>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x108f802e0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10c093380>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x108f828c0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10bdcdfd0; to 'PregelExecutableTask' at 0x16b7bb370>, stream=False, retry=None, futures=<weakref at 0x10bdcd620; to 'FuturesDict' at 0x10bc37410>, schedule_task=<weakref at 0x10bd9e180; to 'AsyncPregelLoop' at 0x10c08df50>, submit=<weakref at 0x10bd9e340; to 'AsyncBackgroundExecutor' at 0x10c08de50>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:31:40,319 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:31:40,319 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:31:40,370 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:31:40,370 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:31:40,370 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:31:40,530 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:31:40,531 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:31:40,531 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:31:40,566 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:31:40,567 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Finished chain.


> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:31:53,235 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the mean shrub volume (MSvol) recorded for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 4, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:c0ae5fb1-0668-06a5-e477-d06a767d8b44', 'checkpoint_ns': 'tools:c0ae5fb1-0668-06a5-e477-d06a767d8b44'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10c0712d0>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'c0ae5fb1-0668-06a5-e477-d06a767d8b44', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x169e8c7c0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x109b2f940>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10bcc1d00>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10bcc3c40>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10bcc0b40>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x109b2d810>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x109b2cfd0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426da-4ce3-6664-8003-955e1f4a1645'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:c0ae5fb1-0668-06a5-e477-d06a767d8b44', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109657b20>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10a00f8b0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10a0e6ca0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b81cf10>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10a7898f0; to 'PregelExecutableTask' at 0x16b7b9360>, stream=False, retry=None, futures=<weakref at 0x10b268ae0; to 'FuturesDict' at 0x109793ef0>, schedule_task=<weakref at 0x10bd9d1c0; to 'AsyncPregelLoop' at 0x109b2e590>, submit=<weakref at 0x10bd9d460; to 'AsyncBackgroundExecutor' at 0x10907aad0>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:31:53,236 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:31:53,236 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:31:53,456 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:31:53,456 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:31:53,457 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:31:53,499 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:31:53,499 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?msvol
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:MSvol ?msvol .
}
LIMIT 50

2025-06-05 17:31:53,873 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:31:53,874 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:31:53,874 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?ulai
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:ULAI ?ulai .
}
LIMIT 50
Invalid SPARQL query:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?plotName ?season (AVG(?shrubArea) AS ?avgShrubArea)
WHERE {
  ?plot a wifire:PlotMetrics .
  ?plot wifire:plotName ?plotName .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:shrubArea ?shrubArea .
  ?plot wifire:hasLocationDataPlot ?locationData .
  ?locationData wifire:plotCounty ?county .
  FILTER(CONTAINS(LCASE(?county), LCASE("santa barbara")) || ?county = "Santa Barbara County") .
  ?plot wifire:hasFireIgnitionSensor ?sensor .
  ?sensor wifire:hasSensorMetadata ?sensorMetadata .
  ?sensorMetadata wifire:time ?time .
  BIND(YEAR(?time) AS ?year) .
  BIND(MONTH(?time) AS ?month) .
  BIND(
    CASE
      WHEN (?month >= 3 && ?month <= 5) THEN "Spring"
      WHEN (?month >= 6 && ?month <= 8) THEN "Summer"
      WHEN (?month >= 9 && ?month <= 11) THEN "Autumn"
      ELSE "Winter"
    END
    AS ?season
  ) .
}
GROUP BY ?plotName ?season
ORDER BY ?plotName ?season
LIMIT 50
SPARQL Query Parse Error:
Expected SelectQuery, found 'BIND'  (at char 846), (line:20, col:3)

2025-06-05 17:32:08,703 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:32:08,704 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:32:08,704 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:32:09,290 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the EVT classification for CASBC_0011_20240913_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:c2a8ba83-5913-014f-07b6-43237ac2e5d8', 'checkpoint_ns': 'tools:c2a8ba83-5913-014f-07b6-43237ac2e5d8'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10c19abd0>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'c2a8ba83-5913-014f-07b6-43237ac2e5d8', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16be058a0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x10c1c4740>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c1bbf80>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c1bbdc0>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c1bbf40>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10842fcd0>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10c1ba790>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426da-e604-6726-8001-1acba0db6f77'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:c2a8ba83-5913-014f-07b6-43237ac2e5d8', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16cd486a0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16cd4a440>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10c107600>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16cd4b6d0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10c09d440; to 'PregelExecutableTask' at 0x10bd17250>, stream=False, retry=None, futures=<weakref at 0x10c09dd50; to 'FuturesDict' at 0x10bda1cd0>, schedule_task=<weakref at 0x10bd9f3e0; to 'AsyncPregelLoop' at 0x10c1bac50>, submit=<weakref at 0x10bd9fbc0; to 'AsyncBackgroundExecutor' at 0x109072190>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:32:09,291 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:32:09,291 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:32:09,512 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:32:09,513 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:32:09,513 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:32:09,552 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:32:09,552 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:32:29,825 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the Leaf Area Index (LAI) for the plot named CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:aa2e0800-0b6e-34f7-d238-b65206728ce1', 'checkpoint_ns': 'tools:aa2e0800-0b6e-34f7-d238-b65206728ce1'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10c162910>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'aa2e0800-0b6e-34f7-d238-b65206728ce1', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b8f2d40>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x10c16ca00>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c16f0c0>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c16d100>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c16f3c0>}, {'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10905aa50>, 'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10b219050>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426db-a9d6-6c4e-8001-90b78eea539e'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:aa2e0800-0b6e-34f7-d238-b65206728ce1', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x108f822c0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1086e6c80>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10c1dab60>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x1099b21d0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10bd318a0; to 'PregelExecutableTask' at 0x10bd16560>, stream=False, retry=None, futures=<weakref at 0x10bd316c0; to 'FuturesDict' at 0x10b27c170>, schedule_task=<weakref at 0x10bd9f920; to 'AsyncPregelLoop' at 0x10c16e9d0>, submit=<weakref at 0x10bd9ff40; to 'AsyncBackgroundExecutor' at 0x10c16cd10>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:32:29,826 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:32:29,826 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:32:30,053 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:32:30,053 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:32:30,054 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:32:30,093 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:32:30,094 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:32:42,795 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the understory leaf area index (ULAI) for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 4, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:a90772d7-aa1b-4f8c-e754-1a9f832669a8', 'checkpoint_ns': 'tools:a90772d7-aa1b-4f8c-e754-1a9f832669a8'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10c1f3d90>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'a90772d7-aa1b-4f8c-e754-1a9f832669a8', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b12c130>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x10c08dac0>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c08d840>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c08f7c0>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c08f680>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10c0a8a50>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10c08ff50>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426dc-2587-67ee-8003-9baff27f329e'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:a90772d7-aa1b-4f8c-e754-1a9f832669a8', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x108f5b400>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x108f828c0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10c093380>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x108f802e0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10bdcd620; to 'PregelExecutableTask' at 0x16b7bb370>, stream=False, retry=None, futures=<weakref at 0x10bdccd60; to 'FuturesDict' at 0x10c012870>, schedule_task=<weakref at 0x10bd9e180; to 'AsyncPregelLoop' at 0x10c08df50>, submit=<weakref at 0x10bd9e340; to 'AsyncBackgroundExecutor' at 0x10c08de50>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:32:42,795 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:32:42,796 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:32:43,010 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:32:43,010 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:32:43,010 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:32:43,054 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:32:43,054 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?ulai
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:ULAI ?ulai .
}
LIMIT 50

2025-06-05 17:32:43,444 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:32:43,445 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:32:43,445 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?evt
WHERE {
  ?plot wifire:plotName "CASBC_0011_20240913_1" .
  ?plot wifire:hasFireBehaviorMetrics ?fireBehaviorMetrics .
  ?fireBehaviorMetrics wifire:LF_EVT ?evt .
}
LIMIT 50

2025-06-05 17:32:54,506 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:32:54,507 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:32:54,508 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?lai
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:LAI ?lai .
}
LIMIT 50

2025-06-05 17:33:09,383 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:33:09,384 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:33:09,384 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:33:11,387 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the total basal area for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:5d22c53c-58bc-8660-079c-80dacb7e9dfa', 'checkpoint_ns': 'tools:5d22c53c-58bc-8660-079c-80dacb7e9dfa'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10c2a4350>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '5d22c53c-58bc-8660-079c-80dacb7e9dfa', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b12d5d0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x10c08f5c0>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c21ee80>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c21e680>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c21ea80>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x1084a2550>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10bd139d0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426dd-3635-6658-8001-32b787476e70'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:5d22c53c-58bc-8660-079c-80dacb7e9dfa', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10c25bcd0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10c25bb50>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10c1fc9a0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10c25a530>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10c2d0db0; to 'PregelExecutableTask' at 0x10c164b80>, stream=False, retry=None, futures=<weakref at 0x10c2d3ec0; to 'FuturesDict' at 0x10c2b5370>, schedule_task=<weakref at 0x10c124ba0; to 'AsyncPregelLoop' at 0x10c2a3ad0>, submit=<weakref at 0x10bd9f760; to 'AsyncBackgroundExecutor' at 0x10c198490>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:33:11,388 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:33:11,388 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:33:11,621 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:33:11,621 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:33:11,622 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:33:11,660 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:33:11,660 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:33:25,241 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: How many plots are there in Santa Barbara County? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:65fc5b14-841f-0473-2ad7-f0d263ce1f2a', 'checkpoint_ns': 'tools:65fc5b14-841f-0473-2ad7-f0d263ce1f2a'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10c2f4990>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '65fc5b14-841f-0473-2ad7-f0d263ce1f2a', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16be07a60>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x10c376bc0>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c376d40>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c3771c0>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c377380>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x10c27e4d0>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10c2b8050>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426dd-ba52-6f12-8001-41c3c2118443'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:65fc5b14-841f-0473-2ad7-f0d263ce1f2a', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109b92ad0>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10c2b0fd0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10c367e20>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10c2b28f0>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10c237100; to 'PregelExecutableTask' at 0x10bd15630>, stream=False, retry=None, futures=<weakref at 0x10c237dd0; to 'FuturesDict' at 0x10c094d10>, schedule_task=<weakref at 0x10c1260a0; to 'AsyncPregelLoop' at 0x10c2bf050>, submit=<weakref at 0x10c126030; to 'AsyncBackgroundExecutor' at 0x10c2a3910>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:33:25,242 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:33:25,242 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:33:25,454 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:33:25,455 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:33:25,455 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:33:25,492 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:33:25,492 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?basalArea
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:basalArea ?basalArea .
}
LIMIT 50

2025-06-05 17:33:46,871 - wildfire_kg.tools.kg - ERROR - Error querying knowledge graph: The generated SPARQL query is invalid.
Traceback (most recent call last):
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/kg_tool.py", line 124, in query_knowledge_graph
    result = qa_chain.invoke({qa_chain.input_key: query})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 167, in invoke
    raise e
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 157, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain_community/chains/graph_qa/ontotext_graphdb.py", line 134, in _call
    generated_sparql = self._get_prepared_sparql_query(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langchain_community/chains/graph_qa/ontotext_graphdb.py", line 182, in _get_prepared_sparql_query
    raise ValueError("The generated SPARQL query is invalid.")
ValueError: The generated SPARQL query is invalid.

Invalid SPARQL query:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?plotName ?season (AVG(?shrubArea) AS ?avgShrubArea)
WHERE {
  ?plot a wifire:PlotMetrics .
  ?plot wifire:plotName ?plotName .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:shrubArea ?shrubArea .
  ?plot wifire:hasLocationDataPlot ?locationData .
  ?locationData wifire:plotCounty ?county .
  FILTER(CONTAINS(LCASE(?county), LCASE("santa barbara")) || ?county = "Santa Barbara County") .
  ?plot wifire:hasFireIgnitionSensor ?sensor .
  ?sensor wifire:hasSensorMetadata ?sensorMetadata .
  ?sensorMetadata wifire:time ?time .
  BIND(YEAR(?time) AS ?year) .
  BIND(MONTH(?time) AS ?month) .
  BIND(
    CASE
      WHEN (?month >= 3 && ?month <= 5) THEN "Spring"
      WHEN (?month >= 6 && ?month <= 8) THEN "Summer"
      WHEN (?month >= 9 && ?month <= 11) THEN "Autumn"
      ELSE "Winter"
    END
    AS ?season
  ) .
}
GROUP BY ?plotName ?season
ORDER BY ?plotName ?season
LIMIT 50
SPARQL Query Parse Error:
Expected SelectQuery, found 'BIND'  (at char 846), (line:20, col:3)

Invalid SPARQL query:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?plotName ?season (AVG(?shrubArea) AS ?avgShrubArea)
WHERE {
  ?plot a wifire:PlotMetrics .
  ?plot wifire:plotName ?plotName .
  ?plot wifire:hasTreeShrubMetrics ?treeShrubMetrics .
  ?treeShrubMetrics wifire:shrubArea ?shrubArea .
  ?plot wifire:hasLocationDataPlot ?locationData .
  ?locationData wifire:plotCounty ?county .
  FILTER(CONTAINS(LCASE(?county), LCASE("santa barbara")) || ?county = "Santa Barbara County") .
  ?plot wifire:hasFireIgnitionSensor ?sensor .
  ?sensor wifire:hasSensorMetadata ?sensorMetadata .
  ?sensorMetadata wifire:time ?time .
  BIND(YEAR(?time) AS ?year) .
  BIND(MONTH(?time) AS ?month) .
  BIND(
    CASE
      WHEN (?month >= 3 && ?month <= 5) THEN "Spring"
      WHEN (?month >= 6 && ?month <= 8) THEN "Summer"
      WHEN (?month >= 9 && ?month <= 11) THEN "Autumn"
      ELSE "Winter"
    END
    AS ?season
  ) .
}
GROUP BY ?plotName ?season
ORDER BY ?plotName ?season
LIMIT 50
SPARQL Query Parse Error:
Expected SelectQuery, found 'BIND'  (at char 846), (line:20, col:3)

2025-06-05 17:33:50,328 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:33:50,329 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:33:50,330 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT (COUNT(DISTINCT ?plot) AS ?count)
WHERE {
  ?plot a wifire:PlotMetrics .
  ?plot wifire:hasLocationDataPlot ?locationData .
  ?locationData wifire:plotCounty ?county .
  FILTER(CONTAINS(LCASE(?county), LCASE("santa barbara"))) .
}
LIMIT 50

2025-06-05 17:34:07,450 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:34:07,451 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:34:07,451 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:34:11,049 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: average temperature in San Diego, CA yesterday
2025-06-05 17:34:11,050 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:34:11,050 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'yesterday': 2025-06-05
2025-06-05 17:34:11,051 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-05 for query: average temperature in San Diego, CA yesterday
2025-06-05 17:34:11,051 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-05
2025-06-05 17:34:11,052 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: -1
2025-06-05 17:34:11,052 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:34:11,053 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-05 00:00:00+00:00
2025-06-05 17:34:11,054 - wildfire_kg.tools.weather - INFO - - Location: San Diego, CA
2025-06-05 17:34:11,054 - wildfire_kg.tools.weather - INFO - - Type: Historical
2025-06-05 17:34:11,538 - wildfire_kg.tools.weather - INFO - Making historical API call...
2025-06-05 17:34:11,540 - wildfire_kg.tools.weather - INFO - Calling historical endpoint: https://history.openweathermap.org/data/2.5/history/city with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 32.7174202, 'lon': -117.1627728, 'type': 'hour', 'start': 1749106800, 'end': 1749193199}

==================================================
API Call Details:
Endpoint: https://history.openweathermap.org/data/2.5/history/city
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 32.7174202,
  "lon": -117.1627728,
  "type": "hour",
  "start": 1749106800,
  "end": 1749193199
}
Status Code: 200
Response: {
  "message": "Count: 18",
  "cod": "200",
  "city_id": 1,
  "calctime": 0.003779852,
  "cnt": 18,
  "list": [
    {
      "dt": 1749106800,
      "main": {
        "temp": 16.39,
        "feels_like": 16.41,
        "pressure": 1012,
        "humidity": 89,
        "temp_min": 15.47,
        "temp_max": 17.24
      },
      "wind": {
        "speed": 3.09,
        "deg": 320
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749110400,
      "main": {
        "temp": 16.33,
        "feels_like": 16.37,
        "pressure": 1012,
        "humidity": 90,
        "temp_min": 15.47,
        "temp_max": 17.24
      },
      "wind": {
        "speed": 3.13,
        "deg": 309,
        "gust": 4.47
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749114000,
      "main": {
        "temp": 16.15,
        "feels_like": 16.2,
        "pressure": 1012,
        "humidity": 91,
        "temp_min": 15.46,
        "temp_max": 17.09
      },
      "wind": {
        "speed": 2.57,
        "deg": 320
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749117600,
      "main": {
        "temp": 16.13,
        "feels_like": 16.2,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.46,
        "temp_max": 17.09
      },
      "wind": {
        "speed": 1.79,
        "deg": 304,
        "gust": 3.58
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749121200,
      "main": {
        "temp": 16.11,
        "feels_like": 16.18,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.42,
        "temp_max": 16.89
      },
      "wind": {
        "speed": 1.79,
        "deg": 310,
        "gust": 3.13
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749124800,
      "main": {
        "temp": 16.14,
        "feels_like": 16.21,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.47,
        "temp_max": 16.89
      },
      "wind": {
        "speed": 2.06,
        "deg": 290
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749128400,
      "main": {
        "temp": 16.16,
        "feels_like": 16.23,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.47,
        "temp_max": 17.16
      },
      "wind": {
        "speed": 3.13,
        "deg": 310,
        "gust": 4.47
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749132000,
      "main": {
        "temp": 16.31,
        "feels_like": 16.4,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.42,
        "temp_max": 17.18
      },
      "wind": {
        "speed": 3.13,
        "deg": 343,
        "gust": 4.92
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749135600,
      "main": {
        "temp": 16.69,
        "feels_like": 16.79,
        "pressure": 1013,
        "humidity": 91,
        "temp_min": 15.59,
        "temp_max": 17.77
      },
      "wind": {
        "speed": 3.58,
        "deg": 313,
        "gust": 5.36
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 701,
          "main": "Mist",
          "description": "mist",
          "icon": "50d"
        }
      ]
    },
    {
      "dt": 1749139200,
      "main": {
        "temp": 17.23,
        "feels_like": 17.36,
        "pressure": 1013,
        "humidity": 90,
        "temp_min": 16.09,
        "temp_max": 18.6
      },
      "wind": {
        "speed": 2.68,
        "deg": 303,
        "gust": 4.02
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749142800,
      "main": {
        "temp": 17.58,
        "feels_like": 17.69,
        "pressure": 1013,
        "humidity": 88,
        "temp_min": 16.53,
        "temp_max": 19.12
      },
      "wind": {
        "speed": 3.6,
        "deg": 270
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749146400,
      "main": {
        "temp": 17.45,
        "feels_like": 17.57,
        "pressure": 1013,
        "humidity": 89,
        "temp_min": 16.53,
        "temp_max": 18.87
      },
      "wind": {
        "speed": 4.02,
        "deg": 282,
        "gust": 5.81
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749150000,
      "main": {
        "temp": 17.89,
        "feels_like": 17.95,
        "pressure": 1013,
        "humidity": 85,
        "temp_min": 17.08,
        "temp_max": 18.9
      },
      "wind": {
        "speed": 4.63,
        "deg": 270
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 701,
          "main": "Mist",
          "description": "mist",
          "icon": "50d"
        }
      ]
    },
    {
      "dt": 1749153600,
      "main": {
        "temp": 18.02,
        "feels_like": 18.1,
        "pressure": 1013,
        "humidity": 85,
        "temp_min": 17.1,
        "temp_max": 19.42
      },
      "wind": {
        "speed": 5.14,
        "deg": 310
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749157200,
      "main": {
        "temp": 18.42,
        "feels_like": 18.46,
        "pressure": 1012,
        "humidity": 82,
        "temp_min": 17.55,
        "temp_max": 19.93
      },
      "wind": {
        "speed": 5.66,
        "deg": 300
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 300,
          "main": "Drizzle",
          "description": "light intensity drizzle",
          "icon": "09d"
        }
      ]
    },
    {
      "dt": 1749160800,
      "main": {
        "temp": 18.31,
        "feels_like": 18.34,
        "pressure": 1012,
        "humidity": 82,
        "temp_min": 17.08,
        "temp_max": 19.46
      },
      "wind": {
        "speed": 4.63,
        "deg": 300
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 300,
          "main": "Drizzle",
          "description": "light intensity drizzle",
          "icon": "09d"
        }
      ]
    },
    {
      "dt": 1749164400,
      "main": {
        "temp": 18.66,
        "feels_like": 18.7,
        "pressure": 1012,
        "humidity": 81,
        "temp_min": 17.55,
        "temp_max": 20.07
      },
      "wind": {
        "speed": 4.92,
        "deg": 309,
        "gust": 6.71
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749168000,
      "main": {
        "temp": 18.24,
        "feels_like": 18.23,
        "pressure": 1012,
        "humidity": 81,
        "temp_min": 17.08,
        "temp_max": 20.6
      },
      "wind": {
        "speed": 4.92,
        "deg": 276,
        "gust": 5.81
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    }
  ]
}
==================================================

2025-06-05 17:34:12,049 - wildfire_kg.tools.weather - INFO - API response for San Diego: {"message": "Count: 18", "cod": "200", "city_id": 1, "calctime": 0.003779852, "cnt": 18, "list": [{"dt": 1749106800, "main": {"temp": 16.39, "feels_like": 16.41, "pressure": 1012, "humidity": 89, "tem...
2025-06-05 17:34:12,051 - wildfire_kg.tools.weather - INFO - Averaging 17 historical entries for San Diego on 2025-06-05
2025-06-05 17:34:18,636 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: average temperature in San Diego, CA yesterday
2025-06-05 17:34:18,637 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:34:18,638 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'yesterday': 2025-06-05
2025-06-05 17:34:18,638 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-05 for query: average temperature in San Diego, CA yesterday
2025-06-05 17:34:18,639 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-05
2025-06-05 17:34:18,639 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: -1
2025-06-05 17:34:18,639 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:34:18,639 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-05 00:00:00+00:00
2025-06-05 17:34:18,640 - wildfire_kg.tools.weather - INFO - - Location: San Diego, CA
2025-06-05 17:34:18,641 - wildfire_kg.tools.weather - INFO - - Type: Historical
2025-06-05 17:34:18,811 - wildfire_kg.tools.weather - INFO - Making historical API call...
2025-06-05 17:34:18,813 - wildfire_kg.tools.weather - INFO - Calling historical endpoint: https://history.openweathermap.org/data/2.5/history/city with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 32.7174202, 'lon': -117.1627728, 'type': 'hour', 'start': 1749106800, 'end': 1749193199}

==================================================
API Call Details:
Endpoint: https://history.openweathermap.org/data/2.5/history/city
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 32.7174202,
  "lon": -117.1627728,
  "type": "hour",
  "start": 1749106800,
  "end": 1749193199
}
Status Code: 200
Response: {
  "message": "Count: 18",
  "cod": "200",
  "city_id": 1,
  "calctime": 0.003965318,
  "cnt": 18,
  "list": [
    {
      "dt": 1749106800,
      "main": {
        "temp": 16.39,
        "feels_like": 16.41,
        "pressure": 1012,
        "humidity": 89,
        "temp_min": 15.47,
        "temp_max": 17.24
      },
      "wind": {
        "speed": 3.09,
        "deg": 320
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749110400,
      "main": {
        "temp": 16.33,
        "feels_like": 16.37,
        "pressure": 1012,
        "humidity": 90,
        "temp_min": 15.47,
        "temp_max": 17.24
      },
      "wind": {
        "speed": 3.13,
        "deg": 309,
        "gust": 4.47
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749114000,
      "main": {
        "temp": 16.15,
        "feels_like": 16.2,
        "pressure": 1012,
        "humidity": 91,
        "temp_min": 15.46,
        "temp_max": 17.09
      },
      "wind": {
        "speed": 2.57,
        "deg": 320
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749117600,
      "main": {
        "temp": 16.13,
        "feels_like": 16.2,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.46,
        "temp_max": 17.09
      },
      "wind": {
        "speed": 1.79,
        "deg": 304,
        "gust": 3.58
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749121200,
      "main": {
        "temp": 16.11,
        "feels_like": 16.18,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.42,
        "temp_max": 16.89
      },
      "wind": {
        "speed": 1.79,
        "deg": 310,
        "gust": 3.13
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749124800,
      "main": {
        "temp": 16.14,
        "feels_like": 16.21,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.47,
        "temp_max": 16.89
      },
      "wind": {
        "speed": 2.06,
        "deg": 290
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ]
    },
    {
      "dt": 1749128400,
      "main": {
        "temp": 16.16,
        "feels_like": 16.23,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.47,
        "temp_max": 17.16
      },
      "wind": {
        "speed": 3.13,
        "deg": 310,
        "gust": 4.47
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749132000,
      "main": {
        "temp": 16.31,
        "feels_like": 16.4,
        "pressure": 1012,
        "humidity": 92,
        "temp_min": 15.42,
        "temp_max": 17.18
      },
      "wind": {
        "speed": 3.13,
        "deg": 343,
        "gust": 4.92
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749135600,
      "main": {
        "temp": 16.69,
        "feels_like": 16.79,
        "pressure": 1013,
        "humidity": 91,
        "temp_min": 15.59,
        "temp_max": 17.77
      },
      "wind": {
        "speed": 3.58,
        "deg": 313,
        "gust": 5.36
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 701,
          "main": "Mist",
          "description": "mist",
          "icon": "50d"
        }
      ]
    },
    {
      "dt": 1749139200,
      "main": {
        "temp": 17.23,
        "feels_like": 17.36,
        "pressure": 1013,
        "humidity": 90,
        "temp_min": 16.09,
        "temp_max": 18.6
      },
      "wind": {
        "speed": 2.68,
        "deg": 303,
        "gust": 4.02
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749142800,
      "main": {
        "temp": 17.58,
        "feels_like": 17.69,
        "pressure": 1013,
        "humidity": 88,
        "temp_min": 16.53,
        "temp_max": 19.12
      },
      "wind": {
        "speed": 3.6,
        "deg": 270
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749146400,
      "main": {
        "temp": 17.45,
        "feels_like": 17.57,
        "pressure": 1013,
        "humidity": 89,
        "temp_min": 16.53,
        "temp_max": 18.87
      },
      "wind": {
        "speed": 4.02,
        "deg": 282,
        "gust": 5.81
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749150000,
      "main": {
        "temp": 17.89,
        "feels_like": 17.95,
        "pressure": 1013,
        "humidity": 85,
        "temp_min": 17.08,
        "temp_max": 18.9
      },
      "wind": {
        "speed": 4.63,
        "deg": 270
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 701,
          "main": "Mist",
          "description": "mist",
          "icon": "50d"
        }
      ]
    },
    {
      "dt": 1749153600,
      "main": {
        "temp": 18.02,
        "feels_like": 18.1,
        "pressure": 1013,
        "humidity": 85,
        "temp_min": 17.1,
        "temp_max": 19.42
      },
      "wind": {
        "speed": 5.14,
        "deg": 310
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749157200,
      "main": {
        "temp": 18.42,
        "feels_like": 18.46,
        "pressure": 1012,
        "humidity": 82,
        "temp_min": 17.55,
        "temp_max": 19.93
      },
      "wind": {
        "speed": 5.66,
        "deg": 300
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 300,
          "main": "Drizzle",
          "description": "light intensity drizzle",
          "icon": "09d"
        }
      ]
    },
    {
      "dt": 1749160800,
      "main": {
        "temp": 18.31,
        "feels_like": 18.34,
        "pressure": 1012,
        "humidity": 82,
        "temp_min": 17.08,
        "temp_max": 19.46
      },
      "wind": {
        "speed": 4.63,
        "deg": 300
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 300,
          "main": "Drizzle",
          "description": "light intensity drizzle",
          "icon": "09d"
        }
      ]
    },
    {
      "dt": 1749164400,
      "main": {
        "temp": 18.66,
        "feels_like": 18.7,
        "pressure": 1012,
        "humidity": 81,
        "temp_min": 17.55,
        "temp_max": 20.07
      },
      "wind": {
        "speed": 4.92,
        "deg": 309,
        "gust": 6.71
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    },
    {
      "dt": 1749168000,
      "main": {
        "temp": 18.24,
        "feels_like": 18.23,
        "pressure": 1012,
        "humidity": 81,
        "temp_min": 17.08,
        "temp_max": 20.6
      },
      "wind": {
        "speed": 4.92,
        "deg": 276,
        "gust": 5.81
      },
      "clouds": {
        "all": 100
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ]
    }
  ]
}
==================================================

2025-06-05 17:34:19,340 - wildfire_kg.tools.weather - INFO - API response for San Diego: {"message": "Count: 18", "cod": "200", "city_id": 1, "calctime": 0.003965318, "cnt": 18, "list": [{"dt": 1749106800, "main": {"temp": 16.39, "feels_like": 16.41, "pressure": 1012, "humidity": 89, "tem...
2025-06-05 17:34:19,341 - wildfire_kg.tools.weather - INFO - Averaging 17 historical entries for San Diego on 2025-06-05
2025-06-05 17:34:36,374 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the basal area value for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 2, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:6aa793c2-ee7a-772a-4b1d-9f8050dcb56a', 'checkpoint_ns': 'tools:6aa793c2-ee7a-772a-4b1d-9f8050dcb56a'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10864e1d0>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': '6aa793c2-ee7a-772a-4b1d-9f8050dcb56a', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16b12f2e0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x10c12a9c0>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c409800>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c40a5c0>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c40bb00>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x109672790>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10c40b7d0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426e0-60b5-63c6-8001-567bec584876'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:6aa793c2-ee7a-772a-4b1d-9f8050dcb56a', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b321f90>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b3231f0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10c1a3060>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x109969330>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x1090453a0; to 'PregelExecutableTask' at 0x10b9f77f0>, stream=False, retry=None, futures=<weakref at 0x109045ad0; to 'FuturesDict' at 0x10c35f110>, schedule_task=<weakref at 0x10bd9ea40; to 'AsyncPregelLoop' at 0x10c409190>, submit=<weakref at 0x10bd9e420; to 'AsyncBackgroundExecutor' at 0x10c062d10>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:34:36,374 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:34:36,375 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:34:36,608 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:34:36,609 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:34:36,609 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:34:36,647 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:34:36,648 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...
2025-06-05 17:34:36,826 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: weather forecast for Los Angeles tomorrow
2025-06-05 17:34:36,826 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:34:36,826 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'tomorrow': 2025-06-07
2025-06-05 17:34:36,827 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-07 for query: weather forecast for Los Angeles tomorrow
2025-06-05 17:34:36,827 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-07
2025-06-05 17:34:36,827 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 1
2025-06-05 17:34:36,827 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:34:36,828 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-07 00:00:00+00:00
2025-06-05 17:34:36,828 - wildfire_kg.tools.weather - INFO - - Location: Los Angeles tomorrow
2025-06-05 17:34:36,828 - wildfire_kg.tools.weather - INFO - - Type: Forecast
2025-06-05 17:34:36,829 - wildfire_kg.tools.weather - INFO - DEBUG: Checking forecast range - Requested date: 2025-06-07, Max forecast date: 2025-06-11

> Entering new OntotextGraphDBQAChain chain...

2025-06-05 17:34:41,733 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:34:41,733 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:34:41,734 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'tomorrow': 2025-06-07
2025-06-05 17:34:41,734 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-07 for query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:34:41,734 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-07
2025-06-05 17:34:41,734 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 1
2025-06-05 17:34:41,735 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:34:41,735 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-07 00:00:00+00:00
2025-06-05 17:34:41,735 - wildfire_kg.tools.weather - INFO - - Location: tomorrow
2025-06-05 17:34:41,735 - wildfire_kg.tools.weather - INFO - - Type: Forecast
2025-06-05 17:34:41,736 - wildfire_kg.tools.weather - INFO - DEBUG: Checking forecast range - Requested date: 2025-06-07, Max forecast date: 2025-06-11
2025-06-05 17:34:41,958 - wildfire_kg.tools.weather - INFO - Making forecast API call...
2025-06-05 17:34:41,959 - wildfire_kg.tools.weather - INFO - Calling forecast endpoint: https://pro.openweathermap.org/data/2.5/forecast with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 17.3478229, 'lon': -88.6949636}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/forecast
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 17.3478229,
  "lon": -88.6949636
}
Status Code: 200
Response: {
  "cod": "200",
  "message": 0,
  "cnt": 40,
  "list": [
    {
      "dt": 1749178800,
      "main": {
        "temp": 26.18,
        "feels_like": 26.18,
        "temp_min": 24.5,
        "temp_max": 26.18,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 84,
        "temp_kf": 1.68
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.79,
        "deg": 94,
        "gust": 9.19
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 03:00:00"
    },
    {
      "dt": 1749189600,
      "main": {
        "temp": 24.58,
        "feels_like": 25.52,
        "temp_min": 23.36,
        "temp_max": 24.58,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 93,
        "temp_kf": 1.22
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 99
      },
      "wind": {
        "speed": 1.29,
        "deg": 94,
        "gust": 8.85
      },
      "visibility": 10000,
      "pop": 0.81,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 06:00:00"
    },
    {
      "dt": 1749200400,
      "main": {
        "temp": 23.12,
        "feels_like": 24.07,
        "temp_min": 23.12,
        "temp_max": 23.12,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.01,
        "deg": 104,
        "gust": 7.22
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.51
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 09:00:00"
    },
    {
      "dt": 1749211200,
      "main": {
        "temp": 23.82,
        "feels_like": 24.84,
        "temp_min": 23.82,
        "temp_max": 23.82,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 0.93,
        "deg": 97,
        "gust": 8.95
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.31
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 12:00:00"
    },
    {
      "dt": 1749222000,
      "main": {
        "temp": 26.84,
        "feels_like": 30.19,
        "temp_min": 26.84,
        "temp_max": 26.84,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 89,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 2.15,
        "deg": 87,
        "gust": 7.19
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.86
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 15:00:00"
    },
    {
      "dt": 1749232800,
      "main": {
        "temp": 28.09,
        "feels_like": 33.15,
        "temp_min": 28.09,
        "temp_max": 28.09,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 85,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 95
      },
      "wind": {
        "speed": 2.7,
        "deg": 82,
        "gust": 6.78
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 2.22
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 18:00:00"
    },
    {
      "dt": 1749243600,
      "main": {
        "temp": 29.48,
        "feels_like": 32.99,
        "temp_min": 29.48,
        "temp_max": 29.48,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 66,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 3.47,
        "deg": 87,
        "gust": 5.96
      },
      "visibility": 10000,
      "pop": 0.88,
      "rain": {
        "3h": 0.88
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 21:00:00"
    },
    {
      "dt": 1749254400,
      "main": {
        "temp": 24.56,
        "feels_like": 25.6,
        "temp_min": 24.56,
        "temp_max": 24.56,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 97,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 93
      },
      "wind": {
        "speed": 1.2,
        "deg": 84,
        "gust": 5.05
      },
      "visibility": 10000,
      "pop": 0.99,
      "rain": {
        "3h": 1.51
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 00:00:00"
    },
    {
      "dt": 1749265200,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 86
      },
      "wind": {
        "speed": 0.8,
        "deg": 107,
        "gust": 6.05
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.77
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 03:00:00"
    },
    {
      "dt": 1749276000,
      "main": {
        "temp": 22.8,
        "feels_like": 23.75,
        "temp_min": 22.8,
        "temp_max": 22.8,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 76
      },
      "wind": {
        "speed": 0.69,
        "deg": 94,
        "gust": 3.44
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 06:00:00"
    },
    {
      "dt": 1749286800,
      "main": {
        "temp": 22.96,
        "feels_like": 23.92,
        "temp_min": 22.96,
        "temp_max": 22.96,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 57
      },
      "wind": {
        "speed": 0.6,
        "deg": 114,
        "gust": 0.98
      },
      "visibility": 10000,
      "pop": 0.51,
      "rain": {
        "3h": 0.44
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 09:00:00"
    },
    {
      "dt": 1749297600,
      "main": {
        "temp": 23.26,
        "feels_like": 24.23,
        "temp_min": 23.26,
        "temp_max": 23.26,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 51
      },
      "wind": {
        "speed": 1.09,
        "deg": 99,
        "gust": 8.18
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 1.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 12:00:00"
    },
    {
      "dt": 1749308400,
      "main": {
        "temp": 26.34,
        "feels_like": 26.34,
        "temp_min": 26.34,
        "temp_max": 26.34,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 93,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 32
      },
      "wind": {
        "speed": 2.25,
        "deg": 87,
        "gust": 7.96
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.81
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 15:00:00"
    },
    {
      "dt": 1749319200,
      "main": {
        "temp": 27.25,
        "feels_like": 31.22,
        "temp_min": 27.25,
        "temp_max": 27.25,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 88,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 501,
          "main": "Rain",
          "description": "moderate rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 30
      },
      "wind": {
        "speed": 2.79,
        "deg": 84,
        "gust": 7.09
      },
      "visibility": 9165,
      "pop": 1,
      "rain": {
        "3h": 3.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 18:00:00"
    },
    {
      "dt": 1749330000,
      "main": {
        "temp": 28.53,
        "feels_like": 32.56,
        "temp_min": 28.53,
        "temp_max": 28.53,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 75,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 16
      },
      "wind": {
        "speed": 2.78,
        "deg": 80,
        "gust": 6.4
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.9
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 21:00:00"
    },
    {
      "dt": 1749340800,
      "main": {
        "temp": 24.78,
        "feels_like": 25.77,
        "temp_min": 24.78,
        "temp_max": 24.78,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 94,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 18
      },
      "wind": {
        "speed": 1.69,
        "deg": 88,
        "gust": 6.92
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.6
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 00:00:00"
    },
    {
      "dt": 1749351600,
      "main": {
        "temp": 22.91,
        "feels_like": 23.89,
        "temp_min": 22.91,
        "temp_max": 22.91,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 101,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 27
      },
      "wind": {
        "speed": 0.8,
        "deg": 117,
        "gust": 6.45
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 1.07
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 03:00:00"
    },
    {
      "dt": 1749362400,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 39
      },
      "wind": {
        "speed": 0.38,
        "deg": 143,
        "gust": 0.74
      },
      "visibility": 10000,
      "pop": 0.59,
      "rain": {
        "3h": 0.46
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 06:00:00"
    },
    {
      "dt": 1749373200,
      "main": {
        "temp": 23.1,
        "feels_like": 24.08,
        "temp_min": 23.1,
        "temp_max": 23.1,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 72
      },
      "wind": {
        "speed": 0.31,
        "deg": 15,
        "gust": 0.05
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.23
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 09:00:00"
    },
    {
      "dt": 1749384000,
      "main": {
        "temp": 23.57,
        "feels_like": 24.59,
        "temp_min": 23.57,
        "temp_max": 23.57,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 69
      },
      "wind": {
        "speed": 0.62,
        "deg": 71,
        "gust": 4.59
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.32
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 12:00:00"
    },
    {
      "dt": 1749394800,
      "main": {
        "temp": 29.24,
        "feels_like": 33.66,
        "temp_min": 29.24,
        "temp_max": 29.24,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 72,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 62
      },
      "wind": {
        "speed": 2.8,
        "deg": 98,
        "gust": 6.11
      },
      "visibility": 10000,
      "pop": 0.93,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 15:00:00"
    },
    {
      "dt": 1749405600,
      "main": {
        "temp": 31.91,
        "feels_like": 35.72,
        "temp_min": 31.91,
        "temp_max": 31.91,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 56,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 54
      },
      "wind": {
        "speed": 3.75,
        "deg": 87,
        "gust": 6
      },
      "visibility": 10000,
      "pop": 0.58,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 18:00:00"
    },
    {
      "dt": 1749416400,
      "main": {
        "temp": 30.55,
        "feels_like": 33.91,
        "temp_min": 30.55,
        "temp_max": 30.55,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1006,
        "humidity": 60,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 47
      },
      "wind": {
        "speed": 3.47,
        "deg": 86,
        "gust": 5.76
      },
      "visibility": 10000,
      "pop": 0.39,
      "rain": {
        "3h": 0.24
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 21:00:00"
    },
    {
      "dt": 1749427200,
      "main": {
        "temp": 26.67,
        "feels_like": 29.18,
        "temp_min": 26.67,
        "temp_max": 26.67,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 82,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "clouds": {
        "all": 34
      },
      "wind": {
        "speed": 2.27,
        "deg": 90,
        "gust": 6.67
      },
      "visibility": 10000,
      "pop": 0.31,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-09 00:00:00"
    },
    {
      "dt": 1749438000,
      "main": {
        "temp": 23.11,
        "feels_like": 24.09,
        "temp_min": 23.11,
        "temp_max": 23.11,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 13
      },
      "wind": {
        "speed": 0.83,
        "deg": 129,
        "gust": 3.08
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.39
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 03:00:00"
    },
    {
      "dt": 1749448800,
      "main": {
        "temp": 22.92,
        "feels_like": 23.88,
        "temp_min": 22.92,
        "temp_max": 22.92,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 24
      },
      "wind": {
        "speed": 0.72,
        "deg": 126,
        "gust": 2.27
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 06:00:00"
    },
    {
      "dt": 1749459600,
      "main": {

2025-06-05 17:34:42,158 - wildfire_kg.tools.weather - INFO - API response for More Tomorrow: {"cod": "200", "message": 0, "cnt": 40, "list": [{"dt": 1749178800, "main": {"temp": 26.18, "feels_like": 26.18, "temp_min": 24.5, "temp_max": 26.18, "pressure": 1012, "sea_level": 1012, "grnd_level":...
2025-06-05 17:34:42,159 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: 8 forecast entries for More Tomorrow on 2025-06-07
2025-06-05 17:34:51,873 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:34:51,876 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:34:51,877 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'tomorrow': 2025-06-07
2025-06-05 17:34:51,878 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-07 for query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:34:51,879 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-07
2025-06-05 17:34:51,879 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 1
2025-06-05 17:34:51,880 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:34:51,880 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-07 00:00:00+00:00
2025-06-05 17:34:51,881 - wildfire_kg.tools.weather - INFO - - Location: tomorrow
2025-06-05 17:34:51,881 - wildfire_kg.tools.weather - INFO - - Type: Forecast
2025-06-05 17:34:51,882 - wildfire_kg.tools.weather - INFO - DEBUG: Checking forecast range - Requested date: 2025-06-07, Max forecast date: 2025-06-11
2025-06-05 17:34:51,975 - wildfire_kg.tools.weather - INFO - Making forecast API call...
2025-06-05 17:34:51,975 - wildfire_kg.tools.weather - INFO - Calling forecast endpoint: https://pro.openweathermap.org/data/2.5/forecast with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 17.3478229, 'lon': -88.6949636}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/forecast
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 17.3478229,
  "lon": -88.6949636
}
Status Code: 200
Response: {
  "cod": "200",
  "message": 0,
  "cnt": 40,
  "list": [
    {
      "dt": 1749178800,
      "main": {
        "temp": 26.18,
        "feels_like": 26.18,
        "temp_min": 24.5,
        "temp_max": 26.18,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 84,
        "temp_kf": 1.68
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.79,
        "deg": 94,
        "gust": 9.19
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 03:00:00"
    },
    {
      "dt": 1749189600,
      "main": {
        "temp": 24.58,
        "feels_like": 25.52,
        "temp_min": 23.36,
        "temp_max": 24.58,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 93,
        "temp_kf": 1.22
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 99
      },
      "wind": {
        "speed": 1.29,
        "deg": 94,
        "gust": 8.85
      },
      "visibility": 10000,
      "pop": 0.81,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 06:00:00"
    },
    {
      "dt": 1749200400,
      "main": {
        "temp": 23.12,
        "feels_like": 24.07,
        "temp_min": 23.12,
        "temp_max": 23.12,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.01,
        "deg": 104,
        "gust": 7.22
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.51
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 09:00:00"
    },
    {
      "dt": 1749211200,
      "main": {
        "temp": 23.82,
        "feels_like": 24.84,
        "temp_min": 23.82,
        "temp_max": 23.82,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 0.93,
        "deg": 97,
        "gust": 8.95
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.31
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 12:00:00"
    },
    {
      "dt": 1749222000,
      "main": {
        "temp": 26.84,
        "feels_like": 30.19,
        "temp_min": 26.84,
        "temp_max": 26.84,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 89,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 2.15,
        "deg": 87,
        "gust": 7.19
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.86
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 15:00:00"
    },
    {
      "dt": 1749232800,
      "main": {
        "temp": 28.09,
        "feels_like": 33.15,
        "temp_min": 28.09,
        "temp_max": 28.09,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 85,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 95
      },
      "wind": {
        "speed": 2.7,
        "deg": 82,
        "gust": 6.78
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 2.22
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 18:00:00"
    },
    {
      "dt": 1749243600,
      "main": {
        "temp": 29.48,
        "feels_like": 32.99,
        "temp_min": 29.48,
        "temp_max": 29.48,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 66,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 3.47,
        "deg": 87,
        "gust": 5.96
      },
      "visibility": 10000,
      "pop": 0.88,
      "rain": {
        "3h": 0.88
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 21:00:00"
    },
    {
      "dt": 1749254400,
      "main": {
        "temp": 24.56,
        "feels_like": 25.6,
        "temp_min": 24.56,
        "temp_max": 24.56,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 97,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 93
      },
      "wind": {
        "speed": 1.2,
        "deg": 84,
        "gust": 5.05
      },
      "visibility": 10000,
      "pop": 0.99,
      "rain": {
        "3h": 1.51
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 00:00:00"
    },
    {
      "dt": 1749265200,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 86
      },
      "wind": {
        "speed": 0.8,
        "deg": 107,
        "gust": 6.05
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.77
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 03:00:00"
    },
    {
      "dt": 1749276000,
      "main": {
        "temp": 22.8,
        "feels_like": 23.75,
        "temp_min": 22.8,
        "temp_max": 22.8,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 76
      },
      "wind": {
        "speed": 0.69,
        "deg": 94,
        "gust": 3.44
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 06:00:00"
    },
    {
      "dt": 1749286800,
      "main": {
        "temp": 22.96,
        "feels_like": 23.92,
        "temp_min": 22.96,
        "temp_max": 22.96,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 57
      },
      "wind": {
        "speed": 0.6,
        "deg": 114,
        "gust": 0.98
      },
      "visibility": 10000,
      "pop": 0.51,
      "rain": {
        "3h": 0.44
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 09:00:00"
    },
    {
      "dt": 1749297600,
      "main": {
        "temp": 23.26,
        "feels_like": 24.23,
        "temp_min": 23.26,
        "temp_max": 23.26,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 51
      },
      "wind": {
        "speed": 1.09,
        "deg": 99,
        "gust": 8.18
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 1.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 12:00:00"
    },
    {
      "dt": 1749308400,
      "main": {
        "temp": 26.34,
        "feels_like": 26.34,
        "temp_min": 26.34,
        "temp_max": 26.34,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 93,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 32
      },
      "wind": {
        "speed": 2.25,
        "deg": 87,
        "gust": 7.96
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.81
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 15:00:00"
    },
    {
      "dt": 1749319200,
      "main": {
        "temp": 27.25,
        "feels_like": 31.22,
        "temp_min": 27.25,
        "temp_max": 27.25,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 88,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 501,
          "main": "Rain",
          "description": "moderate rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 30
      },
      "wind": {
        "speed": 2.79,
        "deg": 84,
        "gust": 7.09
      },
      "visibility": 9165,
      "pop": 1,
      "rain": {
        "3h": 3.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 18:00:00"
    },
    {
      "dt": 1749330000,
      "main": {
        "temp": 28.53,
        "feels_like": 32.56,
        "temp_min": 28.53,
        "temp_max": 28.53,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 75,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 16
      },
      "wind": {
        "speed": 2.78,
        "deg": 80,
        "gust": 6.4
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.9
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 21:00:00"
    },
    {
      "dt": 1749340800,
      "main": {
        "temp": 24.78,
        "feels_like": 25.77,
        "temp_min": 24.78,
        "temp_max": 24.78,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 94,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 18
      },
      "wind": {
        "speed": 1.69,
        "deg": 88,
        "gust": 6.92
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.6
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 00:00:00"
    },
    {
      "dt": 1749351600,
      "main": {
        "temp": 22.91,
        "feels_like": 23.89,
        "temp_min": 22.91,
        "temp_max": 22.91,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 101,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 27
      },
      "wind": {
        "speed": 0.8,
        "deg": 117,
        "gust": 6.45
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 1.07
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 03:00:00"
    },
    {
      "dt": 1749362400,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 39
      },
      "wind": {
        "speed": 0.38,
        "deg": 143,
        "gust": 0.74
      },
      "visibility": 10000,
      "pop": 0.59,
      "rain": {
        "3h": 0.46
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 06:00:00"
    },
    {
      "dt": 1749373200,
      "main": {
        "temp": 23.1,
        "feels_like": 24.08,
        "temp_min": 23.1,
        "temp_max": 23.1,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 72
      },
      "wind": {
        "speed": 0.31,
        "deg": 15,
        "gust": 0.05
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.23
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 09:00:00"
    },
    {
      "dt": 1749384000,
      "main": {
        "temp": 23.57,
        "feels_like": 24.59,
        "temp_min": 23.57,
        "temp_max": 23.57,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 69
      },
      "wind": {
        "speed": 0.62,
        "deg": 71,
        "gust": 4.59
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.32
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 12:00:00"
    },
    {
      "dt": 1749394800,
      "main": {
        "temp": 29.24,
        "feels_like": 33.66,
        "temp_min": 29.24,
        "temp_max": 29.24,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 72,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 62
      },
      "wind": {
        "speed": 2.8,
        "deg": 98,
        "gust": 6.11
      },
      "visibility": 10000,
      "pop": 0.93,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 15:00:00"
    },
    {
      "dt": 1749405600,
      "main": {
        "temp": 31.91,
        "feels_like": 35.72,
        "temp_min": 31.91,
        "temp_max": 31.91,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 56,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 54
      },
      "wind": {
        "speed": 3.75,
        "deg": 87,
        "gust": 6
      },
      "visibility": 10000,
      "pop": 0.58,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 18:00:00"
    },
    {
      "dt": 1749416400,
      "main": {
        "temp": 30.55,
        "feels_like": 33.91,
        "temp_min": 30.55,
        "temp_max": 30.55,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1006,
        "humidity": 60,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 47
      },
      "wind": {
        "speed": 3.47,
        "deg": 86,
        "gust": 5.76
      },
      "visibility": 10000,
      "pop": 0.39,
      "rain": {
        "3h": 0.24
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 21:00:00"
    },
    {
      "dt": 1749427200,
      "main": {
        "temp": 26.67,
        "feels_like": 29.18,
        "temp_min": 26.67,
        "temp_max": 26.67,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 82,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "clouds": {
        "all": 34
      },
      "wind": {
        "speed": 2.27,
        "deg": 90,
        "gust": 6.67
      },
      "visibility": 10000,
      "pop": 0.31,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-09 00:00:00"
    },
    {
      "dt": 1749438000,
      "main": {
        "temp": 23.11,
        "feels_like": 24.09,
        "temp_min": 23.11,
        "temp_max": 23.11,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 13
      },
      "wind": {
        "speed": 0.83,
        "deg": 129,
        "gust": 3.08
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.39
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 03:00:00"
    },
    {
      "dt": 1749448800,
      "main": {
        "temp": 22.92,
        "feels_like": 23.88,
        "temp_min": 22.92,
        "temp_max": 22.92,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 24
      },
      "wind": {
        "speed": 0.72,
        "deg": 126,
        "gust": 2.27
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 06:00:00"
    },
    {
      "dt": 1749459600,
      "main": {

2025-06-05 17:34:52,135 - wildfire_kg.tools.weather - INFO - API response for More Tomorrow: {"cod": "200", "message": 0, "cnt": 40, "list": [{"dt": 1749178800, "main": {"temp": 26.18, "feels_like": 26.18, "temp_min": 24.5, "temp_max": 26.18, "pressure": 1012, "sea_level": 1012, "grnd_level":...
2025-06-05 17:34:52,137 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: 8 forecast entries for More Tomorrow on 2025-06-07
2025-06-05 17:34:54,240 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:34:54,241 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:34:54,241 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'tomorrow': 2025-06-07
2025-06-05 17:34:54,241 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-07 for query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:34:54,242 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-07
2025-06-05 17:34:54,242 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 1
2025-06-05 17:34:54,242 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:34:54,243 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-07 00:00:00+00:00
2025-06-05 17:34:54,243 - wildfire_kg.tools.weather - INFO - - Location: tomorrow
2025-06-05 17:34:54,244 - wildfire_kg.tools.weather - INFO - - Type: Forecast
2025-06-05 17:34:54,244 - wildfire_kg.tools.weather - INFO - DEBUG: Checking forecast range - Requested date: 2025-06-07, Max forecast date: 2025-06-11
2025-06-05 17:34:54,328 - wildfire_kg.tools.weather - INFO - Making forecast API call...
2025-06-05 17:34:54,328 - wildfire_kg.tools.weather - INFO - Calling forecast endpoint: https://pro.openweathermap.org/data/2.5/forecast with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 17.3478229, 'lon': -88.6949636}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/forecast
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 17.3478229,
  "lon": -88.6949636
}
Status Code: 200
Response: {
  "cod": "200",
  "message": 0,
  "cnt": 40,
  "list": [
    {
      "dt": 1749178800,
      "main": {
        "temp": 26.18,
        "feels_like": 26.18,
        "temp_min": 24.5,
        "temp_max": 26.18,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 84,
        "temp_kf": 1.68
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.79,
        "deg": 94,
        "gust": 9.19
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 03:00:00"
    },
    {
      "dt": 1749189600,
      "main": {
        "temp": 24.58,
        "feels_like": 25.52,
        "temp_min": 23.36,
        "temp_max": 24.58,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 93,
        "temp_kf": 1.22
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 99
      },
      "wind": {
        "speed": 1.29,
        "deg": 94,
        "gust": 8.85
      },
      "visibility": 10000,
      "pop": 0.81,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 06:00:00"
    },
    {
      "dt": 1749200400,
      "main": {
        "temp": 23.12,
        "feels_like": 24.07,
        "temp_min": 23.12,
        "temp_max": 23.12,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.01,
        "deg": 104,
        "gust": 7.22
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.51
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 09:00:00"
    },
    {
      "dt": 1749211200,
      "main": {
        "temp": 23.82,
        "feels_like": 24.84,
        "temp_min": 23.82,
        "temp_max": 23.82,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 0.93,
        "deg": 97,
        "gust": 8.95
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.31
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 12:00:00"
    },
    {
      "dt": 1749222000,
      "main": {
        "temp": 26.84,
        "feels_like": 30.19,
        "temp_min": 26.84,
        "temp_max": 26.84,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 89,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 2.15,
        "deg": 87,
        "gust": 7.19
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.86
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 15:00:00"
    },
    {
      "dt": 1749232800,
      "main": {
        "temp": 28.09,
        "feels_like": 33.15,
        "temp_min": 28.09,
        "temp_max": 28.09,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 85,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 95
      },
      "wind": {
        "speed": 2.7,
        "deg": 82,
        "gust": 6.78
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 2.22
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 18:00:00"
    },
    {
      "dt": 1749243600,
      "main": {
        "temp": 29.48,
        "feels_like": 32.99,
        "temp_min": 29.48,
        "temp_max": 29.48,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 66,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 3.47,
        "deg": 87,
        "gust": 5.96
      },
      "visibility": 10000,
      "pop": 0.88,
      "rain": {
        "3h": 0.88
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 21:00:00"
    },
    {
      "dt": 1749254400,
      "main": {
        "temp": 24.56,
        "feels_like": 25.6,
        "temp_min": 24.56,
        "temp_max": 24.56,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 97,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 93
      },
      "wind": {
        "speed": 1.2,
        "deg": 84,
        "gust": 5.05
      },
      "visibility": 10000,
      "pop": 0.99,
      "rain": {
        "3h": 1.51
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 00:00:00"
    },
    {
      "dt": 1749265200,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 86
      },
      "wind": {
        "speed": 0.8,
        "deg": 107,
        "gust": 6.05
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.77
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 03:00:00"
    },
    {
      "dt": 1749276000,
      "main": {
        "temp": 22.8,
        "feels_like": 23.75,
        "temp_min": 22.8,
        "temp_max": 22.8,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 76
      },
      "wind": {
        "speed": 0.69,
        "deg": 94,
        "gust": 3.44
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 06:00:00"
    },
    {
      "dt": 1749286800,
      "main": {
        "temp": 22.96,
        "feels_like": 23.92,
        "temp_min": 22.96,
        "temp_max": 22.96,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 57
      },
      "wind": {
        "speed": 0.6,
        "deg": 114,
        "gust": 0.98
      },
      "visibility": 10000,
      "pop": 0.51,
      "rain": {
        "3h": 0.44
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 09:00:00"
    },
    {
      "dt": 1749297600,
      "main": {
        "temp": 23.26,
        "feels_like": 24.23,
        "temp_min": 23.26,
        "temp_max": 23.26,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 51
      },
      "wind": {
        "speed": 1.09,
        "deg": 99,
        "gust": 8.18
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 1.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 12:00:00"
    },
    {
      "dt": 1749308400,
      "main": {
        "temp": 26.34,
        "feels_like": 26.34,
        "temp_min": 26.34,
        "temp_max": 26.34,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 93,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 32
      },
      "wind": {
        "speed": 2.25,
        "deg": 87,
        "gust": 7.96
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.81
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 15:00:00"
    },
    {
      "dt": 1749319200,
      "main": {
        "temp": 27.25,
        "feels_like": 31.22,
        "temp_min": 27.25,
        "temp_max": 27.25,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 88,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 501,
          "main": "Rain",
          "description": "moderate rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 30
      },
      "wind": {
        "speed": 2.79,
        "deg": 84,
        "gust": 7.09
      },
      "visibility": 9165,
      "pop": 1,
      "rain": {
        "3h": 3.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 18:00:00"
    },
    {
      "dt": 1749330000,
      "main": {
        "temp": 28.53,
        "feels_like": 32.56,
        "temp_min": 28.53,
        "temp_max": 28.53,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 75,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 16
      },
      "wind": {
        "speed": 2.78,
        "deg": 80,
        "gust": 6.4
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.9
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 21:00:00"
    },
    {
      "dt": 1749340800,
      "main": {
        "temp": 24.78,
        "feels_like": 25.77,
        "temp_min": 24.78,
        "temp_max": 24.78,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 94,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 18
      },
      "wind": {
        "speed": 1.69,
        "deg": 88,
        "gust": 6.92
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.6
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 00:00:00"
    },
    {
      "dt": 1749351600,
      "main": {
        "temp": 22.91,
        "feels_like": 23.89,
        "temp_min": 22.91,
        "temp_max": 22.91,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 101,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 27
      },
      "wind": {
        "speed": 0.8,
        "deg": 117,
        "gust": 6.45
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 1.07
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 03:00:00"
    },
    {
      "dt": 1749362400,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 39
      },
      "wind": {
        "speed": 0.38,
        "deg": 143,
        "gust": 0.74
      },
      "visibility": 10000,
      "pop": 0.59,
      "rain": {
        "3h": 0.46
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 06:00:00"
    },
    {
      "dt": 1749373200,
      "main": {
        "temp": 23.1,
        "feels_like": 24.08,
        "temp_min": 23.1,
        "temp_max": 23.1,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 72
      },
      "wind": {
        "speed": 0.31,
        "deg": 15,
        "gust": 0.05
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.23
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 09:00:00"
    },
    {
      "dt": 1749384000,
      "main": {
        "temp": 23.57,
        "feels_like": 24.59,
        "temp_min": 23.57,
        "temp_max": 23.57,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 69
      },
      "wind": {
        "speed": 0.62,
        "deg": 71,
        "gust": 4.59
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.32
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 12:00:00"
    },
    {
      "dt": 1749394800,
      "main": {
        "temp": 29.24,
        "feels_like": 33.66,
        "temp_min": 29.24,
        "temp_max": 29.24,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 72,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 62
      },
      "wind": {
        "speed": 2.8,
        "deg": 98,
        "gust": 6.11
      },
      "visibility": 10000,
      "pop": 0.93,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 15:00:00"
    },
    {
      "dt": 1749405600,
      "main": {
        "temp": 31.91,
        "feels_like": 35.72,
        "temp_min": 31.91,
        "temp_max": 31.91,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 56,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 54
      },
      "wind": {
        "speed": 3.75,
        "deg": 87,
        "gust": 6
      },
      "visibility": 10000,
      "pop": 0.58,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 18:00:00"
    },
    {
      "dt": 1749416400,
      "main": {
        "temp": 30.55,
        "feels_like": 33.91,
        "temp_min": 30.55,
        "temp_max": 30.55,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1006,
        "humidity": 60,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 47
      },
      "wind": {
        "speed": 3.47,
        "deg": 86,
        "gust": 5.76
      },
      "visibility": 10000,
      "pop": 0.39,
      "rain": {
        "3h": 0.24
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 21:00:00"
    },
    {
      "dt": 1749427200,
      "main": {
        "temp": 26.67,
        "feels_like": 29.18,
        "temp_min": 26.67,
        "temp_max": 26.67,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 82,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "clouds": {
        "all": 34
      },
      "wind": {
        "speed": 2.27,
        "deg": 90,
        "gust": 6.67
      },
      "visibility": 10000,
      "pop": 0.31,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-09 00:00:00"
    },
    {
      "dt": 1749438000,
      "main": {
        "temp": 23.11,
        "feels_like": 24.09,
        "temp_min": 23.11,
        "temp_max": 23.11,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 13
      },
      "wind": {
        "speed": 0.83,
        "deg": 129,
        "gust": 3.08
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.39
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 03:00:00"
    },
    {
      "dt": 1749448800,
      "main": {
        "temp": 22.92,
        "feels_like": 23.88,
        "temp_min": 22.92,
        "temp_max": 22.92,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 24
      },
      "wind": {
        "speed": 0.72,
        "deg": 126,
        "gust": 2.27
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 06:00:00"
    },
    {
      "dt": 1749459600,
      "main": {

2025-06-05 17:34:54,491 - wildfire_kg.tools.weather - INFO - API response for More Tomorrow: {"cod": "200", "message": 0, "cnt": 40, "list": [{"dt": 1749178800, "main": {"temp": 26.18, "feels_like": 26.18, "temp_min": 24.5, "temp_max": 26.18, "pressure": 1012, "sea_level": 1012, "grnd_level":...
2025-06-05 17:34:54,493 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: 8 forecast entries for More Tomorrow on 2025-06-07
2025-06-05 17:35:03,272 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:35:03,273 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:35:03,273 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'tomorrow': 2025-06-07
2025-06-05 17:35:03,274 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-07 for query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:35:03,274 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-07
2025-06-05 17:35:03,274 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 1
2025-06-05 17:35:03,274 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:35:03,275 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-07 00:00:00+00:00
2025-06-05 17:35:03,275 - wildfire_kg.tools.weather - INFO - - Location: tomorrow
2025-06-05 17:35:03,276 - wildfire_kg.tools.weather - INFO - - Type: Forecast
2025-06-05 17:35:03,276 - wildfire_kg.tools.weather - INFO - DEBUG: Checking forecast range - Requested date: 2025-06-07, Max forecast date: 2025-06-11
2025-06-05 17:35:03,358 - wildfire_kg.tools.weather - INFO - Making forecast API call...
2025-06-05 17:35:03,359 - wildfire_kg.tools.weather - INFO - Calling forecast endpoint: https://pro.openweathermap.org/data/2.5/forecast with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 17.3478229, 'lon': -88.6949636}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/forecast
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 17.3478229,
  "lon": -88.6949636
}
Status Code: 200
Response: {
  "cod": "200",
  "message": 0,
  "cnt": 40,
  "list": [
    {
      "dt": 1749178800,
      "main": {
        "temp": 26.18,
        "feels_like": 26.18,
        "temp_min": 24.5,
        "temp_max": 26.18,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 84,
        "temp_kf": 1.68
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.79,
        "deg": 94,
        "gust": 9.19
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 03:00:00"
    },
    {
      "dt": 1749189600,
      "main": {
        "temp": 24.58,
        "feels_like": 25.52,
        "temp_min": 23.36,
        "temp_max": 24.58,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 93,
        "temp_kf": 1.22
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 99
      },
      "wind": {
        "speed": 1.29,
        "deg": 94,
        "gust": 8.85
      },
      "visibility": 10000,
      "pop": 0.81,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 06:00:00"
    },
    {
      "dt": 1749200400,
      "main": {
        "temp": 23.12,
        "feels_like": 24.07,
        "temp_min": 23.12,
        "temp_max": 23.12,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.01,
        "deg": 104,
        "gust": 7.22
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.51
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 09:00:00"
    },
    {
      "dt": 1749211200,
      "main": {
        "temp": 23.82,
        "feels_like": 24.84,
        "temp_min": 23.82,
        "temp_max": 23.82,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 0.93,
        "deg": 97,
        "gust": 8.95
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.31
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 12:00:00"
    },
    {
      "dt": 1749222000,
      "main": {
        "temp": 26.84,
        "feels_like": 30.19,
        "temp_min": 26.84,
        "temp_max": 26.84,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 89,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 2.15,
        "deg": 87,
        "gust": 7.19
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.86
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 15:00:00"
    },
    {
      "dt": 1749232800,
      "main": {
        "temp": 28.09,
        "feels_like": 33.15,
        "temp_min": 28.09,
        "temp_max": 28.09,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 85,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 95
      },
      "wind": {
        "speed": 2.7,
        "deg": 82,
        "gust": 6.78
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 2.22
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 18:00:00"
    },
    {
      "dt": 1749243600,
      "main": {
        "temp": 29.48,
        "feels_like": 32.99,
        "temp_min": 29.48,
        "temp_max": 29.48,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 66,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 3.47,
        "deg": 87,
        "gust": 5.96
      },
      "visibility": 10000,
      "pop": 0.88,
      "rain": {
        "3h": 0.88
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 21:00:00"
    },
    {
      "dt": 1749254400,
      "main": {
        "temp": 24.56,
        "feels_like": 25.6,
        "temp_min": 24.56,
        "temp_max": 24.56,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 97,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 93
      },
      "wind": {
        "speed": 1.2,
        "deg": 84,
        "gust": 5.05
      },
      "visibility": 10000,
      "pop": 0.99,
      "rain": {
        "3h": 1.51
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 00:00:00"
    },
    {
      "dt": 1749265200,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 86
      },
      "wind": {
        "speed": 0.8,
        "deg": 107,
        "gust": 6.05
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.77
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 03:00:00"
    },
    {
      "dt": 1749276000,
      "main": {
        "temp": 22.8,
        "feels_like": 23.75,
        "temp_min": 22.8,
        "temp_max": 22.8,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 76
      },
      "wind": {
        "speed": 0.69,
        "deg": 94,
        "gust": 3.44
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 06:00:00"
    },
    {
      "dt": 1749286800,
      "main": {
        "temp": 22.96,
        "feels_like": 23.92,
        "temp_min": 22.96,
        "temp_max": 22.96,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 57
      },
      "wind": {
        "speed": 0.6,
        "deg": 114,
        "gust": 0.98
      },
      "visibility": 10000,
      "pop": 0.51,
      "rain": {
        "3h": 0.44
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 09:00:00"
    },
    {
      "dt": 1749297600,
      "main": {
        "temp": 23.26,
        "feels_like": 24.23,
        "temp_min": 23.26,
        "temp_max": 23.26,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 51
      },
      "wind": {
        "speed": 1.09,
        "deg": 99,
        "gust": 8.18
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 1.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 12:00:00"
    },
    {
      "dt": 1749308400,
      "main": {
        "temp": 26.34,
        "feels_like": 26.34,
        "temp_min": 26.34,
        "temp_max": 26.34,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 93,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 32
      },
      "wind": {
        "speed": 2.25,
        "deg": 87,
        "gust": 7.96
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.81
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 15:00:00"
    },
    {
      "dt": 1749319200,
      "main": {
        "temp": 27.25,
        "feels_like": 31.22,
        "temp_min": 27.25,
        "temp_max": 27.25,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 88,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 501,
          "main": "Rain",
          "description": "moderate rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 30
      },
      "wind": {
        "speed": 2.79,
        "deg": 84,
        "gust": 7.09
      },
      "visibility": 9165,
      "pop": 1,
      "rain": {
        "3h": 3.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 18:00:00"
    },
    {
      "dt": 1749330000,
      "main": {
        "temp": 28.53,
        "feels_like": 32.56,
        "temp_min": 28.53,
        "temp_max": 28.53,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 75,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 16
      },
      "wind": {
        "speed": 2.78,
        "deg": 80,
        "gust": 6.4
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.9
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 21:00:00"
    },
    {
      "dt": 1749340800,
      "main": {
        "temp": 24.78,
        "feels_like": 25.77,
        "temp_min": 24.78,
        "temp_max": 24.78,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 94,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 18
      },
      "wind": {
        "speed": 1.69,
        "deg": 88,
        "gust": 6.92
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.6
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 00:00:00"
    },
    {
      "dt": 1749351600,
      "main": {
        "temp": 22.91,
        "feels_like": 23.89,
        "temp_min": 22.91,
        "temp_max": 22.91,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 101,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 27
      },
      "wind": {
        "speed": 0.8,
        "deg": 117,
        "gust": 6.45
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 1.07
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 03:00:00"
    },
    {
      "dt": 1749362400,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 39
      },
      "wind": {
        "speed": 0.38,
        "deg": 143,
        "gust": 0.74
      },
      "visibility": 10000,
      "pop": 0.59,
      "rain": {
        "3h": 0.46
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 06:00:00"
    },
    {
      "dt": 1749373200,
      "main": {
        "temp": 23.1,
        "feels_like": 24.08,
        "temp_min": 23.1,
        "temp_max": 23.1,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 72
      },
      "wind": {
        "speed": 0.31,
        "deg": 15,
        "gust": 0.05
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.23
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 09:00:00"
    },
    {
      "dt": 1749384000,
      "main": {
        "temp": 23.57,
        "feels_like": 24.59,
        "temp_min": 23.57,
        "temp_max": 23.57,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 69
      },
      "wind": {
        "speed": 0.62,
        "deg": 71,
        "gust": 4.59
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.32
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 12:00:00"
    },
    {
      "dt": 1749394800,
      "main": {
        "temp": 29.24,
        "feels_like": 33.66,
        "temp_min": 29.24,
        "temp_max": 29.24,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 72,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 62
      },
      "wind": {
        "speed": 2.8,
        "deg": 98,
        "gust": 6.11
      },
      "visibility": 10000,
      "pop": 0.93,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 15:00:00"
    },
    {
      "dt": 1749405600,
      "main": {
        "temp": 31.91,
        "feels_like": 35.72,
        "temp_min": 31.91,
        "temp_max": 31.91,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 56,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 54
      },
      "wind": {
        "speed": 3.75,
        "deg": 87,
        "gust": 6
      },
      "visibility": 10000,
      "pop": 0.58,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 18:00:00"
    },
    {
      "dt": 1749416400,
      "main": {
        "temp": 30.55,
        "feels_like": 33.91,
        "temp_min": 30.55,
        "temp_max": 30.55,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1006,
        "humidity": 60,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 47
      },
      "wind": {
        "speed": 3.47,
        "deg": 86,
        "gust": 5.76
      },
      "visibility": 10000,
      "pop": 0.39,
      "rain": {
        "3h": 0.24
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 21:00:00"
    },
    {
      "dt": 1749427200,
      "main": {
        "temp": 26.67,
        "feels_like": 29.18,
        "temp_min": 26.67,
        "temp_max": 26.67,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 82,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "clouds": {
        "all": 34
      },
      "wind": {
        "speed": 2.27,
        "deg": 90,
        "gust": 6.67
      },
      "visibility": 10000,
      "pop": 0.31,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-09 00:00:00"
    },
    {
      "dt": 1749438000,
      "main": {
        "temp": 23.11,
        "feels_like": 24.09,
        "temp_min": 23.11,
        "temp_max": 23.11,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 13
      },
      "wind": {
        "speed": 0.83,
        "deg": 129,
        "gust": 3.08
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.39
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 03:00:00"
    },
    {
      "dt": 1749448800,
      "main": {
        "temp": 22.92,
        "feels_like": 23.88,
        "temp_min": 22.92,
        "temp_max": 22.92,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 24
      },
      "wind": {
        "speed": 0.72,
        "deg": 126,
        "gust": 2.27
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 06:00:00"
    },
    {
      "dt": 1749459600,
      "main": {

2025-06-05 17:35:03,531 - wildfire_kg.tools.weather - INFO - API response for More Tomorrow: {"cod": "200", "message": 0, "cnt": 40, "list": [{"dt": 1749178800, "main": {"temp": 26.18, "feels_like": 26.18, "temp_min": 24.5, "temp_max": 26.18, "pressure": 1012, "sea_level": 1012, "grnd_level":...
2025-06-05 17:35:03,532 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: 8 forecast entries for More Tomorrow on 2025-06-07

Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?basalArea
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:basalArea ?basalArea .
}
LIMIT 50

2025-06-05 17:35:06,143 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:35:06,143 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:35:06,144 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'tomorrow': 2025-06-07
2025-06-05 17:35:06,144 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-07 for query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:35:06,144 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-07
2025-06-05 17:35:06,144 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 1
2025-06-05 17:35:06,144 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:35:06,144 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-07 00:00:00+00:00
2025-06-05 17:35:06,145 - wildfire_kg.tools.weather - INFO - - Location: tomorrow
2025-06-05 17:35:06,145 - wildfire_kg.tools.weather - INFO - - Type: Forecast
2025-06-05 17:35:06,145 - wildfire_kg.tools.weather - INFO - DEBUG: Checking forecast range - Requested date: 2025-06-07, Max forecast date: 2025-06-11
2025-06-05 17:35:06,248 - wildfire_kg.tools.weather - INFO - Making forecast API call...
2025-06-05 17:35:06,248 - wildfire_kg.tools.weather - INFO - Calling forecast endpoint: https://pro.openweathermap.org/data/2.5/forecast with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 17.3478229, 'lon': -88.6949636}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/forecast
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 17.3478229,
  "lon": -88.6949636
}
Status Code: 200
Response: {
  "cod": "200",
  "message": 0,
  "cnt": 40,
  "list": [
    {
      "dt": 1749178800,
      "main": {
        "temp": 26.18,
        "feels_like": 26.18,
        "temp_min": 24.5,
        "temp_max": 26.18,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 84,
        "temp_kf": 1.68
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.79,
        "deg": 94,
        "gust": 9.19
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 03:00:00"
    },
    {
      "dt": 1749189600,
      "main": {
        "temp": 24.58,
        "feels_like": 25.52,
        "temp_min": 23.36,
        "temp_max": 24.58,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 93,
        "temp_kf": 1.22
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 99
      },
      "wind": {
        "speed": 1.29,
        "deg": 94,
        "gust": 8.85
      },
      "visibility": 10000,
      "pop": 0.81,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 06:00:00"
    },
    {
      "dt": 1749200400,
      "main": {
        "temp": 23.12,
        "feels_like": 24.07,
        "temp_min": 23.12,
        "temp_max": 23.12,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.01,
        "deg": 104,
        "gust": 7.22
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.51
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 09:00:00"
    },
    {
      "dt": 1749211200,
      "main": {
        "temp": 23.82,
        "feels_like": 24.84,
        "temp_min": 23.82,
        "temp_max": 23.82,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 0.93,
        "deg": 97,
        "gust": 8.95
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.31
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 12:00:00"
    },
    {
      "dt": 1749222000,
      "main": {
        "temp": 26.84,
        "feels_like": 30.19,
        "temp_min": 26.84,
        "temp_max": 26.84,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 89,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 2.15,
        "deg": 87,
        "gust": 7.19
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.86
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 15:00:00"
    },
    {
      "dt": 1749232800,
      "main": {
        "temp": 28.09,
        "feels_like": 33.15,
        "temp_min": 28.09,
        "temp_max": 28.09,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 85,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 95
      },
      "wind": {
        "speed": 2.7,
        "deg": 82,
        "gust": 6.78
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 2.22
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 18:00:00"
    },
    {
      "dt": 1749243600,
      "main": {
        "temp": 29.48,
        "feels_like": 32.99,
        "temp_min": 29.48,
        "temp_max": 29.48,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 66,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 3.47,
        "deg": 87,
        "gust": 5.96
      },
      "visibility": 10000,
      "pop": 0.88,
      "rain": {
        "3h": 0.88
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 21:00:00"
    },
    {
      "dt": 1749254400,
      "main": {
        "temp": 24.56,
        "feels_like": 25.6,
        "temp_min": 24.56,
        "temp_max": 24.56,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 97,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 93
      },
      "wind": {
        "speed": 1.2,
        "deg": 84,
        "gust": 5.05
      },
      "visibility": 10000,
      "pop": 0.99,
      "rain": {
        "3h": 1.51
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 00:00:00"
    },
    {
      "dt": 1749265200,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 86
      },
      "wind": {
        "speed": 0.8,
        "deg": 107,
        "gust": 6.05
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.77
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 03:00:00"
    },
    {
      "dt": 1749276000,
      "main": {
        "temp": 22.8,
        "feels_like": 23.75,
        "temp_min": 22.8,
        "temp_max": 22.8,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 76
      },
      "wind": {
        "speed": 0.69,
        "deg": 94,
        "gust": 3.44
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 06:00:00"
    },
    {
      "dt": 1749286800,
      "main": {
        "temp": 22.96,
        "feels_like": 23.92,
        "temp_min": 22.96,
        "temp_max": 22.96,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 57
      },
      "wind": {
        "speed": 0.6,
        "deg": 114,
        "gust": 0.98
      },
      "visibility": 10000,
      "pop": 0.51,
      "rain": {
        "3h": 0.44
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 09:00:00"
    },
    {
      "dt": 1749297600,
      "main": {
        "temp": 23.26,
        "feels_like": 24.23,
        "temp_min": 23.26,
        "temp_max": 23.26,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 51
      },
      "wind": {
        "speed": 1.09,
        "deg": 99,
        "gust": 8.18
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 1.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 12:00:00"
    },
    {
      "dt": 1749308400,
      "main": {
        "temp": 26.34,
        "feels_like": 26.34,
        "temp_min": 26.34,
        "temp_max": 26.34,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 93,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 32
      },
      "wind": {
        "speed": 2.25,
        "deg": 87,
        "gust": 7.96
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.81
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 15:00:00"
    },
    {
      "dt": 1749319200,
      "main": {
        "temp": 27.25,
        "feels_like": 31.22,
        "temp_min": 27.25,
        "temp_max": 27.25,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 88,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 501,
          "main": "Rain",
          "description": "moderate rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 30
      },
      "wind": {
        "speed": 2.79,
        "deg": 84,
        "gust": 7.09
      },
      "visibility": 9165,
      "pop": 1,
      "rain": {
        "3h": 3.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 18:00:00"
    },
    {
      "dt": 1749330000,
      "main": {
        "temp": 28.53,
        "feels_like": 32.56,
        "temp_min": 28.53,
        "temp_max": 28.53,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 75,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 16
      },
      "wind": {
        "speed": 2.78,
        "deg": 80,
        "gust": 6.4
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.9
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 21:00:00"
    },
    {
      "dt": 1749340800,
      "main": {
        "temp": 24.78,
        "feels_like": 25.77,
        "temp_min": 24.78,
        "temp_max": 24.78,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 94,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 18
      },
      "wind": {
        "speed": 1.69,
        "deg": 88,
        "gust": 6.92
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.6
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 00:00:00"
    },
    {
      "dt": 1749351600,
      "main": {
        "temp": 22.91,
        "feels_like": 23.89,
        "temp_min": 22.91,
        "temp_max": 22.91,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 101,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 27
      },
      "wind": {
        "speed": 0.8,
        "deg": 117,
        "gust": 6.45
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 1.07
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 03:00:00"
    },
    {
      "dt": 1749362400,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 39
      },
      "wind": {
        "speed": 0.38,
        "deg": 143,
        "gust": 0.74
      },
      "visibility": 10000,
      "pop": 0.59,
      "rain": {
        "3h": 0.46
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 06:00:00"
    },
    {
      "dt": 1749373200,
      "main": {
        "temp": 23.1,
        "feels_like": 24.08,
        "temp_min": 23.1,
        "temp_max": 23.1,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 72
      },
      "wind": {
        "speed": 0.31,
        "deg": 15,
        "gust": 0.05
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.23
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 09:00:00"
    },
    {
      "dt": 1749384000,
      "main": {
        "temp": 23.57,
        "feels_like": 24.59,
        "temp_min": 23.57,
        "temp_max": 23.57,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 69
      },
      "wind": {
        "speed": 0.62,
        "deg": 71,
        "gust": 4.59
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.32
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 12:00:00"
    },
    {
      "dt": 1749394800,
      "main": {
        "temp": 29.24,
        "feels_like": 33.66,
        "temp_min": 29.24,
        "temp_max": 29.24,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 72,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 62
      },
      "wind": {
        "speed": 2.8,
        "deg": 98,
        "gust": 6.11
      },
      "visibility": 10000,
      "pop": 0.93,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 15:00:00"
    },
    {
      "dt": 1749405600,
      "main": {
        "temp": 31.91,
        "feels_like": 35.72,
        "temp_min": 31.91,
        "temp_max": 31.91,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 56,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 54
      },
      "wind": {
        "speed": 3.75,
        "deg": 87,
        "gust": 6
      },
      "visibility": 10000,
      "pop": 0.58,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 18:00:00"
    },
    {
      "dt": 1749416400,
      "main": {
        "temp": 30.55,
        "feels_like": 33.91,
        "temp_min": 30.55,
        "temp_max": 30.55,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1006,
        "humidity": 60,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 47
      },
      "wind": {
        "speed": 3.47,
        "deg": 86,
        "gust": 5.76
      },
      "visibility": 10000,
      "pop": 0.39,
      "rain": {
        "3h": 0.24
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 21:00:00"
    },
    {
      "dt": 1749427200,
      "main": {
        "temp": 26.67,
        "feels_like": 29.18,
        "temp_min": 26.67,
        "temp_max": 26.67,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 82,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "clouds": {
        "all": 34
      },
      "wind": {
        "speed": 2.27,
        "deg": 90,
        "gust": 6.67
      },
      "visibility": 10000,
      "pop": 0.31,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-09 00:00:00"
    },
    {
      "dt": 1749438000,
      "main": {
        "temp": 23.11,
        "feels_like": 24.09,
        "temp_min": 23.11,
        "temp_max": 23.11,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 13
      },
      "wind": {
        "speed": 0.83,
        "deg": 129,
        "gust": 3.08
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.39
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 03:00:00"
    },
    {
      "dt": 1749448800,
      "main": {
        "temp": 22.92,
        "feels_like": 23.88,
        "temp_min": 22.92,
        "temp_max": 22.92,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 24
      },
      "wind": {
        "speed": 0.72,
        "deg": 126,
        "gust": 2.27
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 06:00:00"
    },
    {
      "dt": 1749459600,
      "main": {

2025-06-05 17:35:06,406 - wildfire_kg.tools.weather - INFO - API response for More Tomorrow: {"cod": "200", "message": 0, "cnt": 40, "list": [{"dt": 1749178800, "main": {"temp": 26.18, "feels_like": 26.18, "temp_min": 24.5, "temp_max": 26.18, "pressure": 1012, "sea_level": 1012, "grnd_level":...
2025-06-05 17:35:06,406 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: 8 forecast entries for More Tomorrow on 2025-06-07
2025-06-05 17:35:06,568 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:35:06,568 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:35:06,569 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}

> Finished chain.

2025-06-05 17:35:10,395 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:35:10,395 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:35:10,396 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'tomorrow': 2025-06-07
2025-06-05 17:35:10,396 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-07 for query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:35:10,396 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-07
2025-06-05 17:35:10,396 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 1
2025-06-05 17:35:10,397 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:35:10,397 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-07 00:00:00+00:00
2025-06-05 17:35:10,397 - wildfire_kg.tools.weather - INFO - - Location: tomorrow
2025-06-05 17:35:10,398 - wildfire_kg.tools.weather - INFO - - Type: Forecast
2025-06-05 17:35:10,398 - wildfire_kg.tools.weather - INFO - DEBUG: Checking forecast range - Requested date: 2025-06-07, Max forecast date: 2025-06-11
2025-06-05 17:35:10,479 - wildfire_kg.tools.weather - INFO - Making forecast API call...
2025-06-05 17:35:10,480 - wildfire_kg.tools.weather - INFO - Calling forecast endpoint: https://pro.openweathermap.org/data/2.5/forecast with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 17.3478229, 'lon': -88.6949636}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/forecast
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 17.3478229,
  "lon": -88.6949636
}
Status Code: 200
Response: {
  "cod": "200",
  "message": 0,
  "cnt": 40,
  "list": [
    {
      "dt": 1749178800,
      "main": {
        "temp": 26.18,
        "feels_like": 26.18,
        "temp_min": 24.5,
        "temp_max": 26.18,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 84,
        "temp_kf": 1.68
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.79,
        "deg": 94,
        "gust": 9.19
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 03:00:00"
    },
    {
      "dt": 1749189600,
      "main": {
        "temp": 24.58,
        "feels_like": 25.52,
        "temp_min": 23.36,
        "temp_max": 24.58,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 93,
        "temp_kf": 1.22
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 99
      },
      "wind": {
        "speed": 1.29,
        "deg": 94,
        "gust": 8.85
      },
      "visibility": 10000,
      "pop": 0.81,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 06:00:00"
    },
    {
      "dt": 1749200400,
      "main": {
        "temp": 23.12,
        "feels_like": 24.07,
        "temp_min": 23.12,
        "temp_max": 23.12,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.01,
        "deg": 104,
        "gust": 7.22
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.51
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 09:00:00"
    },
    {
      "dt": 1749211200,
      "main": {
        "temp": 23.82,
        "feels_like": 24.84,
        "temp_min": 23.82,
        "temp_max": 23.82,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 0.93,
        "deg": 97,
        "gust": 8.95
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.31
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 12:00:00"
    },
    {
      "dt": 1749222000,
      "main": {
        "temp": 26.84,
        "feels_like": 30.19,
        "temp_min": 26.84,
        "temp_max": 26.84,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 89,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 2.15,
        "deg": 87,
        "gust": 7.19
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.86
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 15:00:00"
    },
    {
      "dt": 1749232800,
      "main": {
        "temp": 28.09,
        "feels_like": 33.15,
        "temp_min": 28.09,
        "temp_max": 28.09,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 85,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 95
      },
      "wind": {
        "speed": 2.7,
        "deg": 82,
        "gust": 6.78
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 2.22
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 18:00:00"
    },
    {
      "dt": 1749243600,
      "main": {
        "temp": 29.48,
        "feels_like": 32.99,
        "temp_min": 29.48,
        "temp_max": 29.48,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 66,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 3.47,
        "deg": 87,
        "gust": 5.96
      },
      "visibility": 10000,
      "pop": 0.88,
      "rain": {
        "3h": 0.88
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 21:00:00"
    },
    {
      "dt": 1749254400,
      "main": {
        "temp": 24.56,
        "feels_like": 25.6,
        "temp_min": 24.56,
        "temp_max": 24.56,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 97,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 93
      },
      "wind": {
        "speed": 1.2,
        "deg": 84,
        "gust": 5.05
      },
      "visibility": 10000,
      "pop": 0.99,
      "rain": {
        "3h": 1.51
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 00:00:00"
    },
    {
      "dt": 1749265200,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 86
      },
      "wind": {
        "speed": 0.8,
        "deg": 107,
        "gust": 6.05
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.77
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 03:00:00"
    },
    {
      "dt": 1749276000,
      "main": {
        "temp": 22.8,
        "feels_like": 23.75,
        "temp_min": 22.8,
        "temp_max": 22.8,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 76
      },
      "wind": {
        "speed": 0.69,
        "deg": 94,
        "gust": 3.44
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 06:00:00"
    },
    {
      "dt": 1749286800,
      "main": {
        "temp": 22.96,
        "feels_like": 23.92,
        "temp_min": 22.96,
        "temp_max": 22.96,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 57
      },
      "wind": {
        "speed": 0.6,
        "deg": 114,
        "gust": 0.98
      },
      "visibility": 10000,
      "pop": 0.51,
      "rain": {
        "3h": 0.44
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 09:00:00"
    },
    {
      "dt": 1749297600,
      "main": {
        "temp": 23.26,
        "feels_like": 24.23,
        "temp_min": 23.26,
        "temp_max": 23.26,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 51
      },
      "wind": {
        "speed": 1.09,
        "deg": 99,
        "gust": 8.18
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 1.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 12:00:00"
    },
    {
      "dt": 1749308400,
      "main": {
        "temp": 26.34,
        "feels_like": 26.34,
        "temp_min": 26.34,
        "temp_max": 26.34,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 93,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 32
      },
      "wind": {
        "speed": 2.25,
        "deg": 87,
        "gust": 7.96
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.81
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 15:00:00"
    },
    {
      "dt": 1749319200,
      "main": {
        "temp": 27.25,
        "feels_like": 31.22,
        "temp_min": 27.25,
        "temp_max": 27.25,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 88,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 501,
          "main": "Rain",
          "description": "moderate rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 30
      },
      "wind": {
        "speed": 2.79,
        "deg": 84,
        "gust": 7.09
      },
      "visibility": 9165,
      "pop": 1,
      "rain": {
        "3h": 3.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 18:00:00"
    },
    {
      "dt": 1749330000,
      "main": {
        "temp": 28.53,
        "feels_like": 32.56,
        "temp_min": 28.53,
        "temp_max": 28.53,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 75,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 16
      },
      "wind": {
        "speed": 2.78,
        "deg": 80,
        "gust": 6.4
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.9
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 21:00:00"
    },
    {
      "dt": 1749340800,
      "main": {
        "temp": 24.78,
        "feels_like": 25.77,
        "temp_min": 24.78,
        "temp_max": 24.78,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 94,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 18
      },
      "wind": {
        "speed": 1.69,
        "deg": 88,
        "gust": 6.92
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.6
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 00:00:00"
    },
    {
      "dt": 1749351600,
      "main": {
        "temp": 22.91,
        "feels_like": 23.89,
        "temp_min": 22.91,
        "temp_max": 22.91,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 101,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 27
      },
      "wind": {
        "speed": 0.8,
        "deg": 117,
        "gust": 6.45
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 1.07
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 03:00:00"
    },
    {
      "dt": 1749362400,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 39
      },
      "wind": {
        "speed": 0.38,
        "deg": 143,
        "gust": 0.74
      },
      "visibility": 10000,
      "pop": 0.59,
      "rain": {
        "3h": 0.46
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 06:00:00"
    },
    {
      "dt": 1749373200,
      "main": {
        "temp": 23.1,
        "feels_like": 24.08,
        "temp_min": 23.1,
        "temp_max": 23.1,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 72
      },
      "wind": {
        "speed": 0.31,
        "deg": 15,
        "gust": 0.05
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.23
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 09:00:00"
    },
    {
      "dt": 1749384000,
      "main": {
        "temp": 23.57,
        "feels_like": 24.59,
        "temp_min": 23.57,
        "temp_max": 23.57,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 69
      },
      "wind": {
        "speed": 0.62,
        "deg": 71,
        "gust": 4.59
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.32
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 12:00:00"
    },
    {
      "dt": 1749394800,
      "main": {
        "temp": 29.24,
        "feels_like": 33.66,
        "temp_min": 29.24,
        "temp_max": 29.24,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 72,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 62
      },
      "wind": {
        "speed": 2.8,
        "deg": 98,
        "gust": 6.11
      },
      "visibility": 10000,
      "pop": 0.93,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 15:00:00"
    },
    {
      "dt": 1749405600,
      "main": {
        "temp": 31.91,
        "feels_like": 35.72,
        "temp_min": 31.91,
        "temp_max": 31.91,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 56,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 54
      },
      "wind": {
        "speed": 3.75,
        "deg": 87,
        "gust": 6
      },
      "visibility": 10000,
      "pop": 0.58,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 18:00:00"
    },
    {
      "dt": 1749416400,
      "main": {
        "temp": 30.55,
        "feels_like": 33.91,
        "temp_min": 30.55,
        "temp_max": 30.55,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1006,
        "humidity": 60,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 47
      },
      "wind": {
        "speed": 3.47,
        "deg": 86,
        "gust": 5.76
      },
      "visibility": 10000,
      "pop": 0.39,
      "rain": {
        "3h": 0.24
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 21:00:00"
    },
    {
      "dt": 1749427200,
      "main": {
        "temp": 26.67,
        "feels_like": 29.18,
        "temp_min": 26.67,
        "temp_max": 26.67,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 82,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "clouds": {
        "all": 34
      },
      "wind": {
        "speed": 2.27,
        "deg": 90,
        "gust": 6.67
      },
      "visibility": 10000,
      "pop": 0.31,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-09 00:00:00"
    },
    {
      "dt": 1749438000,
      "main": {
        "temp": 23.11,
        "feels_like": 24.09,
        "temp_min": 23.11,
        "temp_max": 23.11,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 13
      },
      "wind": {
        "speed": 0.83,
        "deg": 129,
        "gust": 3.08
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.39
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 03:00:00"
    },
    {
      "dt": 1749448800,
      "main": {
        "temp": 22.92,
        "feels_like": 23.88,
        "temp_min": 22.92,
        "temp_max": 22.92,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 24
      },
      "wind": {
        "speed": 0.72,
        "deg": 126,
        "gust": 2.27
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 06:00:00"
    },
    {
      "dt": 1749459600,
      "main": {

2025-06-05 17:35:10,644 - wildfire_kg.tools.weather - INFO - API response for More Tomorrow: {"cod": "200", "message": 0, "cnt": 40, "list": [{"dt": 1749178800, "main": {"temp": 26.18, "feels_like": 26.18, "temp_min": 24.5, "temp_max": 26.18, "pressure": 1012, "sea_level": 1012, "grnd_level":...
2025-06-05 17:35:10,645 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: 8 forecast entries for More Tomorrow on 2025-06-07
2025-06-05 17:35:25,089 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:35:25,090 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:35:25,090 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'tomorrow': 2025-06-07
2025-06-05 17:35:25,090 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-07 for query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:35:25,091 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-07
2025-06-05 17:35:25,091 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 1
2025-06-05 17:35:25,091 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:35:25,092 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-07 00:00:00+00:00
2025-06-05 17:35:25,092 - wildfire_kg.tools.weather - INFO - - Location: tomorrow
2025-06-05 17:35:25,093 - wildfire_kg.tools.weather - INFO - - Type: Forecast
2025-06-05 17:35:25,093 - wildfire_kg.tools.weather - INFO - DEBUG: Checking forecast range - Requested date: 2025-06-07, Max forecast date: 2025-06-11
2025-06-05 17:35:25,177 - wildfire_kg.tools.weather - INFO - Making forecast API call...
2025-06-05 17:35:25,178 - wildfire_kg.tools.weather - INFO - Calling forecast endpoint: https://pro.openweathermap.org/data/2.5/forecast with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 17.3478229, 'lon': -88.6949636}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/forecast
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 17.3478229,
  "lon": -88.6949636
}
Status Code: 200
Response: {
  "cod": "200",
  "message": 0,
  "cnt": 40,
  "list": [
    {
      "dt": 1749178800,
      "main": {
        "temp": 26.18,
        "feels_like": 26.18,
        "temp_min": 24.5,
        "temp_max": 26.18,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 84,
        "temp_kf": 1.68
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.79,
        "deg": 94,
        "gust": 9.19
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 03:00:00"
    },
    {
      "dt": 1749189600,
      "main": {
        "temp": 24.58,
        "feels_like": 25.52,
        "temp_min": 23.36,
        "temp_max": 24.58,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 93,
        "temp_kf": 1.22
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 99
      },
      "wind": {
        "speed": 1.29,
        "deg": 94,
        "gust": 8.85
      },
      "visibility": 10000,
      "pop": 0.81,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 06:00:00"
    },
    {
      "dt": 1749200400,
      "main": {
        "temp": 23.12,
        "feels_like": 24.07,
        "temp_min": 23.12,
        "temp_max": 23.12,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.01,
        "deg": 104,
        "gust": 7.22
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.51
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 09:00:00"
    },
    {
      "dt": 1749211200,
      "main": {
        "temp": 23.82,
        "feels_like": 24.84,
        "temp_min": 23.82,
        "temp_max": 23.82,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 0.93,
        "deg": 97,
        "gust": 8.95
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.31
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 12:00:00"
    },
    {
      "dt": 1749222000,
      "main": {
        "temp": 26.84,
        "feels_like": 30.19,
        "temp_min": 26.84,
        "temp_max": 26.84,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 89,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 2.15,
        "deg": 87,
        "gust": 7.19
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.86
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 15:00:00"
    },
    {
      "dt": 1749232800,
      "main": {
        "temp": 28.09,
        "feels_like": 33.15,
        "temp_min": 28.09,
        "temp_max": 28.09,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 85,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 95
      },
      "wind": {
        "speed": 2.7,
        "deg": 82,
        "gust": 6.78
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 2.22
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 18:00:00"
    },
    {
      "dt": 1749243600,
      "main": {
        "temp": 29.48,
        "feels_like": 32.99,
        "temp_min": 29.48,
        "temp_max": 29.48,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 66,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 3.47,
        "deg": 87,
        "gust": 5.96
      },
      "visibility": 10000,
      "pop": 0.88,
      "rain": {
        "3h": 0.88
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 21:00:00"
    },
    {
      "dt": 1749254400,
      "main": {
        "temp": 24.56,
        "feels_like": 25.6,
        "temp_min": 24.56,
        "temp_max": 24.56,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 97,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 93
      },
      "wind": {
        "speed": 1.2,
        "deg": 84,
        "gust": 5.05
      },
      "visibility": 10000,
      "pop": 0.99,
      "rain": {
        "3h": 1.51
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 00:00:00"
    },
    {
      "dt": 1749265200,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 86
      },
      "wind": {
        "speed": 0.8,
        "deg": 107,
        "gust": 6.05
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.77
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 03:00:00"
    },
    {
      "dt": 1749276000,
      "main": {
        "temp": 22.8,
        "feels_like": 23.75,
        "temp_min": 22.8,
        "temp_max": 22.8,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 76
      },
      "wind": {
        "speed": 0.69,
        "deg": 94,
        "gust": 3.44
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 06:00:00"
    },
    {
      "dt": 1749286800,
      "main": {
        "temp": 22.96,
        "feels_like": 23.92,
        "temp_min": 22.96,
        "temp_max": 22.96,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 57
      },
      "wind": {
        "speed": 0.6,
        "deg": 114,
        "gust": 0.98
      },
      "visibility": 10000,
      "pop": 0.51,
      "rain": {
        "3h": 0.44
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 09:00:00"
    },
    {
      "dt": 1749297600,
      "main": {
        "temp": 23.26,
        "feels_like": 24.23,
        "temp_min": 23.26,
        "temp_max": 23.26,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 51
      },
      "wind": {
        "speed": 1.09,
        "deg": 99,
        "gust": 8.18
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 1.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 12:00:00"
    },
    {
      "dt": 1749308400,
      "main": {
        "temp": 26.34,
        "feels_like": 26.34,
        "temp_min": 26.34,
        "temp_max": 26.34,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 93,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 32
      },
      "wind": {
        "speed": 2.25,
        "deg": 87,
        "gust": 7.96
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.81
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 15:00:00"
    },
    {
      "dt": 1749319200,
      "main": {
        "temp": 27.25,
        "feels_like": 31.22,
        "temp_min": 27.25,
        "temp_max": 27.25,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 88,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 501,
          "main": "Rain",
          "description": "moderate rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 30
      },
      "wind": {
        "speed": 2.79,
        "deg": 84,
        "gust": 7.09
      },
      "visibility": 9165,
      "pop": 1,
      "rain": {
        "3h": 3.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 18:00:00"
    },
    {
      "dt": 1749330000,
      "main": {
        "temp": 28.53,
        "feels_like": 32.56,
        "temp_min": 28.53,
        "temp_max": 28.53,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 75,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 16
      },
      "wind": {
        "speed": 2.78,
        "deg": 80,
        "gust": 6.4
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.9
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 21:00:00"
    },
    {
      "dt": 1749340800,
      "main": {
        "temp": 24.78,
        "feels_like": 25.77,
        "temp_min": 24.78,
        "temp_max": 24.78,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 94,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 18
      },
      "wind": {
        "speed": 1.69,
        "deg": 88,
        "gust": 6.92
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.6
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 00:00:00"
    },
    {
      "dt": 1749351600,
      "main": {
        "temp": 22.91,
        "feels_like": 23.89,
        "temp_min": 22.91,
        "temp_max": 22.91,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 101,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 27
      },
      "wind": {
        "speed": 0.8,
        "deg": 117,
        "gust": 6.45
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 1.07
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 03:00:00"
    },
    {
      "dt": 1749362400,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 39
      },
      "wind": {
        "speed": 0.38,
        "deg": 143,
        "gust": 0.74
      },
      "visibility": 10000,
      "pop": 0.59,
      "rain": {
        "3h": 0.46
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 06:00:00"
    },
    {
      "dt": 1749373200,
      "main": {
        "temp": 23.1,
        "feels_like": 24.08,
        "temp_min": 23.1,
        "temp_max": 23.1,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 72
      },
      "wind": {
        "speed": 0.31,
        "deg": 15,
        "gust": 0.05
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.23
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 09:00:00"
    },
    {
      "dt": 1749384000,
      "main": {
        "temp": 23.57,
        "feels_like": 24.59,
        "temp_min": 23.57,
        "temp_max": 23.57,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 69
      },
      "wind": {
        "speed": 0.62,
        "deg": 71,
        "gust": 4.59
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.32
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 12:00:00"
    },
    {
      "dt": 1749394800,
      "main": {
        "temp": 29.24,
        "feels_like": 33.66,
        "temp_min": 29.24,
        "temp_max": 29.24,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 72,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 62
      },
      "wind": {
        "speed": 2.8,
        "deg": 98,
        "gust": 6.11
      },
      "visibility": 10000,
      "pop": 0.93,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 15:00:00"
    },
    {
      "dt": 1749405600,
      "main": {
        "temp": 31.91,
        "feels_like": 35.72,
        "temp_min": 31.91,
        "temp_max": 31.91,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 56,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 54
      },
      "wind": {
        "speed": 3.75,
        "deg": 87,
        "gust": 6
      },
      "visibility": 10000,
      "pop": 0.58,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 18:00:00"
    },
    {
      "dt": 1749416400,
      "main": {
        "temp": 30.55,
        "feels_like": 33.91,
        "temp_min": 30.55,
        "temp_max": 30.55,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1006,
        "humidity": 60,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 47
      },
      "wind": {
        "speed": 3.47,
        "deg": 86,
        "gust": 5.76
      },
      "visibility": 10000,
      "pop": 0.39,
      "rain": {
        "3h": 0.24
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 21:00:00"
    },
    {
      "dt": 1749427200,
      "main": {
        "temp": 26.67,
        "feels_like": 29.18,
        "temp_min": 26.67,
        "temp_max": 26.67,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 82,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "clouds": {
        "all": 34
      },
      "wind": {
        "speed": 2.27,
        "deg": 90,
        "gust": 6.67
      },
      "visibility": 10000,
      "pop": 0.31,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-09 00:00:00"
    },
    {
      "dt": 1749438000,
      "main": {
        "temp": 23.11,
        "feels_like": 24.09,
        "temp_min": 23.11,
        "temp_max": 23.11,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 13
      },
      "wind": {
        "speed": 0.83,
        "deg": 129,
        "gust": 3.08
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.39
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 03:00:00"
    },
    {
      "dt": 1749448800,
      "main": {
        "temp": 22.92,
        "feels_like": 23.88,
        "temp_min": 22.92,
        "temp_max": 22.92,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 24
      },
      "wind": {
        "speed": 0.72,
        "deg": 126,
        "gust": 2.27
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 06:00:00"
    },
    {
      "dt": 1749459600,
      "main": {

2025-06-05 17:35:25,346 - wildfire_kg.tools.weather - INFO - API response for More Tomorrow: {"cod": "200", "message": 0, "cnt": 40, "list": [{"dt": 1749178800, "main": {"temp": 26.18, "feels_like": 26.18, "temp_min": 24.5, "temp_max": 26.18, "pressure": 1012, "sea_level": 1012, "grnd_level":...
2025-06-05 17:35:25,347 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: 8 forecast entries for More Tomorrow on 2025-06-07
2025-06-05 17:35:28,345 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:35:28,346 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:35:28,347 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'tomorrow': 2025-06-07
2025-06-05 17:35:28,347 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-07 for query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:35:28,347 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-07
2025-06-05 17:35:28,348 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 1
2025-06-05 17:35:28,348 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:35:28,349 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-07 00:00:00+00:00
2025-06-05 17:35:28,350 - wildfire_kg.tools.weather - INFO - - Location: tomorrow
2025-06-05 17:35:28,350 - wildfire_kg.tools.weather - INFO - - Type: Forecast
2025-06-05 17:35:28,351 - wildfire_kg.tools.weather - INFO - DEBUG: Checking forecast range - Requested date: 2025-06-07, Max forecast date: 2025-06-11
2025-06-05 17:35:28,433 - wildfire_kg.tools.weather - INFO - Making forecast API call...
2025-06-05 17:35:28,434 - wildfire_kg.tools.weather - INFO - Calling forecast endpoint: https://pro.openweathermap.org/data/2.5/forecast with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 17.3478229, 'lon': -88.6949636}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/forecast
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 17.3478229,
  "lon": -88.6949636
}
Status Code: 200
Response: {
  "cod": "200",
  "message": 0,
  "cnt": 40,
  "list": [
    {
      "dt": 1749178800,
      "main": {
        "temp": 26.18,
        "feels_like": 26.18,
        "temp_min": 24.5,
        "temp_max": 26.18,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 84,
        "temp_kf": 1.68
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.79,
        "deg": 94,
        "gust": 9.19
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 03:00:00"
    },
    {
      "dt": 1749189600,
      "main": {
        "temp": 24.58,
        "feels_like": 25.52,
        "temp_min": 23.36,
        "temp_max": 24.58,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 93,
        "temp_kf": 1.22
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 99
      },
      "wind": {
        "speed": 1.29,
        "deg": 94,
        "gust": 8.85
      },
      "visibility": 10000,
      "pop": 0.81,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 06:00:00"
    },
    {
      "dt": 1749200400,
      "main": {
        "temp": 23.12,
        "feels_like": 24.07,
        "temp_min": 23.12,
        "temp_max": 23.12,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.01,
        "deg": 104,
        "gust": 7.22
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.51
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 09:00:00"
    },
    {
      "dt": 1749211200,
      "main": {
        "temp": 23.82,
        "feels_like": 24.84,
        "temp_min": 23.82,
        "temp_max": 23.82,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 0.93,
        "deg": 97,
        "gust": 8.95
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.31
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 12:00:00"
    },
    {
      "dt": 1749222000,
      "main": {
        "temp": 26.84,
        "feels_like": 30.19,
        "temp_min": 26.84,
        "temp_max": 26.84,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 89,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 2.15,
        "deg": 87,
        "gust": 7.19
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.86
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 15:00:00"
    },
    {
      "dt": 1749232800,
      "main": {
        "temp": 28.09,
        "feels_like": 33.15,
        "temp_min": 28.09,
        "temp_max": 28.09,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 85,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 95
      },
      "wind": {
        "speed": 2.7,
        "deg": 82,
        "gust": 6.78
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 2.22
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 18:00:00"
    },
    {
      "dt": 1749243600,
      "main": {
        "temp": 29.48,
        "feels_like": 32.99,
        "temp_min": 29.48,
        "temp_max": 29.48,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 66,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 3.47,
        "deg": 87,
        "gust": 5.96
      },
      "visibility": 10000,
      "pop": 0.88,
      "rain": {
        "3h": 0.88
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 21:00:00"
    },
    {
      "dt": 1749254400,
      "main": {
        "temp": 24.56,
        "feels_like": 25.6,
        "temp_min": 24.56,
        "temp_max": 24.56,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 97,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 93
      },
      "wind": {
        "speed": 1.2,
        "deg": 84,
        "gust": 5.05
      },
      "visibility": 10000,
      "pop": 0.99,
      "rain": {
        "3h": 1.51
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 00:00:00"
    },
    {
      "dt": 1749265200,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 86
      },
      "wind": {
        "speed": 0.8,
        "deg": 107,
        "gust": 6.05
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.77
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 03:00:00"
    },
    {
      "dt": 1749276000,
      "main": {
        "temp": 22.8,
        "feels_like": 23.75,
        "temp_min": 22.8,
        "temp_max": 22.8,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 76
      },
      "wind": {
        "speed": 0.69,
        "deg": 94,
        "gust": 3.44
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 06:00:00"
    },
    {
      "dt": 1749286800,
      "main": {
        "temp": 22.96,
        "feels_like": 23.92,
        "temp_min": 22.96,
        "temp_max": 22.96,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 57
      },
      "wind": {
        "speed": 0.6,
        "deg": 114,
        "gust": 0.98
      },
      "visibility": 10000,
      "pop": 0.51,
      "rain": {
        "3h": 0.44
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 09:00:00"
    },
    {
      "dt": 1749297600,
      "main": {
        "temp": 23.26,
        "feels_like": 24.23,
        "temp_min": 23.26,
        "temp_max": 23.26,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 51
      },
      "wind": {
        "speed": 1.09,
        "deg": 99,
        "gust": 8.18
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 1.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 12:00:00"
    },
    {
      "dt": 1749308400,
      "main": {
        "temp": 26.34,
        "feels_like": 26.34,
        "temp_min": 26.34,
        "temp_max": 26.34,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 93,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 32
      },
      "wind": {
        "speed": 2.25,
        "deg": 87,
        "gust": 7.96
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.81
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 15:00:00"
    },
    {
      "dt": 1749319200,
      "main": {
        "temp": 27.25,
        "feels_like": 31.22,
        "temp_min": 27.25,
        "temp_max": 27.25,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 88,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 501,
          "main": "Rain",
          "description": "moderate rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 30
      },
      "wind": {
        "speed": 2.79,
        "deg": 84,
        "gust": 7.09
      },
      "visibility": 9165,
      "pop": 1,
      "rain": {
        "3h": 3.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 18:00:00"
    },
    {
      "dt": 1749330000,
      "main": {
        "temp": 28.53,
        "feels_like": 32.56,
        "temp_min": 28.53,
        "temp_max": 28.53,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 75,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 16
      },
      "wind": {
        "speed": 2.78,
        "deg": 80,
        "gust": 6.4
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.9
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 21:00:00"
    },
    {
      "dt": 1749340800,
      "main": {
        "temp": 24.78,
        "feels_like": 25.77,
        "temp_min": 24.78,
        "temp_max": 24.78,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 94,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 18
      },
      "wind": {
        "speed": 1.69,
        "deg": 88,
        "gust": 6.92
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.6
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 00:00:00"
    },
    {
      "dt": 1749351600,
      "main": {
        "temp": 22.91,
        "feels_like": 23.89,
        "temp_min": 22.91,
        "temp_max": 22.91,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 101,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 27
      },
      "wind": {
        "speed": 0.8,
        "deg": 117,
        "gust": 6.45
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 1.07
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 03:00:00"
    },
    {
      "dt": 1749362400,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 39
      },
      "wind": {
        "speed": 0.38,
        "deg": 143,
        "gust": 0.74
      },
      "visibility": 10000,
      "pop": 0.59,
      "rain": {
        "3h": 0.46
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 06:00:00"
    },
    {
      "dt": 1749373200,
      "main": {
        "temp": 23.1,
        "feels_like": 24.08,
        "temp_min": 23.1,
        "temp_max": 23.1,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 72
      },
      "wind": {
        "speed": 0.31,
        "deg": 15,
        "gust": 0.05
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.23
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 09:00:00"
    },
    {
      "dt": 1749384000,
      "main": {
        "temp": 23.57,
        "feels_like": 24.59,
        "temp_min": 23.57,
        "temp_max": 23.57,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 69
      },
      "wind": {
        "speed": 0.62,
        "deg": 71,
        "gust": 4.59
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.32
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 12:00:00"
    },
    {
      "dt": 1749394800,
      "main": {
        "temp": 29.24,
        "feels_like": 33.66,
        "temp_min": 29.24,
        "temp_max": 29.24,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 72,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 62
      },
      "wind": {
        "speed": 2.8,
        "deg": 98,
        "gust": 6.11
      },
      "visibility": 10000,
      "pop": 0.93,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 15:00:00"
    },
    {
      "dt": 1749405600,
      "main": {
        "temp": 31.91,
        "feels_like": 35.72,
        "temp_min": 31.91,
        "temp_max": 31.91,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 56,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 54
      },
      "wind": {
        "speed": 3.75,
        "deg": 87,
        "gust": 6
      },
      "visibility": 10000,
      "pop": 0.58,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 18:00:00"
    },
    {
      "dt": 1749416400,
      "main": {
        "temp": 30.55,
        "feels_like": 33.91,
        "temp_min": 30.55,
        "temp_max": 30.55,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1006,
        "humidity": 60,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 47
      },
      "wind": {
        "speed": 3.47,
        "deg": 86,
        "gust": 5.76
      },
      "visibility": 10000,
      "pop": 0.39,
      "rain": {
        "3h": 0.24
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 21:00:00"
    },
    {
      "dt": 1749427200,
      "main": {
        "temp": 26.67,
        "feels_like": 29.18,
        "temp_min": 26.67,
        "temp_max": 26.67,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 82,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "clouds": {
        "all": 34
      },
      "wind": {
        "speed": 2.27,
        "deg": 90,
        "gust": 6.67
      },
      "visibility": 10000,
      "pop": 0.31,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-09 00:00:00"
    },
    {
      "dt": 1749438000,
      "main": {
        "temp": 23.11,
        "feels_like": 24.09,
        "temp_min": 23.11,
        "temp_max": 23.11,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 13
      },
      "wind": {
        "speed": 0.83,
        "deg": 129,
        "gust": 3.08
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.39
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 03:00:00"
    },
    {
      "dt": 1749448800,
      "main": {
        "temp": 22.92,
        "feels_like": 23.88,
        "temp_min": 22.92,
        "temp_max": 22.92,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 24
      },
      "wind": {
        "speed": 0.72,
        "deg": 126,
        "gust": 2.27
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 06:00:00"
    },
    {
      "dt": 1749459600,
      "main": {

2025-06-05 17:35:28,600 - wildfire_kg.tools.weather - INFO - API response for More Tomorrow: {"cod": "200", "message": 0, "cnt": 40, "list": [{"dt": 1749178800, "main": {"temp": 26.18, "feels_like": 26.18, "temp_min": 24.5, "temp_max": 26.18, "pressure": 1012, "sea_level": 1012, "grnd_level":...
2025-06-05 17:35:28,601 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: 8 forecast entries for More Tomorrow on 2025-06-07
2025-06-05 17:35:38,178 - wildfire_kg.tools.kg - INFO - Querying knowledge graph with: What is the basal area value for CASBC_0006_20240911_1? and config: {'tags': [], 'metadata': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, 'langgraph_step': 4, 'langgraph_node': 'tools', 'langgraph_triggers': ('branch:to:tools',), 'langgraph_path': ('__pregel_pull', 'tools'), 'langgraph_checkpoint_ns': 'tools:e9cc1138-452f-b0b9-b9fb-f5436d5ce288', 'checkpoint_ns': 'tools:e9cc1138-452f-b0b9-b9fb-f5436d5ce288'}, 'callbacks': <langchain_core.callbacks.manager.AsyncCallbackManager object at 0x10a747c90>, 'recursion_limit': 25, 'configurable': {'agent_model_name': 'llama3-sdsc', 'agent_temperature': 0.1, 'kg_model_name': 'llama3-sdsc', 'kg_temperature': 0.1, 'verbose': True, '__pregel_task_id': 'e9cc1138-452f-b0b9-b9fb-f5436d5ce288', '__pregel_send': functools.partial(<function local_write at 0x162605940>, <built-in method extend of collections.deque object at 0x16be247c0>, ('__start__', 'agent', 'tools')), '__pregel_read': functools.partial(<function local_read at 0x1626058a0>, {'messages': <langgraph.channels.binop.BinaryOperatorAggregate object at 0x10c12a9c0>, '__start__': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c409800>, 'branch:to:agent': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c40a5c0>, 'branch:to:tools': <langgraph.channels.ephemeral_value.EphemeralValue object at 0x10c40bb00>}, {'is_last_step': <langgraph.managed.is_last_step.IsLastStepManager object at 0x109672790>, 'remaining_steps': <langgraph.managed.is_last_step.RemainingStepsManager object at 0x10c40b7d0>}, PregelTaskWrites(path=('__pregel_pull', 'tools'), name='tools', writes=deque([]), triggers=('branch:to:tools',))), '__pregel_store': None, '__pregel_checkpointer': None, 'checkpoint_map': {'': '1f0426e2-ae1c-6d60-8003-7a10e046e2f0'}, 'checkpoint_id': None, 'checkpoint_ns': 'tools:e9cc1138-452f-b0b9-b9fb-f5436d5ce288', '__pregel_scratchpad': PregelScratchpad(call_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10b210310>, interrupt_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x10b2a94b0>, get_null_resume=<function _scratchpad.<locals>.get_null_resume at 0x10c1d99e0>, resume=[], subgraph_counter=<langgraph.pregel.algo.LazyAtomicCounter object at 0x16b8e9f90>), '__pregel_previous': None, '__pregel_call': functools.partial(<function _acall at 0x16262e660>, <weakref at 0x10a068b80; to 'PregelExecutableTask' at 0x16be98310>, stream=False, retry=None, futures=<weakref at 0x1618362a0; to 'FuturesDict' at 0x10c35e6f0>, schedule_task=<weakref at 0x10bd9ea40; to 'AsyncPregelLoop' at 0x10c409190>, submit=<weakref at 0x10bd9e420; to 'AsyncBackgroundExecutor' at 0x10c062d10>, reraise=True, loop=<_UnixSelectorEventLoop running=True closed=False debug=False>)}}
2025-06-05 17:35:38,179 - wildfire_kg.tools.kg - DEBUG - Using GraphDB endpoint: https://graphdb-wildfire-kg.nrp-nautilus.io/repositories/wildfire-kg-prod
2025-06-05 17:35:38,179 - wildfire_kg.tools.kg - DEBUG - Using ontology file at: /Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/wildfire_kg_api/orchestration/tools/knowledge-representation/wildfire_kg_ontology.owl
2025-06-05 17:35:38,400 - wildfire_kg.tools.kg - DEBUG - GraphDB connection initialized successfully
2025-06-05 17:35:38,401 - wildfire_kg.tools.kg - INFO - KG tool using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:35:38,401 - wildfire_kg.tools.kg - INFO - Final LLM params for KG tool QA chain: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:35:38,444 - wildfire_kg.tools.kg - DEBUG - QA chain initialized successfully
2025-06-05 17:35:38,445 - wildfire_kg.tools.kg - DEBUG - Executing query through QA chain...

> Entering new OntotextGraphDBQAChain chain...
Generated SPARQL:
PREFIX wifire: <http://wifire.ucsd.edu/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?basalArea
WHERE {
  ?plot wifire:plotName "CASBC_0006_20240911_1" .
  ?plot wifire:hasVegetationMetrics ?vegetationMetrics .
  ?vegetationMetrics wifire:basalArea ?basalArea .
}
LIMIT 50

2025-06-05 17:35:38,834 - wildfire_kg.tools.kg - DEBUG - Generated SPARQL query:
2025-06-05 17:35:38,835 - wildfire_kg.tools.kg - INFO - Follow-up questions using model: llama3-sdsc, requested temperature: 0.1
2025-06-05 17:35:38,836 - wildfire_kg.tools.kg - INFO - Final LLM params for follow-up questions: {'model': 'llama3-sdsc', 'temperature': 0.1, 'openai_api_base': 'https://llm.nrp-nautilus.io', 'api_key': 'sk-_Mm7RE39d6cc-I_lRnOQcw'}
2025-06-05 17:35:38,843 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:35:38,843 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:35:38,843 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'tomorrow': 2025-06-07
2025-06-05 17:35:38,844 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-07 for query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:35:38,844 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-07
2025-06-05 17:35:38,845 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 1
2025-06-05 17:35:38,845 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:35:38,846 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-07 00:00:00+00:00
2025-06-05 17:35:38,846 - wildfire_kg.tools.weather - INFO - - Location: tomorrow
2025-06-05 17:35:38,846 - wildfire_kg.tools.weather - INFO - - Type: Forecast
2025-06-05 17:35:38,847 - wildfire_kg.tools.weather - INFO - DEBUG: Checking forecast range - Requested date: 2025-06-07, Max forecast date: 2025-06-11
2025-06-05 17:35:38,928 - wildfire_kg.tools.weather - INFO - Making forecast API call...
2025-06-05 17:35:38,928 - wildfire_kg.tools.weather - INFO - Calling forecast endpoint: https://pro.openweathermap.org/data/2.5/forecast with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 17.3478229, 'lon': -88.6949636}

> Finished chain.

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/forecast
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 17.3478229,
  "lon": -88.6949636
}
Status Code: 200
Response: {
  "cod": "200",
  "message": 0,
  "cnt": 40,
  "list": [
    {
      "dt": 1749178800,
      "main": {
        "temp": 26.18,
        "feels_like": 26.18,
        "temp_min": 24.5,
        "temp_max": 26.18,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 84,
        "temp_kf": 1.68
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.79,
        "deg": 94,
        "gust": 9.19
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 03:00:00"
    },
    {
      "dt": 1749189600,
      "main": {
        "temp": 24.58,
        "feels_like": 25.52,
        "temp_min": 23.36,
        "temp_max": 24.58,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 93,
        "temp_kf": 1.22
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 99
      },
      "wind": {
        "speed": 1.29,
        "deg": 94,
        "gust": 8.85
      },
      "visibility": 10000,
      "pop": 0.81,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 06:00:00"
    },
    {
      "dt": 1749200400,
      "main": {
        "temp": 23.12,
        "feels_like": 24.07,
        "temp_min": 23.12,
        "temp_max": 23.12,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.01,
        "deg": 104,
        "gust": 7.22
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.51
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 09:00:00"
    },
    {
      "dt": 1749211200,
      "main": {
        "temp": 23.82,
        "feels_like": 24.84,
        "temp_min": 23.82,
        "temp_max": 23.82,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 0.93,
        "deg": 97,
        "gust": 8.95
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.31
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 12:00:00"
    },
    {
      "dt": 1749222000,
      "main": {
        "temp": 26.84,
        "feels_like": 30.19,
        "temp_min": 26.84,
        "temp_max": 26.84,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 89,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 2.15,
        "deg": 87,
        "gust": 7.19
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.86
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 15:00:00"
    },
    {
      "dt": 1749232800,
      "main": {
        "temp": 28.09,
        "feels_like": 33.15,
        "temp_min": 28.09,
        "temp_max": 28.09,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 85,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 95
      },
      "wind": {
        "speed": 2.7,
        "deg": 82,
        "gust": 6.78
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 2.22
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 18:00:00"
    },
    {
      "dt": 1749243600,
      "main": {
        "temp": 29.48,
        "feels_like": 32.99,
        "temp_min": 29.48,
        "temp_max": 29.48,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 66,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 3.47,
        "deg": 87,
        "gust": 5.96
      },
      "visibility": 10000,
      "pop": 0.88,
      "rain": {
        "3h": 0.88
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 21:00:00"
    },
    {
      "dt": 1749254400,
      "main": {
        "temp": 24.56,
        "feels_like": 25.6,
        "temp_min": 24.56,
        "temp_max": 24.56,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 97,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 93
      },
      "wind": {
        "speed": 1.2,
        "deg": 84,
        "gust": 5.05
      },
      "visibility": 10000,
      "pop": 0.99,
      "rain": {
        "3h": 1.51
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 00:00:00"
    },
    {
      "dt": 1749265200,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 86
      },
      "wind": {
        "speed": 0.8,
        "deg": 107,
        "gust": 6.05
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.77
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 03:00:00"
    },
    {
      "dt": 1749276000,
      "main": {
        "temp": 22.8,
        "feels_like": 23.75,
        "temp_min": 22.8,
        "temp_max": 22.8,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 76
      },
      "wind": {
        "speed": 0.69,
        "deg": 94,
        "gust": 3.44
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 06:00:00"
    },
    {
      "dt": 1749286800,
      "main": {
        "temp": 22.96,
        "feels_like": 23.92,
        "temp_min": 22.96,
        "temp_max": 22.96,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 57
      },
      "wind": {
        "speed": 0.6,
        "deg": 114,
        "gust": 0.98
      },
      "visibility": 10000,
      "pop": 0.51,
      "rain": {
        "3h": 0.44
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 09:00:00"
    },
    {
      "dt": 1749297600,
      "main": {
        "temp": 23.26,
        "feels_like": 24.23,
        "temp_min": 23.26,
        "temp_max": 23.26,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 51
      },
      "wind": {
        "speed": 1.09,
        "deg": 99,
        "gust": 8.18
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 1.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 12:00:00"
    },
    {
      "dt": 1749308400,
      "main": {
        "temp": 26.34,
        "feels_like": 26.34,
        "temp_min": 26.34,
        "temp_max": 26.34,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 93,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 32
      },
      "wind": {
        "speed": 2.25,
        "deg": 87,
        "gust": 7.96
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.81
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 15:00:00"
    },
    {
      "dt": 1749319200,
      "main": {
        "temp": 27.25,
        "feels_like": 31.22,
        "temp_min": 27.25,
        "temp_max": 27.25,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 88,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 501,
          "main": "Rain",
          "description": "moderate rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 30
      },
      "wind": {
        "speed": 2.79,
        "deg": 84,
        "gust": 7.09
      },
      "visibility": 9165,
      "pop": 1,
      "rain": {
        "3h": 3.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 18:00:00"
    },
    {
      "dt": 1749330000,
      "main": {
        "temp": 28.53,
        "feels_like": 32.56,
        "temp_min": 28.53,
        "temp_max": 28.53,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 75,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 16
      },
      "wind": {
        "speed": 2.78,
        "deg": 80,
        "gust": 6.4
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.9
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 21:00:00"
    },
    {
      "dt": 1749340800,
      "main": {
        "temp": 24.78,
        "feels_like": 25.77,
        "temp_min": 24.78,
        "temp_max": 24.78,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 94,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 18
      },
      "wind": {
        "speed": 1.69,
        "deg": 88,
        "gust": 6.92
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.6
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 00:00:00"
    },
    {
      "dt": 1749351600,
      "main": {
        "temp": 22.91,
        "feels_like": 23.89,
        "temp_min": 22.91,
        "temp_max": 22.91,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 101,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 27
      },
      "wind": {
        "speed": 0.8,
        "deg": 117,
        "gust": 6.45
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 1.07
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 03:00:00"
    },
    {
      "dt": 1749362400,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 39
      },
      "wind": {
        "speed": 0.38,
        "deg": 143,
        "gust": 0.74
      },
      "visibility": 10000,
      "pop": 0.59,
      "rain": {
        "3h": 0.46
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 06:00:00"
    },
    {
      "dt": 1749373200,
      "main": {
        "temp": 23.1,
        "feels_like": 24.08,
        "temp_min": 23.1,
        "temp_max": 23.1,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 72
      },
      "wind": {
        "speed": 0.31,
        "deg": 15,
        "gust": 0.05
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.23
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 09:00:00"
    },
    {
      "dt": 1749384000,
      "main": {
        "temp": 23.57,
        "feels_like": 24.59,
        "temp_min": 23.57,
        "temp_max": 23.57,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 69
      },
      "wind": {
        "speed": 0.62,
        "deg": 71,
        "gust": 4.59
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.32
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 12:00:00"
    },
    {
      "dt": 1749394800,
      "main": {
        "temp": 29.24,
        "feels_like": 33.66,
        "temp_min": 29.24,
        "temp_max": 29.24,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 72,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 62
      },
      "wind": {
        "speed": 2.8,
        "deg": 98,
        "gust": 6.11
      },
      "visibility": 10000,
      "pop": 0.93,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 15:00:00"
    },
    {
      "dt": 1749405600,
      "main": {
        "temp": 31.91,
        "feels_like": 35.72,
        "temp_min": 31.91,
        "temp_max": 31.91,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 56,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 54
      },
      "wind": {
        "speed": 3.75,
        "deg": 87,
        "gust": 6
      },
      "visibility": 10000,
      "pop": 0.58,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 18:00:00"
    },
    {
      "dt": 1749416400,
      "main": {
        "temp": 30.55,
        "feels_like": 33.91,
        "temp_min": 30.55,
        "temp_max": 30.55,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1006,
        "humidity": 60,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 47
      },
      "wind": {
        "speed": 3.47,
        "deg": 86,
        "gust": 5.76
      },
      "visibility": 10000,
      "pop": 0.39,
      "rain": {
        "3h": 0.24
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 21:00:00"
    },
    {
      "dt": 1749427200,
      "main": {
        "temp": 26.67,
        "feels_like": 29.18,
        "temp_min": 26.67,
        "temp_max": 26.67,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 82,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "clouds": {
        "all": 34
      },
      "wind": {
        "speed": 2.27,
        "deg": 90,
        "gust": 6.67
      },
      "visibility": 10000,
      "pop": 0.31,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-09 00:00:00"
    },
    {
      "dt": 1749438000,
      "main": {
        "temp": 23.11,
        "feels_like": 24.09,
        "temp_min": 23.11,
        "temp_max": 23.11,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 13
      },
      "wind": {
        "speed": 0.83,
        "deg": 129,
        "gust": 3.08
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.39
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 03:00:00"
    },
    {
      "dt": 1749448800,
      "main": {
        "temp": 22.92,
        "feels_like": 23.88,
        "temp_min": 22.92,
        "temp_max": 22.92,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 24
      },
      "wind": {
        "speed": 0.72,
        "deg": 126,
        "gust": 2.27
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 06:00:00"
    },
    {

2025-06-05 17:35:39,087 - wildfire_kg.tools.weather - INFO - API response for More Tomorrow: {"cod": "200", "message": 0, "cnt": 40, "list": [{"dt": 1749178800, "main": {"temp": 26.18, "feels_like": 26.18, "temp_min": 24.5, "temp_max": 26.18, "pressure": 1012, "sea_level": 1012, "grnd_level":...
2025-06-05 17:35:39,087 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: 8 forecast entries for More Tomorrow on 2025-06-07
2025-06-05 17:35:42,701 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:35:42,702 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:35:42,702 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'tomorrow': 2025-06-07
2025-06-05 17:35:42,702 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-07 for query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:35:42,703 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-07
2025-06-05 17:35:42,703 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 1
2025-06-05 17:35:42,703 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:35:42,704 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-07 00:00:00+00:00
2025-06-05 17:35:42,704 - wildfire_kg.tools.weather - INFO - - Location: tomorrow
2025-06-05 17:35:42,705 - wildfire_kg.tools.weather - INFO - - Type: Forecast
2025-06-05 17:35:42,705 - wildfire_kg.tools.weather - INFO - DEBUG: Checking forecast range - Requested date: 2025-06-07, Max forecast date: 2025-06-11
2025-06-05 17:35:42,797 - wildfire_kg.tools.weather - INFO - Making forecast API call...
2025-06-05 17:35:42,797 - wildfire_kg.tools.weather - INFO - Calling forecast endpoint: https://pro.openweathermap.org/data/2.5/forecast with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 17.3478229, 'lon': -88.6949636}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/forecast
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 17.3478229,
  "lon": -88.6949636
}
Status Code: 200
Response: {
  "cod": "200",
  "message": 0,
  "cnt": 40,
  "list": [
    {
      "dt": 1749178800,
      "main": {
        "temp": 26.18,
        "feels_like": 26.18,
        "temp_min": 24.5,
        "temp_max": 26.18,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 84,
        "temp_kf": 1.68
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.79,
        "deg": 94,
        "gust": 9.19
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 03:00:00"
    },
    {
      "dt": 1749189600,
      "main": {
        "temp": 24.58,
        "feels_like": 25.52,
        "temp_min": 23.36,
        "temp_max": 24.58,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 93,
        "temp_kf": 1.22
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 99
      },
      "wind": {
        "speed": 1.29,
        "deg": 94,
        "gust": 8.85
      },
      "visibility": 10000,
      "pop": 0.81,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 06:00:00"
    },
    {
      "dt": 1749200400,
      "main": {
        "temp": 23.12,
        "feels_like": 24.07,
        "temp_min": 23.12,
        "temp_max": 23.12,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.01,
        "deg": 104,
        "gust": 7.22
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.51
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 09:00:00"
    },
    {
      "dt": 1749211200,
      "main": {
        "temp": 23.82,
        "feels_like": 24.84,
        "temp_min": 23.82,
        "temp_max": 23.82,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 0.93,
        "deg": 97,
        "gust": 8.95
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.31
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 12:00:00"
    },
    {
      "dt": 1749222000,
      "main": {
        "temp": 26.84,
        "feels_like": 30.19,
        "temp_min": 26.84,
        "temp_max": 26.84,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 89,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 2.15,
        "deg": 87,
        "gust": 7.19
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.86
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 15:00:00"
    },
    {
      "dt": 1749232800,
      "main": {
        "temp": 28.09,
        "feels_like": 33.15,
        "temp_min": 28.09,
        "temp_max": 28.09,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 85,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 95
      },
      "wind": {
        "speed": 2.7,
        "deg": 82,
        "gust": 6.78
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 2.22
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 18:00:00"
    },
    {
      "dt": 1749243600,
      "main": {
        "temp": 29.48,
        "feels_like": 32.99,
        "temp_min": 29.48,
        "temp_max": 29.48,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 66,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 3.47,
        "deg": 87,
        "gust": 5.96
      },
      "visibility": 10000,
      "pop": 0.88,
      "rain": {
        "3h": 0.88
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 21:00:00"
    },
    {
      "dt": 1749254400,
      "main": {
        "temp": 24.56,
        "feels_like": 25.6,
        "temp_min": 24.56,
        "temp_max": 24.56,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 97,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 93
      },
      "wind": {
        "speed": 1.2,
        "deg": 84,
        "gust": 5.05
      },
      "visibility": 10000,
      "pop": 0.99,
      "rain": {
        "3h": 1.51
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 00:00:00"
    },
    {
      "dt": 1749265200,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 86
      },
      "wind": {
        "speed": 0.8,
        "deg": 107,
        "gust": 6.05
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.77
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 03:00:00"
    },
    {
      "dt": 1749276000,
      "main": {
        "temp": 22.8,
        "feels_like": 23.75,
        "temp_min": 22.8,
        "temp_max": 22.8,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 76
      },
      "wind": {
        "speed": 0.69,
        "deg": 94,
        "gust": 3.44
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 06:00:00"
    },
    {
      "dt": 1749286800,
      "main": {
        "temp": 22.96,
        "feels_like": 23.92,
        "temp_min": 22.96,
        "temp_max": 22.96,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 57
      },
      "wind": {
        "speed": 0.6,
        "deg": 114,
        "gust": 0.98
      },
      "visibility": 10000,
      "pop": 0.51,
      "rain": {
        "3h": 0.44
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 09:00:00"
    },
    {
      "dt": 1749297600,
      "main": {
        "temp": 23.26,
        "feels_like": 24.23,
        "temp_min": 23.26,
        "temp_max": 23.26,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 51
      },
      "wind": {
        "speed": 1.09,
        "deg": 99,
        "gust": 8.18
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 1.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 12:00:00"
    },
    {
      "dt": 1749308400,
      "main": {
        "temp": 26.34,
        "feels_like": 26.34,
        "temp_min": 26.34,
        "temp_max": 26.34,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 93,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 32
      },
      "wind": {
        "speed": 2.25,
        "deg": 87,
        "gust": 7.96
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.81
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 15:00:00"
    },
    {
      "dt": 1749319200,
      "main": {
        "temp": 27.25,
        "feels_like": 31.22,
        "temp_min": 27.25,
        "temp_max": 27.25,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 88,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 501,
          "main": "Rain",
          "description": "moderate rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 30
      },
      "wind": {
        "speed": 2.79,
        "deg": 84,
        "gust": 7.09
      },
      "visibility": 9165,
      "pop": 1,
      "rain": {
        "3h": 3.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 18:00:00"
    },
    {
      "dt": 1749330000,
      "main": {
        "temp": 28.53,
        "feels_like": 32.56,
        "temp_min": 28.53,
        "temp_max": 28.53,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 75,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 16
      },
      "wind": {
        "speed": 2.78,
        "deg": 80,
        "gust": 6.4
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.9
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 21:00:00"
    },
    {
      "dt": 1749340800,
      "main": {
        "temp": 24.78,
        "feels_like": 25.77,
        "temp_min": 24.78,
        "temp_max": 24.78,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 94,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 18
      },
      "wind": {
        "speed": 1.69,
        "deg": 88,
        "gust": 6.92
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.6
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 00:00:00"
    },
    {
      "dt": 1749351600,
      "main": {
        "temp": 22.91,
        "feels_like": 23.89,
        "temp_min": 22.91,
        "temp_max": 22.91,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 101,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 27
      },
      "wind": {
        "speed": 0.8,
        "deg": 117,
        "gust": 6.45
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 1.07
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 03:00:00"
    },
    {
      "dt": 1749362400,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 39
      },
      "wind": {
        "speed": 0.38,
        "deg": 143,
        "gust": 0.74
      },
      "visibility": 10000,
      "pop": 0.59,
      "rain": {
        "3h": 0.46
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 06:00:00"
    },
    {
      "dt": 1749373200,
      "main": {
        "temp": 23.1,
        "feels_like": 24.08,
        "temp_min": 23.1,
        "temp_max": 23.1,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 72
      },
      "wind": {
        "speed": 0.31,
        "deg": 15,
        "gust": 0.05
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.23
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 09:00:00"
    },
    {
      "dt": 1749384000,
      "main": {
        "temp": 23.57,
        "feels_like": 24.59,
        "temp_min": 23.57,
        "temp_max": 23.57,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 69
      },
      "wind": {
        "speed": 0.62,
        "deg": 71,
        "gust": 4.59
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.32
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 12:00:00"
    },
    {
      "dt": 1749394800,
      "main": {
        "temp": 29.24,
        "feels_like": 33.66,
        "temp_min": 29.24,
        "temp_max": 29.24,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 72,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 62
      },
      "wind": {
        "speed": 2.8,
        "deg": 98,
        "gust": 6.11
      },
      "visibility": 10000,
      "pop": 0.93,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 15:00:00"
    },
    {
      "dt": 1749405600,
      "main": {
        "temp": 31.91,
        "feels_like": 35.72,
        "temp_min": 31.91,
        "temp_max": 31.91,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 56,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 54
      },
      "wind": {
        "speed": 3.75,
        "deg": 87,
        "gust": 6
      },
      "visibility": 10000,
      "pop": 0.58,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 18:00:00"
    },
    {
      "dt": 1749416400,
      "main": {
        "temp": 30.55,
        "feels_like": 33.91,
        "temp_min": 30.55,
        "temp_max": 30.55,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1006,
        "humidity": 60,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 47
      },
      "wind": {
        "speed": 3.47,
        "deg": 86,
        "gust": 5.76
      },
      "visibility": 10000,
      "pop": 0.39,
      "rain": {
        "3h": 0.24
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 21:00:00"
    },
    {
      "dt": 1749427200,
      "main": {
        "temp": 26.67,
        "feels_like": 29.18,
        "temp_min": 26.67,
        "temp_max": 26.67,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 82,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "clouds": {
        "all": 34
      },
      "wind": {
        "speed": 2.27,
        "deg": 90,
        "gust": 6.67
      },
      "visibility": 10000,
      "pop": 0.31,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-09 00:00:00"
    },
    {
      "dt": 1749438000,
      "main": {
        "temp": 23.11,
        "feels_like": 24.09,
        "temp_min": 23.11,
        "temp_max": 23.11,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 13
      },
      "wind": {
        "speed": 0.83,
        "deg": 129,
        "gust": 3.08
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.39
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 03:00:00"
    },
    {
      "dt": 1749448800,
      "main": {
        "temp": 22.92,
        "feels_like": 23.88,
        "temp_min": 22.92,
        "temp_max": 22.92,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 24
      },
      "wind": {
        "speed": 0.72,
        "deg": 126,
        "gust": 2.27
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 06:00:00"
    },
    {
      "dt": 1749459600,
      "main": {

2025-06-05 17:35:42,969 - wildfire_kg.tools.weather - INFO - API response for More Tomorrow: {"cod": "200", "message": 0, "cnt": 40, "list": [{"dt": 1749178800, "main": {"temp": 26.18, "feels_like": 26.18, "temp_min": 24.5, "temp_max": 26.18, "pressure": 1012, "sea_level": 1012, "grnd_level":...
2025-06-05 17:35:42,971 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: 8 forecast entries for More Tomorrow on 2025-06-07
2025-06-05 17:35:50,476 - wildfire_kg.tools.weather - INFO -
==================================================
Processing weather query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:35:50,477 - wildfire_kg.tools.weather - INFO - DEBUG: Current UTC date: 2025-06-06
2025-06-05 17:35:50,478 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Extracted date for 'tomorrow': 2025-06-07
2025-06-05 17:35:50,478 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: Final extracted date: 2025-06-07 for query: Los Angeles, CA weather forecast for tomorrow
2025-06-05 17:35:50,478 - wildfire_kg.tools.weather - INFO - DEBUG: Requested date: 2025-06-07
2025-06-05 17:35:50,478 - wildfire_kg.tools.weather - INFO - DEBUG: Days from today: 1
2025-06-05 17:35:50,479 - wildfire_kg.tools.weather - INFO - Query Analysis:
2025-06-05 17:35:50,479 - wildfire_kg.tools.weather - INFO - - Date: 2025-06-07 00:00:00+00:00
2025-06-05 17:35:50,480 - wildfire_kg.tools.weather - INFO - - Location: tomorrow
2025-06-05 17:35:50,481 - wildfire_kg.tools.weather - INFO - - Type: Forecast
2025-06-05 17:35:50,481 - wildfire_kg.tools.weather - INFO - DEBUG: Checking forecast range - Requested date: 2025-06-07, Max forecast date: 2025-06-11
2025-06-05 17:35:50,563 - wildfire_kg.tools.weather - INFO - Making forecast API call...
2025-06-05 17:35:50,564 - wildfire_kg.tools.weather - INFO - Calling forecast endpoint: https://pro.openweathermap.org/data/2.5/forecast with params: {'appid': 'c558************************1427', 'units': 'metric', 'lat': 17.3478229, 'lon': -88.6949636}

==================================================
API Call Details:
Endpoint: https://pro.openweathermap.org/data/2.5/forecast
Parameters: {
  "appid": "c558************************1427",
  "units": "metric",
  "lat": 17.3478229,
  "lon": -88.6949636
}
Status Code: 200
Response: {
  "cod": "200",
  "message": 0,
  "cnt": 40,
  "list": [
    {
      "dt": 1749178800,
      "main": {
        "temp": 26.18,
        "feels_like": 26.18,
        "temp_min": 24.5,
        "temp_max": 26.18,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 84,
        "temp_kf": 1.68
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.79,
        "deg": 94,
        "gust": 9.19
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 03:00:00"
    },
    {
      "dt": 1749189600,
      "main": {
        "temp": 24.58,
        "feels_like": 25.52,
        "temp_min": 23.36,
        "temp_max": 24.58,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1009,
        "humidity": 93,
        "temp_kf": 1.22
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 99
      },
      "wind": {
        "speed": 1.29,
        "deg": 94,
        "gust": 8.85
      },
      "visibility": 10000,
      "pop": 0.81,
      "rain": {
        "3h": 0.79
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 06:00:00"
    },
    {
      "dt": 1749200400,
      "main": {
        "temp": 23.12,
        "feels_like": 24.07,
        "temp_min": 23.12,
        "temp_max": 23.12,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 1.01,
        "deg": 104,
        "gust": 7.22
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.51
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-06 09:00:00"
    },
    {
      "dt": 1749211200,
      "main": {
        "temp": 23.82,
        "feels_like": 24.84,
        "temp_min": 23.82,
        "temp_max": 23.82,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 0.93,
        "deg": 97,
        "gust": 8.95
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.31
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 12:00:00"
    },
    {
      "dt": 1749222000,
      "main": {
        "temp": 26.84,
        "feels_like": 30.19,
        "temp_min": 26.84,
        "temp_max": 26.84,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 89,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 2.15,
        "deg": 87,
        "gust": 7.19
      },
      "visibility": 10000,
      "pop": 0.91,
      "rain": {
        "3h": 0.86
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 15:00:00"
    },
    {
      "dt": 1749232800,
      "main": {
        "temp": 28.09,
        "feels_like": 33.15,
        "temp_min": 28.09,
        "temp_max": 28.09,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 85,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 95
      },
      "wind": {
        "speed": 2.7,
        "deg": 82,
        "gust": 6.78
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 2.22
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 18:00:00"
    },
    {
      "dt": 1749243600,
      "main": {
        "temp": 29.48,
        "feels_like": 32.99,
        "temp_min": 29.48,
        "temp_max": 29.48,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 66,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 3.47,
        "deg": 87,
        "gust": 5.96
      },
      "visibility": 10000,
      "pop": 0.88,
      "rain": {
        "3h": 0.88
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-06 21:00:00"
    },
    {
      "dt": 1749254400,
      "main": {
        "temp": 24.56,
        "feels_like": 25.6,
        "temp_min": 24.56,
        "temp_max": 24.56,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 97,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 93
      },
      "wind": {
        "speed": 1.2,
        "deg": 84,
        "gust": 5.05
      },
      "visibility": 10000,
      "pop": 0.99,
      "rain": {
        "3h": 1.51
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 00:00:00"
    },
    {
      "dt": 1749265200,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 86
      },
      "wind": {
        "speed": 0.8,
        "deg": 107,
        "gust": 6.05
      },
      "visibility": 10000,
      "pop": 0.76,
      "rain": {
        "3h": 0.77
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 03:00:00"
    },
    {
      "dt": 1749276000,
      "main": {
        "temp": 22.8,
        "feels_like": 23.75,
        "temp_min": 22.8,
        "temp_max": 22.8,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 76
      },
      "wind": {
        "speed": 0.69,
        "deg": 94,
        "gust": 3.44
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 06:00:00"
    },
    {
      "dt": 1749286800,
      "main": {
        "temp": 22.96,
        "feels_like": 23.92,
        "temp_min": 22.96,
        "temp_max": 22.96,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 57
      },
      "wind": {
        "speed": 0.6,
        "deg": 114,
        "gust": 0.98
      },
      "visibility": 10000,
      "pop": 0.51,
      "rain": {
        "3h": 0.44
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-07 09:00:00"
    },
    {
      "dt": 1749297600,
      "main": {
        "temp": 23.26,
        "feels_like": 24.23,
        "temp_min": 23.26,
        "temp_max": 23.26,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 99,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 51
      },
      "wind": {
        "speed": 1.09,
        "deg": 99,
        "gust": 8.18
      },
      "visibility": 10000,
      "pop": 0.6,
      "rain": {
        "3h": 1.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 12:00:00"
    },
    {
      "dt": 1749308400,
      "main": {
        "temp": 26.34,
        "feels_like": 26.34,
        "temp_min": 26.34,
        "temp_max": 26.34,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1010,
        "humidity": 93,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 32
      },
      "wind": {
        "speed": 2.25,
        "deg": 87,
        "gust": 7.96
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.81
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 15:00:00"
    },
    {
      "dt": 1749319200,
      "main": {
        "temp": 27.25,
        "feels_like": 31.22,
        "temp_min": 27.25,
        "temp_max": 27.25,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 88,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 501,
          "main": "Rain",
          "description": "moderate rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 30
      },
      "wind": {
        "speed": 2.79,
        "deg": 84,
        "gust": 7.09
      },
      "visibility": 9165,
      "pop": 1,
      "rain": {
        "3h": 3.11
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 18:00:00"
    },
    {
      "dt": 1749330000,
      "main": {
        "temp": 28.53,
        "feels_like": 32.56,
        "temp_min": 28.53,
        "temp_max": 28.53,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 75,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 16
      },
      "wind": {
        "speed": 2.78,
        "deg": 80,
        "gust": 6.4
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.9
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-07 21:00:00"
    },
    {
      "dt": 1749340800,
      "main": {
        "temp": 24.78,
        "feels_like": 25.77,
        "temp_min": 24.78,
        "temp_max": 24.78,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 94,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 18
      },
      "wind": {
        "speed": 1.69,
        "deg": 88,
        "gust": 6.92
      },
      "visibility": 10000,
      "pop": 1,
      "rain": {
        "3h": 1.6
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 00:00:00"
    },
    {
      "dt": 1749351600,
      "main": {
        "temp": 22.91,
        "feels_like": 23.89,
        "temp_min": 22.91,
        "temp_max": 22.91,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1009,
        "humidity": 101,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 27
      },
      "wind": {
        "speed": 0.8,
        "deg": 117,
        "gust": 6.45
      },
      "visibility": 10000,
      "pop": 0.68,
      "rain": {
        "3h": 1.07
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 03:00:00"
    },
    {
      "dt": 1749362400,
      "main": {
        "temp": 22.93,
        "feels_like": 23.89,
        "temp_min": 22.93,
        "temp_max": 22.93,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 39
      },
      "wind": {
        "speed": 0.38,
        "deg": 143,
        "gust": 0.74
      },
      "visibility": 10000,
      "pop": 0.59,
      "rain": {
        "3h": 0.46
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 06:00:00"
    },
    {
      "dt": 1749373200,
      "main": {
        "temp": 23.1,
        "feels_like": 24.08,
        "temp_min": 23.1,
        "temp_max": 23.1,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 72
      },
      "wind": {
        "speed": 0.31,
        "deg": 15,
        "gust": 0.05
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.23
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-08 09:00:00"
    },
    {
      "dt": 1749384000,
      "main": {
        "temp": 23.57,
        "feels_like": 24.59,
        "temp_min": 23.57,
        "temp_max": 23.57,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 69
      },
      "wind": {
        "speed": 0.62,
        "deg": 71,
        "gust": 4.59
      },
      "visibility": 10000,
      "pop": 0.36,
      "rain": {
        "3h": 0.32
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 12:00:00"
    },
    {
      "dt": 1749394800,
      "main": {
        "temp": 29.24,
        "feels_like": 33.66,
        "temp_min": 29.24,
        "temp_max": 29.24,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 72,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 62
      },
      "wind": {
        "speed": 2.8,
        "deg": 98,
        "gust": 6.11
      },
      "visibility": 10000,
      "pop": 0.93,
      "rain": {
        "3h": 0.58
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 15:00:00"
    },
    {
      "dt": 1749405600,
      "main": {
        "temp": 31.91,
        "feels_like": 35.72,
        "temp_min": 31.91,
        "temp_max": 31.91,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1008,
        "humidity": 56,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 54
      },
      "wind": {
        "speed": 3.75,
        "deg": 87,
        "gust": 6
      },
      "visibility": 10000,
      "pop": 0.58,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 18:00:00"
    },
    {
      "dt": 1749416400,
      "main": {
        "temp": 30.55,
        "feels_like": 33.91,
        "temp_min": 30.55,
        "temp_max": 30.55,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1006,
        "humidity": 60,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10d"
        }
      ],
      "clouds": {
        "all": 47
      },
      "wind": {
        "speed": 3.47,
        "deg": 86,
        "gust": 5.76
      },
      "visibility": 10000,
      "pop": 0.39,
      "rain": {
        "3h": 0.24
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-08 21:00:00"
    },
    {
      "dt": 1749427200,
      "main": {
        "temp": 26.67,
        "feels_like": 29.18,
        "temp_min": 26.67,
        "temp_max": 26.67,
        "pressure": 1012,
        "sea_level": 1012,
        "grnd_level": 1007,
        "humidity": 82,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "clouds": {
        "all": 34
      },
      "wind": {
        "speed": 2.27,
        "deg": 90,
        "gust": 6.67
      },
      "visibility": 10000,
      "pop": 0.31,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2025-06-09 00:00:00"
    },
    {
      "dt": 1749438000,
      "main": {
        "temp": 23.11,
        "feels_like": 24.09,
        "temp_min": 23.11,
        "temp_max": 23.11,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1009,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 13
      },
      "wind": {
        "speed": 0.83,
        "deg": 129,
        "gust": 3.08
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.39
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 03:00:00"
    },
    {
      "dt": 1749448800,
      "main": {
        "temp": 22.92,
        "feels_like": 23.88,
        "temp_min": 22.92,
        "temp_max": 22.92,
        "pressure": 1013,
        "sea_level": 1013,
        "grnd_level": 1008,
        "humidity": 100,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 24
      },
      "wind": {
        "speed": 0.72,
        "deg": 126,
        "gust": 2.27
      },
      "visibility": 10000,
      "pop": 0.45,
      "rain": {
        "3h": 0.34
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2025-06-09 06:00:00"
    },
    {
      "dt": 1749459600,
      "main": {

2025-06-05 17:35:50,747 - wildfire_kg.tools.weather - INFO - API response for More Tomorrow: {"cod": "200", "message": 0, "cnt": 40, "list": [{"dt": 1749178800, "main": {"temp": 26.18, "feels_like": 26.18, "temp_min": 24.5, "temp_max": 26.18, "pressure": 1012, "sea_level": 1012, "grnd_level":...
2025-06-05 17:35:50,748 - wildfire_kg.tools.weather - INFO - WEATHERTOOL: 8 forecast entries for More Tomorrow on 2025-06-07
Error running target function: Recursion limit of 25 reached without hitting a stop condition. You can increase the limit by setting the `recursion_limit` config key.
For troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/GRAPH_RECURSION_LIMIT
Traceback (most recent call last):
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langsmith/evaluation/_arunner.py", line 1236, in _aforward
    await fn(
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langsmith/run_helpers.py", line 538, in async_wrapper
    raise e
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langsmith/run_helpers.py", line 524, in async_wrapper
    function_result = await asyncio.create_task(  # type: ignore[call-arg]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/anaconda3/lib/python3.11/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "/Users/blake/anaconda3/lib/python3.11/asyncio/tasks.py", line 339, in __wakeup
    future.result()
  File "/Users/blake/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/Users/blake/anaconda3/lib/python3.11/asyncio/tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/var/folders/xg/71m7ljjd5dvbxqsym0xn0qv80000gn/T/ipykernel_32199/774810132.py", line 111, in target_func
    result = await agent_graph.ainvoke(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 2769, in ainvoke
    async for chunk in self.astream(
  File "/Users/blake/Documents/School/UCSD/Capstone/dev/wildfire-kg/applications/wildfire-kg-api/venv/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 2673, in astream
    raise GraphRecursionError(msg)
langgraph.errors.GraphRecursionError: Recursion limit of 25 reached without hitting a stop condition. You can increase the limit by setting the `recursion_limit` config key.
For troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/GRAPH_RECURSION_LIMIT

Evaluation complete for agent=llama3-sdsc (temp_cfg=0.1), kg=llama3-sdsc (temp_cfg=0.1)

Results Summary:
==================================================
Response Accuracy: 83.41%
Tool Usage Accuracy: 92.35%
==================================================

================================================================================
ALL EVALUATIONS COMPLETE
================================================================================

Overall Results Summary:
================================================================================

,Agent Model,KG Model,Agent Temperature,KG Temperature,Response Accuracy,Tool Usage Accuracy,Examples,Dataset
0,llama3-sdsc,llama3-sdsc,0.1,0.1,83.41%,92.35%,34,wildfire-kg-eval-20250605_171033

================================================================================
Evaluation complete - view detailed results in the LangSmith UI
All evaluations complete!


--- Overall Summary of Evaluation Runs ---

Model: llama3-sdsc, KG Model: llama3-sdsc, Temperature: 0.1, 0.1
  Response Accuracy: 83.41%
  Tool Usage Accuracy: 92.35%
  Detailed results table:

,inputs.question,outputs.messages,error,reference.expected_response,feedback.response_contains,feedback.tool_usage,execution_time,example_id,id,outputs.output
0,According to the National Interagency Fire Cen...,[content='According to the National Interagenc...,None,"[National Interagency Fire Center, acres, 2022]",1.00,1.0,23.068031,06772e90-99df-44e1-a484-3109203ca250,b454a2b0-ba43-4db2-8fdd-dd152c2bb81f,NaN
1,How windy is it in Bakersfield right now?,[content='How windy is it in Bakersfield right...,None,"[Bakersfield, Wind, mph]",1.00,0.9,24.937872,17b8447c-aa7e-4a3e-ae3a-f7d6d85a3d88,4fdb0935-c167-457e-8a38-0a372be6c2b7,NaN
2,How many trees and shrubs are present in CASBC...,[content='How many trees and shrubs are presen...,None,"[3, 29]",1.00,1.0,77.920764,03db411b-ffe3-4db4-8143-4dc1882896b1,c2bb6b91-48f7-407f-8bc1-292bd44401f8,NaN
3,What is the leaf area index (LAI) for CASBC_00...,[content='What is the leaf area index (LAI) fo...,None,[0.7],1.00,1.0,57.159485,34237582-ca3e-4e3b-9ef6-ada1edea9cdd,b25571cb-42c9-4ec0-9835-61b8ad460deb,NaN
4,What is the overstory shrub volume (OSvol) for...,[content='What is the overstory shrub volume (...,None,[0.0],1.00,1.0,65.431331,3536ab90-6175-4a11-99a6-a4f7cf8a8b64,1f4293de-a03a-4608-b04f-efa0a0b1513b,NaN
...,...,...,...,...,...,...,...,...,...,...
63,What was the average temperature in San Diego ...,[content='What was the average temperature in ...,None,"[San Diego, yesterday, average Temperature, °F]",1.00,0.9,22.107910,d5041d09-fb34-46f5-ba87-6f1b15e93bd3,5651c108-e0a5-4b81-80a5-4eb0dbd545e1,NaN
64,What is the current reported containment level...,"[content=""What is the current reported contain...",None,"[MountainView Fire, Napa County, containment, %]",0.25,1.0,16.725436,e39de548-f202-4b03-8874-98ba42893ee3,c75fccbb-af03-48ae-b79d-1cfa594135d1,NaN
65,How many plots are there in Santa Barbara Coun...,[content='How many plots are there in Santa Ba...,None,"[62, Thomas Fire]",1.00,1.0,82.366181,d4dc3b24-1ef7-42e2-9805-4fd37eafaa35,e9165737-e2a9-4f81-a158-0df0a2aa56cb,NaN
66,What is the basal area value for CASBC_0006_20...,[content='What is the basal area value for CAS...,None,[84.6],1.00,0.9,89.836143,ea1515f8-4419-42ad-8029-cc730fce3043,159099a6-8d43-4dbb-8342-35744a49c7e2,NaN
67,Tell me the weather forecast for Los Angeles t...,NaN,GraphRecursionError('Recursion limit of 25 rea...,"[Los Angeles, tomorrow, forecast, Humidity, %]",0.00,0.5,88.337946,f73311da-fa80-406f-a85e-8fc03a6c7d8b,88946400-efce-4442-8208-dbb25f4c797d,NaN